README.md
First pull request on the public repo woo!
Fix a broken link in the README.
None
The text wasn't rendered as a link.
I looked at the rendered README on Github.
None.
=> Fix topdoc link.

.github/CONTRIBUTING.md
This PR fixes #3.
- added link/sections for:
- code of conduct
- cla signing
- filing issues (and security issues separately)
- removed old internal adobe setup instructions
- small typo fix
Relevant issue: #3 
Moar docs
Nope
=> 📝 Contributor guideline tweaks

package.json
Preparing to release version 2.6.0 on npm. I've updated the name in `package.json` to `@adobe/spectrum-css`. 
https://github.com/adobe/spectrum-css/issues/21
We need to release this publicly to npm. The `spectrum-css` namespace is already taken. We own the [NPM Adobe org](https://npmjs.com/org/adobe). Makes sense to scope this under adobe and release it there. 
Confirmed it still builds
=> updated name to @adobe/spectrum-css

tasks/resources/docs/js/docs.js
remove unnecessary date math during scroll handler, slightly improve scroll speed
Relates to #6 
Learning chrome devtools perf tab 😄, helping this sweet project where I can
With chrome devtools perf tab
Before:
After:
=> ⚡️ #6: improve scroll performance a teeny bit

README.md
- formatting consistency
- added TOC
- moved "where is JS" to top
- made notes when sections contained adobe-only firewall links
- linked to contribution guidelines, removed 'learn more' section that linked to internal top-level spectrum docs
This issue relates to #17, but I am not sure that it closes it.
=> 📝 readme tweaks

src/typography/index.css, tasks/build-css.js, tasks/lib/postcss-notnested.js
This PR adds a quick postcss plugin that removes selectors that make assumptions about nesting. This enables us to add behaviors that only apply when the interface is scaled. 
This PR also reverts d65d0ab2827285fbb5e931eb4270301f6c8cd786 (which fixes #34, but breaks 94ade838d3e84bb2279f6d71e6e7ecfcfa8443f2).
#34 
94ade838d3e84bb2279f6d71e6e7ecfcfa8443f2 introduced a fix that increased the specificity of a selector such that large interfaces would get the correct font size, but it broke this for non-scaled interfaces as the assumption of nesting resulted in an invalid selector.
This change removes the invalid selectors, making it possible to safely assume nesting in selectors.
After this change, if you use an `&` in `index.css` as follows:
```css
&.spectrum-Body,
.spectrum-Body { …
```
=> Fix stray & in build output due to assumptions about nesting

docs/typography/typography-code.yml
… also try to show off a multiline example. It's weird because the different sizing variants now all show up in the same line (see screenshot below). Probably needs some work.
This closes #47.
#47
=> 📝 use code tags instead of p tags for code typography example in docs

src/toast/index.css
Flex shorthand and some dead code broke IE 11.
#64 
Opened it up in IE 11, success.
=> Fix Toast layout in IE11, fixes #64

src/dropdown/index.css, src/menu/index.css
IE11 compatibility for dropdowns.
#74 
In VM (Windows 10 IE11), OS X (Chrome latest)
=> [IE11] fix dropdown and menu width

src/button/index.css
For icons in deletable tags, fall back to how we used to center things to appease the Safari 10 gods.
#66 
A quick scroll through in:
* Safari 10
* Chrome
=> Fix deletable tag icon alignment in Safari 10, fixes #66

src/button/index.css
A hacky little workaround (the best kind)  for a good 'ol Safari 10 issue: https://bugs.webkit.org/show_bug.cgi?id=169700
#76 
I checked it in Safari 10, then tested the following to make sure there were no weird side effects:
* Chrome
* Firefox 
* IE 11
* Safari 11
=> Fix text alignment when text < min-width in Safari 10

docs/accordion/accordion.yml, src/accordion/index.css
Fix for Issue #81, related to RSP-786
The WAI-ARIA design pattern for Accordion has changed from WAI-ARIA 1.0 to WAI-ARIA 1.1.
WAI-ARIA 1.0 implemented Accordion using role="tablist", which, in addition to being somewhat confusing to a keyboard user, was problematic for users of the JAWS screen reader. Basically, using role="tablist" on the Accordion switches JAWS into forms mode when an Accordion item header receives focus. In forms mode, content within the expanded panels cannot be accessed using the screen reader. One can exit forms mode to access panel content by pressing the Esc key, but if the Accordion happens to be a descendant of a Dialog, the Esc key will also close the Dialog. There doesn't seem to be a good workaround for this other than switching to the WAI-ARIA 1.1 design …
=> Accordion: Update implementation to follow WAI-ARIA 1.1 design pattern (#81)

src/calendar/index.css
Fix calendar rendering in Edge
#99 
Manually checked both Edge and Chrome, rendering in both is identical to previous version in Chrome.
=> Use flexbox to position Calendar day of week headings, fixes #99

.travis.yml, gulpfile.js, package-lock.json, package.json, tasks/build.js, tasks/sass-compile.js
Add sass compiling validation phrase while building the library. 
It is super fast at least for now. If we could integrate it with build task. Every change we made could be ensure not breaking the angular-cli like tool.
#61 
Add a super fast sass compiling phrase to catch the CSS error.
We have this validation phrase for @adcloud/spectrum-css for months. It helps catch a few CSS errors and ensure the spectrum-css could be used by the angular-cli.
=> Add sass compiling validation phrase while building the library

docs/accordion/accordion.yml
Better document markup change from WAI-ARIA 1.0 to WAI-ARIA 1.1.
Add code comments to better explain backward-compatible markup change.
#81 and #83
Per comment https://github.com/adobe/spectrum-css/pull/83#issuecomment-467993470
- [NA] Bug fix (non-breaking change which fixes an issue)
- [NA] New feature (non-breaking change which adds functionality)
- [NA] Breaking change (fix or feature that would cause existing functionality to change)
=> [Documentation] Accordion: Update implementation to follow WAI-ARIA 1.1 design pattern (#81)

docs/rating/rating.yml, src/rating/index.css
In some use cases, a Rating component needs to be `readOnly`, and simply show the current rating. When `readOnly` is true, the Rating should not respond to hover events.
```css
.spectrum-Rating {
&.is-disabled {
cursor: default;
pointer-events: none;
}
}
```
Should be:
```css
.spectrum-Rating {
&.is-disabled,
&.is-readonly {
cursor: default;
pointer-events: none;
}
}
```
#109 
In some use cases, a Rating component needs to be `readOnly`, and simply show the current rating. When `readOnly` is true, the Rating should not respond to hover events.
Tested in React Spectrum. And Spectrum-CSS docs.
Also, see working prototype: https://codepen.io/mijordan/pen/KEVEKO
- [NA] Breaking change (fix or feature that would cause existing functionality to change)
=> Issue-109 Rating: add readOnly state

src/sidenav/index.css
Width token for side navigation component is being deprecated. Removing from CSS due to it causing unwanted restriction. Side navigation is intended to have a product-defined width, which is difficult to do with this value in the CSS.
=> removed width from Side Nav component

docs/card/card-asset.yml, docs/card/card-gallery.yml, docs/card/card-quiet-file.yml, docs/card/card-quiet-folder.yml, docs/card/card-quiet-large.yml, docs/card/card-quiet-small.yml, docs/card/card-small.yml, docs/card/card.yml, src/card/index.css, src/card/skin.css
`.spectrum-Card` only accounts for `:focus` style on the card itself.
Currently, `.spectrum-Card` only accounts for `:focus` style on the card itself.
This PR adds `:focus-ring` styles so that the `.spectrum-Card` will render focused style when its parent has focus.
#105 
In a grid view, where the `.spectrum-Card` is has `role="gridcell"` within a parent element with `role="row"`, the`.spectrum-Card` should render its focus style when the parent row receives focus.
Tested against React-Spectrum PR #495
=> Issue-105 Card: display focus ring when a parent row element has focus

docs/dropdown/dropdown.yml, docs/inputgroup/datepicker-range-quiet.yml, docs/inputgroup/datepicker-range.yml, src/inputgroup/index.css, src/inputgroup/skin.css, topdoc/resources/js/docs.js
Add Datepicker range variants to InputGroup to support date and datetime range.
Add `.spectrum-Datepicker--range` and `.spectrum-Datepicker--datetimeRange` to `.spectrum-InputGroup` style definitions.
Update docs to support adding `.is-focused` style to InputGroup on focus, similar to how we do it for `.spectrum-Slider`. 
#54 
[✨ RSP-631: Datepicker range styles added](https://github.com/adobe/spectrum-css/pull/13)
Spectrum/spectrum-css/issues/663
JIRA issue RSP-631
Calendar supports range selection but Datepicker component does not display the date range.
Tested in Spectrum docs and as part of a related React-Spectrum PR.
=> ✨ RSP-631 InputGroup: add Datepicker range variant

src/dropdown/index.css
/title
#121
is bug
mad scrolling in Chrome and IE 11
Chrome:
IE11:
=> Fix Dropdown label truncation when text too long, fixes #121

docs/sidenav/sidenav-icon.yml, src/sidenav/index.css, src/sidenav/skin.css
Sidenav variant that allows for icons on parent-level navigation menu items
https://github.com/adobe/spectrum-css/issues/55
=> Side Nav: Icon variant

tasks/build-css.js, tasks/lib/postcss-notnested.js
Use `notnested` to make sure stray `&` doesn't appear for Typography and Page, also fix `notnested` to be a little smarter about replacing complex selectors.
#134 
Built the project and diffed the output directories, ensuring that the change fixed only the problem at hand (`gulp; cp -r dist distnew; git checkout master; gulp; diff -rq dist distnew;` returns only two files)
=>  Fix stray & in index-vars.css for Page and Typography

src/button/index.css
This fix accounts for issues introduced by a Safari 10 fix https://github.com/adobe/spectrum-css/commit/9a790d52a8d8e079d6da9b660bb0e95f2acd30f4 that broke the ability to use multiple spans inside of the button label, which is required for Korean internationalization.
#153 
Tested and working in:
* Safari 10
* Safari 11
* Safari 12
* IE 11
* Edge
* Firefox
* Chrome
=> Fix Button label display for i18n

.topdocrc, src/inputgroup/index.css, tasks/build-css.js, tasks/build-docs.js, tasks/lib/postcss-strip-comments.js
This kills the Apache headers, dead comments, and other bits in output.
Closes #68 
Closes #145 
Build output diffed.
=> Strip comments in built output

docs/examples/dialog.html, docs/examples/dialogAlert.html, docs/examples/dialogWithCheckbox.html, docs/examples/dialogWithWrappingButtons.html, docs/examples/dialogWrapping.html, docs/examples/vars.html, src/button/index.css
Adjust the vertical alignment of text within buttons with a gross hack.
Also, fix font family on examples.
Fixes #185
* Chrome 74.0.3729.169 on macOS 10.12.6 (retina)
* Firefox 66.0.5 on macOS 10.12.6 (retina)
* Safari 12.1.1 on macOS 10.12.6 (retina)
* Edge 42.17134.1.0 on Windows 10 (retina)
* Firefox 67.0.1 on Windows 10 (retina)
* Chrome 74.0.3729.169 on Windows 10 (retina)
* Chrome 74.0.3729.169 on macOS 10.12.6 (non-retina)
* Safari 12.1.1 on macOS 10.12.6 (non-retina)
* Safari 11 on macOS 10.11.6 (non-retina)
* Edge 42.17134.1.0 on Windows 10 (non-retina)
* Chrome 74.0.3729.169 on Windows 10 (non-retina)
* Firefox 67.0.1 on Windows 10 (non-retina)
* Firefox 66.0.5 on macOS 10.12.6 (non-retina)
=> Fix vertical alignment of Button text

docs/form/index.yml, src/fieldlabel/index.css
This PR adds support for a structured Form layout with labels above the form fields.
#199 
This was needed for the Panels prototype #156 
iScrolled
- New feature (non-breaking change which adds functionality)
=> Form: labelsAbove

components/commons/fonts.css, components/typography/docs/typography-international.yml, components/typography/font.css
This PR fixes fallback fonts for Adobe Clean UX as well as ar, he, ja, zh-Hans, zh-Hant, and ko.
#189 
#232 
Examples have been added for Hebrew that show the new fonts in action. Additionally, the fallbacks for ja, zh-Hans, zh-Hant, and ko have been confirmed with @yloubry
=> Font fallbacks

.travis.yml, .yarnrc
Using `.yarnrc` file to enforce `workspaces` and `ignore-optional` always true for spectrum-css.
=> Fix yarn optional-dependency issue.

components/textfield/index.css
update @spectrum-css/textfield from 2.0.0-alpha.5 to 2.0.0-alpha.6
Jira: https://jira.corp.adobe.com/browse/SDS-2298
Github: https://github.com/adobe/spectrum-css/issues/275
Fixes opacity on placeholder text in combination with a CSS resetter. 
Fixed a visual bug where textfields receive an opacity setting for placeholders when a CSS resetter is used. 
Example CSS Resetter is https://github.com/csstools/normalize.css/blob/master/normalize.css#L297
Also bumps up textfield's version in package.js 
Jira: https://jira.corp.adobe.com/browse/SDS-2298
Github: https://github.com/adobe/spectrum-css/issues/275
Allows Spectrum CSS textfields to remain a consistent look in combination with a CSS resetter.
1. Added an import of https://github.com/csstools/normalize.css/blob/master/normalize.css
in …
=> fix: SDS-2298 add correct placeholder opacity for textfields, closes #275

.travis.yml, backstop_data/backstop_test.js, package.json
1. Enhance backstopjs testing script to support configurable bitmaps reference path. It can make update bitmaps reference easier.
2. Add `npm run watch`.
3. Update travis ci script to use `watch` instead of `dev` to avoid unnecessary rebuild.
Test with latest mac and travis-ci passed
=> test(backstopjs): support configurable bitmaps reference path

.github/ISSUE_TEMPLATE/--bug-report.md, .github/ISSUE_TEMPLATE/--support-request.md, .github/PULL_REQUEST_TEMPLATE.md
- **How this was tested:** On this actual PR!
INCEPTION
=> docs: make issue report template fields for environment bold

components/card/index.css, components/card/metadata/card.yml, components/card/skin.css, components/dropdown/metadata/dropdown.yml, components/site/index.css, components/site/skin.css, gulpfile.js, package.json, site/getting-started.pug, site/includes/example.pug, site/includes/footer.pug, site/includes/nav.pug, site/includes/pageBottom.pug, site/includes/sidebar.pug, site/index.pug, site/resources/css/docs.css, site/resources/js/Search.js, site/resources/js/docs.js, site/resources/js/enhancement.js, site/resources/js/site.js, site/templates/siteComponent.pug, site/util.js, tools/bundle-builder/docs/index.js, tools/bundle-builder/lib/exec.js
This PR implements the fancy new site design.
Also added is the Small Horizontal card, required for the site design.
- How this was tested: A little scrolly scroll on the deployed (internal) test site https://git.corp.adobe.com/pages/lawdavis/spectrum-css-new-design/docs/
- Browser(s) and OS(s) this was tested with: Chrome 75 on macOS
Not implemented:
- Bundle version switcher
- Spectrum website card links
- Footer contact us link
- Getting started
=> Temporary site design update for 2.14 release

backstop_data/engine_scripts/puppet/injectSpectrumThemeAndScale.js
It seems that VR testing was applying the `.spectrum` classname in the wrong place, resulting in incorrect output.
- **How this was tested:** Local backstop testing
=> test(ci): fix application of classes to docs for theme/scale

README.md
The README still references `npm` for package installations, this PR fixes that. This was discovered during work on #269 
- **How this was tested:** commands ran on terminal
=> docs: fix quickstart docs to reference yarn

README.md, components/calendar/index.css
Changes display styling on Calender heading away from absolute positioning to flexbox order.
Tested in Chrome, Safari and FireFox
While setting the parent to `dir="rtl"` switches the next and previous buttons there is still a need for a modifier selector to flip the caret direction.
=> chore: refactor Calendar header to use flexbox per issue #269

components/calendar/metadata/calendar.yml
Calendar weekdays need to be summarized to single letter as per https://github.com/adobe/spectrum-css/issues/294
N/A
N/A
=> docs: update week labels to single character, fixes #294

components/fieldgroup/index.css
Added radio warp for when there are too many radios or radio labels exceed container width.
https://github.com/adobe/spectrum-css/issues/268
BEFORE:
AFTER:
=> Added flex-wrap: wrap to FieldGroup

components/calendar/index.css
While testing for the 2.14 release, I discovered some extra padding on the calendar heading, and when removed, I found that calendar headings no longer truncate correctly or align vertically in the large scale. Also, the horizontal alignment of the text was wrong due to an Action Button margin applied to adjacent siblings. This fixes all that. 
This relates to work done in #269 
- **How this was tested:** Load up docs, give a calendar a large heading like `August of the good year 2017`, it should truncate, switch to large scale, it should line up vertically
- **Browser(s) and OS(s) this was tested with:** Chrome 77 on macOS
=> fix: fix Calendar title wrapping/alignment, related to #269

package.json, yarn.lock
backstopjs => puppeteer@1.2.0 => https-proxy-agent@2.2.2
We need to upgrade https-proxy-agent to 3.0.0 to fix security vulnerabilities.
=> fix(vulnerabilities): https-proxy-agent@2.2.2 => https-proxy-agent@^3.0.0

css/main.scss
If Typekit times out, we get `.wf-inactive` instead of `.wf-active`. This PR makes things still display.
- **How this was tested:** load site with WiFi off
=> docs: fix FOUT if Typekit times out

components/Sidebar.js, components/css/sidebar.scss
Fix width of the sidebar.
- **How this was tested:** load site, get large, expand menu, look to make sure Spectrum CSS doesn't wrap
=> fix: sidebar width is too small to fit "Spectrum CSS" in large scale

css/main.scss, pages/_app.js
This makes things wrap nicely on tiny phones.
- **How this was tested:** Use device inspector, select iPhone 5, switch to Large scale
- **Browser(s) and OS(s) this was tested with:** iOS Simulator, Chrome
=> docs: fix switcher wrapping on small screens

components/css/componentPage.scss, pages/_app.js, pages/components/id.js
Fix Dialog page on next.js documentation
- **How this was tested:** open Dialog and check it out
=> docs: fix dialog presentation on docs page

components/checkbox/skin.css, components/radio/skin.css, components/toggle/skin.css
This PR reverts the Checkbox/Radio/Switch color change, addressing #355 by using the emphasized variant by default.
- **How this was tested:** visit Checkbox/Radio/Switch, observe blue goodness
=> fix: revert Checkbox/Radio/Switch color change, fixes #355

tools/bundle-builder/vars/index.js, tools/component-builder/css/lib/varUtils.js
Include all the variables referred to up the chain.
1. Run the following:
```
git co master
gulp buildUniqueVars
cp dist/vars/spectrum-light-unique.css /tmp/spectrum-light-unique-master.css
git co uniquevars
gulp buildUniqueVars
diff /tmp/spectrum-light-unique-master.css dist/vars/spectrum-light-unique.css
```
2. Observe the output, you should see the following vars
Ensure the following vars are present:
```
--spectrum-global-color-red-400
--spectrum-global-color-green-400
--spectrum-global-color-green-600
--spectrum-global-color-orange-400
--spectrum-global-color-orange-600
--spectrum-global-color-orange-500
```
Additionally, these vars should be present in other files:
```
--spectrum-global-color-static-blue-600
--spectrum-global-font-weight-black …
```
=> fix: add missing variables to -unique files, closes #336

site/resources/js/enhancement.js, site/resources/js/polyfills.js
The dev site Dropdown enhancements were broken in IE 11 as they rely on `CustomEvent`.
This PR adds a polyfill for `CustomEvent` and works around IE 11's lack of support for the second argument to [`classList.toggle()`](https://developer.mozilla.org/en-US/docs/Web/API/Element/classList)
1. Dust of IE 11 VM (blow in serial port if it doesn't start)
1. Open up dev docs site
1. Click Theme or Scale dropdown
1. Select a new Theme or Scale
1. Theme/Scale switches, dropdown closes
- **Browser(s) and OS(s) this was tested with:** IE 11 on Windows 8.1
=> docs: fix dev site Dropdown enhancements in IE 11

components/dropdown/metadata/dropdown.yml, components/menu/index.css, components/menu/metadata/menu.yml, components/tabs/metadata/tabs.yml, site/templates/siteComponent.pug
Adds `spectrum-Menu-itemIcon` classname.
Adds menu specific icon classname for issue #202 and changes all menu instance with icons.
=> Add menu icon class

README.md
This fixes #370 
Before:
After:
=> docs(readme): fix broken url workflow icons

components/ResourceCard.js
[SDS-3251](https://jira.corp.adobe.com/browse/SDS-3251)
Making all resources links open in a `_blank` new window unless specified as a `target` prop.
Opens by default the resource cards in a new window.
clicked on a card.
=> fix: opening View Guielines link in new window (SDS-3251)

components/css/componentPage.scss, pages/components/id.js
This fixes the detail table font size on large scale as well as line height for the first entry.
- **How this was tested:** Load, use large, examine detail table
=> docs: fix detail table styling

components/css/siteSearch.scss
[SDS-3248](https://jira.corp.adobe.com/browse/SDS-3248) Sidebar search input field got over-written by the Combobox component on the page. 
This re-sets the search input box in the sidebar. 
There is debate if this should be fixed with a reset or with a re-ordering of the requested stylesheet rules. 
Navigated to 3 pages:
/components/combobox/ (viewport mobile & desktop)
/components/search
/ (homepage)
Chrome Desktop Version 80.0.3955.4 (Official Build) canary (64-bit)
=> fix: normalizing sidebar search input field for Combobox site (SDS-3248)

next.config.js, pages/_document.js
=> fix: point footer and adobe launch to production while next export

components/actionbar/index.css, components/actionbar/metadata/actionbar.yml
Added the relative width in actionbar popover as mentioned in #319 
- **How this was tested:** Using steps in issue #319 
=> Actionbar popover width fixed

components/rating/metadata/rating.yml, site/resources/js/enhancement.js
This enables focus and clicking on Ratings to show the focus and selected states.
- **How this was tested:** Tab to focus on Rating, observe focus.
=> docs: add Rating enhancement to show focus, closes #249

package.json, yarn.lock
Fix the security vulnerabilities caused by handlebar@^4.3.0
=> fix: fix security vulnerabilities introduced by handlebars

components/dialog/index.css, components/dialog/metadata/dialog.yml, site/resources/js/enhancement.js, site/templates/siteComponent.pug
* fix Dialog examples if page loaded directly
* add wrapped Dialog example
- **How this was tested:** open `dialog.html`, scroll to the bottom, clicky the button
=> fix: correct positioning of children of wrapped Dialogs, closes #389

README.md, components/vars/README.md
[SDS-4424](https://jira.corp.adobe.com/browse/SDS-4424) Update the DNA token update documentation and provide some error resolving hints.
This surfaced during the  typography updates : [SDS-2513](https://jira.corp.adobe.com/browse/SDS-2513)
More discussion about this can be found in #388
Previewed the Markdown in VS Code
=> docs: update DNA token update documentation (SDS-4424) #388

tools/component-builder/css/plugins/postcss-custom-properties-mapping.js
This is a workaround for https://github.com/parcel-bundler/parcel/issues/3881
Effectively, this tells the algorithm that adds fallback CSS custom properties to ignore them when they appear inside of a `url()`. The variables within the `url()` are already doing nothing (see #223), this just removes the fallback that was causing Parcel bundling to fail in Leonardo.
- **How this was tested:** `cd packages/textfield; gulp build`
=> fix: don't try to add fallbacks inside of url(), related to #223

site/truncation.pug, site/wrapping.pug
In testing #415, I realized the Wrapping and Truncation studies from #176  did not make it when we moved to individually versioned components and the new dev site. This PR adds them back.
- **How this was tested:** `gulp dev; open http://localhost:3000/docs/truncation.html; open http://localhost:3000/docs/wrapping.html`
=> docs: restore wrapping/truncation studies

components/barloader/index.css
This PR fixes the wrapping of BarLoader/Meter labels. This was a regression caused by changing the `flex: 1` to `flex: 1 0 auto` for IE 11 support, when it should have been `flex: 1 1 0%`.
- **How this was tested:** open link, use eyes
- **Browser(s) and OS(s) this was tested with:** Chrome on macOS, IE 11ing
✅Chrome 78
✅IE 11
=> fix: text wrapping in Meter/BarLoader, fixes #420

components/inputgroup/index.css, components/inputgroup/metadata/datepicker.yml
Corrects the width of InputGroup buttons, fixes #399 
Also fixes #394 (documentation markup was wrong).
- **How this was tested:** Open Date picker examples, use eyes
=> fix: fix button width in InputGroup, fix DatePicker example, fixes #399

components/checkbox/index.css, components/radio/index.css, components/toggle/index.css
Correcting the top margin for checkboxes & radio buttons. 
https://jira.corp.adobe.com/browse/SDS-4420 closes #406, 
https://jira.corp.adobe.com/browse/SDS-4418 closes #402,
https://jira.corp.adobe.com/browse/SDS-4403 closes #403 
Adding the correct margin. There seems to be a "wrapping study" in #176 that hard-coded the value `--spectrum-global-dimension-size-75`. The correct value should be `--spectrum-global-dimension-size-85`.
@lazd  Maybe we should remove the hard-coded value instead if the wrapping study is complete.  
Go to the following pages and inspect the label for the checkbox or radio button
http://localhost:3000/docs/radio.html
http://localhost:3000/docs/checkbox.html
http://localhost:3000/docs/toggle.html
Browser(s) and OS(s): macOS Mojave 10.14.5 (18F203)
Google Chrome …
=> fix: top margin for switch, checkbox & radio button

components/search/index.css, components/search/skin.css
Fixes #409 by correctly using DNA tokens. 
- **How this was tested:** Look at example, hover on it, smile
=> fix: correct Search icon color on hover/down/focus, fixes #409

components/statuslight/index.css
This PR fixes the vertical alignment of text in Status Light by reducing the top padding to move the text upward.
- **How this was tested:** eyeballs
- **Browser(s) and OS(s) this was tested with:** all the many
✅Chrome 78.0.3904.108
✅Safari 13.0.3
✅Safari 11.1.2
✅Firefox 70.0.1 (off by a half pixel)
✅IE11 (the font doesn't render the right height, but it looks visually correct next to the dot)
✅Edge 42.17134.1.0 (off by a half pixel)
=> fix: vertical alignment of Status Light text, fixes #426

tools/component-builder/package.json
This PR declares `@spectrum-css/vars` as a `peerDependency` in `@spectrum-css/component-builder` so uses outside of Spectrum CSS will be aware that it is required.
- **How this was tested:** n/a
=> build: add vars as a peerDep, fixes #413

components/textfield/index.css
Remove resize functionality completely when textfield are disabled.
- **How this was tested:** Open textarea example, try in vain to resize the disabled textarea
=> fix: disable resize functionality when disabled, fixes #443

components/textfield/index.css
Accomplished by setting both `height` and `min-height` to the height of a textfield. It's on implementations to change `height` as necessary on input.
- **How this was tested:** view example, rejoice
=> fix: make quiet Text area 1 line tall by default, fixes #442

components/menu/index.css
adding `word-break: break-all;` to dropdown label.
In order to break "unbreakable words" like German connected nouns or urls / paths we need to allow break-all for words.
- **How this was tested:**  go to `http://localhost:3000/docs/dropdown.html` and inspect the dropdown label
- **Browser(s) and OS(s) this was tested with:**  Google Chrome Canary Version 81.0.3993.0 (Official Build) canary (64-bit) on macOS Mojave 0.14.5 (18F203)
Before:
After:
=> fix: wrapping on long words indropdowns (SDS-4649) #451

components/treeview/index.css
Be explicit about Treeview group indicator box model.
Fixes #467
- **How this was tested:** Open treeview docs, add rule: `* { box-sizing: border-box; }` and make sure the indicator was still there
=> fix: be explicit about Treeview group indicator box model

components/dropdown/index.css, site/resources/js/polyfills.js
Use a variable for the Quiet Dropdown's width, fixes #477 
Also, added `testMultistops()` function that can be ran from the console to convert everything on the page from Custom Properties to multistops. This will help testing bugs like this one.
- **How this was tested:** `gulp devHeavy`, go to Quiet Dropdown example, then `testMultistops()` in console
These kinds of bugs happen because the multistop algorithm basically takes any property with a variable and re-defines it for the large scale with the resolved, large variable value.
This works great normally, but sometimes, a variant will override a property with a bare value, when the default (no variant) version of the component defines the same property with a variable …
=> fix: large Quiet Dropdown when using multistops

components/buttongroup/index.css, components/rule/index.css, components/rule/metadata/rule.yml, components/rule/package.json
This PR does a few different things:
* Update DNA to 5.23 to catch new tokens
* Use correct DNA tokens for Rule, closes #425
* Make vertical Rule's height a variable, fixes #455
* Support vertical Rules inside of ButtonGroup, simplifying usage examples
* Add documentation on using vertical Rules inside of a flex context
- **How this was tested:** A little scrolly scroll
- **Browser(s) and OS(s) this was tested with:**  Chrome on macOS
=> fix: vertical rule doesn't render

components/dropdown/metadata/dropdown.yml, components/menu/index.css
Adding overflow-wrap and hyphen option to dropdown label and limiting the width to `80%` to force wrapping. 
In order to break "unbreakable words" like German connected nouns or urls / paths we need to allow overflow-wrap for words.
Fixes #451 ([SDS-4649](https://jira.corp.adobe.com/browse/SDS-4649)).
Previous fix was not sufficient int #452
Swap out the following text in the `components/dropdown/metadata/dropdown.yml`
go to`http://localhost:3000/docs/dropdown.html` and inspect the dropdown label
Browsers left to right:
On macOs Mojave 10.14.5 (18F203): 
Chrome Version 81.0.4027.0 (Official Build) canary (64-bit)
Safari Version 12.1.1 (14607.2.6.1.1)
FireFox 72.0.1 (64-bit)
Edge Version 80.0.361.32 (Official …
=> fix: adding overflow-wrap to dropdown #451

components/search/skin.css
I'm not sure why it works on spectrum-css but not in react-spectrum, but the order matters because it's the same specificity, maybe there's some other way so it's not order dependent?
- **Browser(s) and OS(s) this was tested with:**  Chrome  79.0.3945.117 (Official Build) (64-bit)
This is what it looks like for us without this change.
=> fix: order of psuedo selectors search 

tools/component-builder/css/legacyBuild.js, tools/component-builder/css/processors.js
When generating `index-diff.css`, we were running the `varsonly` plugin before the `import` plugin, which was working fine for most components.
Icon, however, uses imports for all of its CSS, and because `varsonly` was running before `import`, it was never seeing the actual CSS and was unable to filter out properties that only contain variables. As a result, it was wrapping ALL rules and all properties for icon in `.spectrum--large`, which resulted in a very specific selector setting the `display` property, which was overriding the rule that hides the checkbox for non-selected menu items, which was causing the checkbox to appear at all times when in Large scale, resulting in #495 .
Before, inside of `icon/dist/index-diff.css`:
```css
.spectrum--large .spectrum-Icon, .spectrum--large …
```
=> fix: fix order of processor includes when doing diff CSS, fixes #495

components/decoratedtextfield/index.css, components/decoratedtextfield/metadata/decoratedtextfield.yml, components/textfield/index.css
This PR fixes the alignment of icons inside of DecoratedTextfield and multiline Textfields (Textareas). They now (finally) match the design guidance given here https://github.com/adobe/spectrum-css/issues/494#issuecomment-578192258
- **How this was tested:** Open up DecoratedTextfield, Textarea examples, paste them over the design screenshot, and check icon position
Textarea:
DecoratedTextfield:
=> fix: alignment of icon in DecoratedTextfield and Textfield, closes #494

components/calendar/index.css, components/calendar/metadata/calendar.yml
Adding correct letter spacing for calendar title.
Changing the standard calendar example from "S M T W T F S" to "SUN MON TUE WED THU FRI SAT". 
This fixes #407
Jira: [SDS-4421](https://jira.corp.adobe.com/browse/SDS-4421)
Adding correct letter spacing for calendar title.
Also changing the standard calendar example from "S M T W T F S" to "SUN MON TUE WED THU FRI SAT". React Spectrum also features the abbreviations for their default calendar that might be something we could match. I left the other three calendar examples below the first default calendar untouched to display both options. https://react-spectrum.corp.adobe.com/storybook/?path=/story/calendar--default
Navigate to [http://localhost:3000/docs/calendar.html#variants](http://localhost:3000/docs/calenda …
=> fix: adding letter spacing for calendar title (SDS-4421) #407

components/statuslight/index.css
#508 
1. Enable Windows High Contrast Mode:
1. Select the Start button , and then select Settings > Ease of Access > High contrast.
2. To turn on high contrast mode, select the toggle button under Turn on high contrast. Windows may 
3. display a “Please wait” screen for a few seconds after which the colors on the screen change.
4. Select the theme that works best for you from the Choose a theme dropdown menu.
5. To turn off high contrast mode, select the Turn on high contrast toggle button again. Windows may again display a “Please wait” screen for a few seconds after which the colors on the screen change back to default.
3. Using Edge Chromium, Go to https://opensource.adobe.com/spectrum-css/components/statuslight/#Colors
4. Observe StatusLight indicator dots do not display in high …
=> fix: [Accessibility] StatusLight dot disappears in High Contrast Mode

components/button/metadata/actionbutton.yml, components/button/metadata/tool.yml, components/buttongroup/metadata/buttongroup.yml, components/site/index.css, components/typography/metadata/typography-body.yml, components/typography/metadata/typography-code.yml, components/typography/metadata/typography-deprecated.yml, components/typography/metadata/typography-detail.yml, components/typography/metadata/typography-heading.yml, components/typography/metadata/typography-international-deprecated.yml, components/typography/metadata/typography-international.yml, components/typography/metadata/typography-legacy.yml, components/typography/metadata/typography.yml, site/includes/nav.pug, site/templates/siteComponent.pug, tools/bundle-builder/docs/index.js
This PR does the following:
* Fixes Typography's metadata status
* Fixes Typography's usage of heading level elements (i.e. `<h1>`)
* Fixed Typography's description text
* Removes duplicate Typography examples
* Hides deprecated Typography components from the dev site menu
* Adds a landing page for Typography, link to deprecated components
* Adds Spectrum site badge for verifying links are correct
* Adds the ability to change the  "Variants" section title in dev site
* Fixes incorrect Spectrum site link for ButtonGroup
* Hides Tool from dev site menu, link to Tool from Quiet Action Button
- **How this was tested:** `gulp dev`, use eyes
Docs are deployed here for your perusal: https://git.corp.adobe.com/pages/lawdavis/spectrum-css-typogra …
=> Typography metadata fixes and deprecation bits

components/site/index.css, components/site/skin.css, components/typography/metadata/typography.yml, gulpfile.js, package.json, site/getting-started.pug, site/includes/example.pug, site/includes/exampleContent.pug, site/includes/section.pug, site/includes/sidebar.pug, site/index.pug, site/templates/individualComponent.pug, site/templates/siteComponent.pug, site/truncation.pug, site/util.js, site/wrapping.pug, tools/bundle-builder/docs/README.md, tools/bundle-builder/docs/index.js, tools/bundle-builder/index.js, tools/component-builder/package.json, yarn.lock
This pull request does the following:
* Add migration guide for new Typography API
* Switch from `markdown` (deprecated) to `markdown-it`
* Implement Spectrum classes for markdown'd links, tables, and code samples
* Use new Typography components on site template for header/body text
* Use new Typography Code component for markup examples
* Fix color styles that leaked into `site/index.css` (should be in `site/skin.css`)
* Fix header for Code on Typography landing page
* Support `sections` property in metadata to define sections
* Update documentation for component metadata to document new properties and correct errors
- **How this was tested:** Load up https://git.corp.adobe.com/pages/lawdavis/spectrum-css-typography/docs/typography.html#migratingfromdeprecatedtypography, use eyes
- …
=> Typography migration guide

components/tabs/index.css, components/tabs/metadata/tabs.yml, components/tabs/skin.css
Implements support for Tab labels as `<a>` tags, closes #670 
Corrects tab document to use `<span>` instead of `<label>`, fixes #671 
- **How this was tested:** Scroll, observe
=> feat: fix tabs markup, support anchors for labels

README.md
the readme was a bit off with respect to getting workflow icons.
=> update link to spectrum workflow icons in the README.

components/fieldlabel/metadata/fieldlabel.yml
Fixed the issue that wrong input box could get activated when clicking on a label.
- **How this was tested:** Click on each label on the "Field Label" page and ensure that the input box that's activated is the one referred to by the label (i.e. the one next to the label).
- **Browser(s) and OS(s) this was tested with:** Chrome 81 on macOS
=> fix(fieldlabel): use unique id for each input

components/button/index.css
Lookit #730 
- **How this was tested:** Clicky click
=> fix: correct OverBackground ClearButton focus-ring, fixes #730

components/checkbox/index.css
Focus rings in FF have a tendency to look like one of the lines is half the weight of the opposing side.
Before:
After:
This should also be done with button and any others
Before:
After:
- **How this was tested:** In react spectrum
- **Browser(s) and OS(s) this was tested with:** FF on Mac
=> Fix anti-aliasing issue on FF

components/tray/metadata/tray.yml, components/tray/package.json, components/tray/skin.css
There are no tokens for tray bg so I brought in Modal to bring in the missing styles.
=> fix: added modal to tray component

components/button/skin.css
Original PR from @Martskin . Thank you very much for your contribution.
I am re-creating this PR so we can have the Visual Regression Testing handled by Jenkins (like for #77). Unfortunately we don't don't support that yet on forks.
Original description from #759: 
This PR fixes ActionButton Focus-ring Active state visual issue #755
=> fix: actionButton focus-ring active state visual issue #755

components/button/skin.css
This PR fixes ActionButton Focus-ring Active state visual issue #755
=> fix: actionButton focus-ring active state visual

components/actiongroup/index.css
Original PR from @Martskin . Thank you very much for your contribution.
I am re-creating this PR so we can have the Visual Regression Testing handled by Jenkins. Unfortunately we don't don't support that yet on forks. 
Original PR description from #758:
This PR modifies the CSS of ActionGroup to add top (block start) and right (inline-end) margins to fix the wrapping issue reported in Issue #749
https://user-images.githubusercontent.com/3717760/85166502-3bc7ce00-b21c-11ea-8a22-01809ea7dbff.png
=> fix: actiongroup wrapping, fixes #749

README.md
Update the VRT related documentation to resolve #771 
=> test: update VRT instruction documentation

components/checkbox/skin.css
Fix for checkbox part of #786.
This changes checkboxes to work in the following ways in WHCM
- Have a visible focus indicator using the highlight colour
- Use Disabled colour when disabled
- Not use error colour when in error
- be able to determine the checked/unchecked/mixed state 
Note - I am unsure how to mark error state and am in discussions with Spectrum. IMO this can be tackled in a later PR.
- Run using Windows High Contrast mode both White on Black and Black on White
- Note that the colors now match the windows system colors
- Edge 85.0.564.30 on Windows 10
=> fix: allow high contrast mode for checkboxes

components/actionbar/index.css, components/actionbar/metadata/actionbar.yml, components/actionbar/package.json, yarn.lock
Fixed #807 and when parent branch was merged to main, it will fix `#894`
1. Example change
- Changed string capitalization
- Switched to use `ActionGroup`
- Changed Workflow icon size from small to medium
2. Add `@spectrum-css/actiongroup` as dependency
3. Change action bar content padding-right to be half of the padding-left to match [UI kit](https://spectrum-contributions.corp.adobe.com/page/action-bar-beta/)
Chrome/Firefox/Safari on MacOS
1. Desktop scale
2. Mobile scale
=> Spectrum tokens 17 for Action Bar

components/calendar/metadata/calendar.yml
Fixed #808
1. Change previous/next icon size to medium
UI Kit:
Example:
=> Spectrum tokens 17 for calendar

components/checkbox/metadata/checkbox.yml, components/checkbox/skin.css
Closes #816
Checkbox Emphasized vs Quiet was not implemented correctly. That has been fixed.
Checkbox has two global variables:
```
[08:33:16] @spectrum-css/checkbox directly uses global variable --spectrum-global-dimension-size-65
[08:33:16] @spectrum-css/checkbox directly uses global variable --spectrum-global-animation-duration-100
```
These are both used for properties that are currently unavailable in DNA.
A note was written on quiet vs emphasized.
=> Spectrum tokens 17 Checkbox

components/tooltip/index.css
Avoid the tooltip label overlaps on the icon and still preserved the max-width.
Fixed #847 
Before:
After:
=> Spectrum tokens 17 - Tooltip

components/pagination/skin.css
Fixed #859 
Change pagination counter text color to match with DL.
This issue is blocked by the solution of #913 
DL:
=> Spectrum tokens 17 - Pagination

components/slider/index.css, components/slider/metadata/slider.yml, components/slider/skin.css
Adding back ramp-slider and removing color-slider.
Addresses issue #829 
- added back ramp-slider
- removed color-slider from slider page that is now it's own component under [/docs/colorslider.html](/docs/colorslider.html)
URL: http://localhost:3000/docs/slider.html
Chrome Version 85.0.4183.102 (Official Build) (64-bit) on MacOS
=> fix: ramp slider (#829)

components/checkbox/index.css, components/checkbox/metadata/checkbox.yml, components/fieldgroup/index.css, components/fieldgroup/metadata/fieldgroup.yml, components/fieldlabel/metadata/form.yml, components/fieldlabel/package.json, components/radio/index.css, components/radio/metadata/radio.yml, components/radio/skin.css, components/site/index.css
This PR fixes up Checkbox and Radio's margins, docs, and typography.
It addresses #243 by setting text styles on the label of the Checkbox/Radio explicitly, instead of relying on inheritance.
It addresses #124 by removing margin from Checkbox/Radio, instead making FieldGroup required to add the margin. THIS IS A BREAKING CHANGE.
#707 is addressed by adding columns for default, invalid, and disabled for Checkbox/Radio, and moving the wrapping example to its own section.
#484 is fixed as a dep was missing from Form.
- **How this was tested:** big time scrolly scroll
=> fix: Checkbox and Radio margins, docs, and typography

components/sidenav/index.css
When a [side nav item with icon](https://opensource.adobe.com/spectrum-css/sidenav.html#icon) has long text, the icon no longer gets cut off. Fixes #895 and https://git.corp.adobe.com/React/react-spectrum-v2/issues/613.
This is needed for the upcoming GA release of a new AEP feature.
- **How this was tested:** Using steps in issue #895
- **Browser(s) and OS(s) this was tested with:** Chrome 85.0.4183.102, Safari 13.1.2, Firefox 80.0.1 on Mac OS 10.14.6
**Before**
**After**
=> Fix side nav item with long text cutting off icon

components/slider/index.css
Closes https://github.com/adobe/spectrum-css/issues/968
See issue for more details
Before: https://reactspectrum.blob.core.windows.net/reactspectrum/90e48ecca96b40cb4c4a90eb833e0e36871372b6/storybook/index.html?path=/story/slider--label-overflow
After: https://reactspectrum.blob.core.windows.net/reactspectrum/563b35205c55a6b38433830beca9aed9b8003256/storybook/index.html?path=/story/slider--label-overflow
- **Browser(s) and OS(s) this was tested with:** 85.0.4183.102, macOS 10.15
=> Try to make the slider value label less jumpy

components/actionbar/index.css
fixes #1042 
supersedes #1043 
- uses logical CSS properties to ensure padding is applied in a content direction relative manner
- **How this was tested:** Using steps in #1042 
=> fix(actionbar): ensure Poppover padding is managed for content direction

components/calendar/skin.css
See https://opensource.adobe.com/spectrum-css/calendar.html#focused
The grey background color for the .is-focused style on today's date is insufficient to communicate that the date has focus. We should use either the blue focus ring as we do for other focused styles, or to continue communicating that the date is today, some sort of double border.
#1051
- **How this was tested:** Verified in documentation example.
- **Browser(s) and OS(s) this was tested with:** Chrome Version 85.0.4183.121 (Official Build) (64-bit) on macOS
=> fix(calendar): .is-today.is-focused should have blue focus ring #1051

components/checkbox/metadata/checkbox.yml, components/radio/metadata/radio.yml, components/radio/skin.css
Correct Checkbox and Radio to have a standard color by default, add emphasized variant.
This work was already done in some form here https://github.com/adobe/spectrum-css/commit/c8db570481f1e30c73854bffd7ecc9371ce2d113, but it seems to have been lost.
=> feat: Checkbox/Radio emphasized variant

components/picker/index.css
Since the new chevron ui icon increased its size to 10x10. It got squeezed in some scenarios.
Fixed #1045 
Before:
After:
=> fix: #1045 chevron icon in picker got squeezed

components/dialog/index.css
fixes https://github.com/adobe/spectrum-css/issues/1039 by adding a border in Windows High Contrast mode
- **How this was tested:** using steps in #1039 1039
- **Browser(s) and OS(s) this was tested with:** Edge 85.0 on Win 10
=> fix: add a border to dialogs in high contrast mode

components/colorarea/skin.css, components/colorhandle/skin.css, components/colorloupe/skin.css, components/colorslider/skin.css, components/colorwheel/skin.css
https://github.com/adobe/spectrum-css/issues/1037
Made the following Changes
* force-color-adjust: none on the handle and the gradient so the colors show even in high contrast mode
* Add disabled color when disabled
* Added colors for the border and fill when disabled
* Ensure there is always a visible border
* Set disabled colors
* Add force-color-adjust so colors show through
=> fix: support high contrast mode in color components

backstop_data/backstop_scenarios.json
After re-generating the VRT baseline images, we still got one scenarios constantly failed. It turns out to be an animation of progresscircle component which should be excluded.
402 passed / 1 failed - https://spectrum-visual-regression.ci.corp.adobe.com/job/spectrum-css-vr-essential-test/17/artifact/light_medium/backstop_data/html_report/index.html
=> test: Exclude animation scenario for progresscircle

components/fieldgroup/index.css
fixes #1050
Apply margin at the _end_ of items for balanced content direction support and so that start alignment can be correct when wrapping.
- **How this was tested:** Follow steps in #1050 in local build.
=> fix(fieldgroup): support content direction sensitive horizontal spacing

components/accordion/index.css
fixes #1033
supersedes #1043 
- simplify calculation of the Accordion heading to rely on %s rather than `--spectrum-accordion-item-height-actual`
- remove use of `--spectrum-accordion-item-height-actual` custom property (which was unmanaged across various scales)
- **How this was tested:** Steps in #1033 and the locally built demo site.
- **Browser(s) and OS(s) this was tested with:**  Chrome on macOS
=> fix(accordion): simplify header sizing, remove unmanaged custom property

backstop_data/backstop_scenarios.json
New animation example from progress bar component broke the VRT.
=> fix: exclude new animation scenario for VRT

components/link/index.css, components/link/skin.css
fixes #1108
- **How this was tested:** scrollyscroll.exe
- **Browser(s) and OS(s) this was tested with:** a computer
=> fix: link shouldn't remap color variables, fixes #1108

tools/bundle-builder/package.json, tools/component-builder/package.json, yarn.lock
Socket.io is giving some security warnings. It's a dependency of Browser-sync which we use in some of the dev/build tools.
- ran `gulp dev` and `gulp build` on my local machine to make sure it still works.
=> Update build tool deps with security problem

components/commons/basebutton.css
ReactSpectrum should override this when/if they start pulling from
SpectrumCSS again.
Fixes #1128 
This was simple enough that I didn't test directly -- I have tested removing this same style in the public doc pages in the debugger though.
=> fix: re-enable touch scrolling for buttons.

components/vars/css/components/spectrum-search.css, components/vars/css/components/spectrum-textarea.css, components/vars/css/components/spectrum-textfield.css
Per #1123 
Currently, Spectrum-CSS uses `var(--spectrum-global-color-gray-600);` for the `::placeholder` text color in Search, Textarea and Textfield components, which results in placholder text that does not comply with WCAG 2.1 AA contrast ratio requirements, and is different than the value specified in Spectrum for `var(--spectrum-alias-placeholder-text-color)`, `gray-800`.
1. Go to https://opensource.adobe.com/spectrum-css/textfield.html
2. Inspect the placeholder text element in the sub-dom for any of the enabled textfield examples.
3. Observe the color specified in CSS is currently `var(--spectrum-global-color-gray-600);`
Placeholder text should use the token defined in Spectrum `var(--spectrum-alias-placeholder-text-color)` which corresponds to …
=> fix(#1123): placeholder text color alias for search, textarea, textfield

site/get-started.pug
Update the example on the [getting started page](https://opensource.adobe.com/spectrum-css/get-started.html) to use the t-shirt sizes for Button.
```html
<button class="spectrum-Button spectrum-Button--cta spectrum-Button--sizeM">
<span class="spectrum-Button-label">Button</span>
</button>
```
=> Update getting started page to include t-shirt sized button

tools/postcss-dropunusedvars/expected/varRefs.css, tools/postcss-dropunusedvars/fixtures/varRefs.css, tools/postcss-dropunusedvars/index.js, tools/postcss-dropunusedvars/test.js
This PR makes `postcss-dropunusedvars` even more aggressive, removing variables if everything that references them has been removed.
- **How this was tested:** tests!
- **Browser(s) and OS(s) this was tested with:** n/a/
=> feat: drop even more unused vars

components/table/skin.css
fixes the double showing of blue on table
Issue Number:  #225 
There was a helper function that was being triggered which rendered the extra blue
This was tested by comparing the expected and actual behavior using Backstop.js
=> fix: table row dropzone shows extra blue, fix #225

README.md, tools/postcss-dropdupedvars/README.md, tools/postcss-dropdupedvars/index.js, tools/postcss-droproot/index.js, tools/postcss-dropunusedvars/README.md, tools/postcss-dropunusedvars/index.js, tools/postcss-transformselectors/README.md, tools/postcss-transformselectors/expected/complex.css, tools/postcss-transformselectors/expected/regex.css, tools/postcss-transformselectors/expected/replace.css, tools/postcss-transformselectors/expected/transform.css, tools/postcss-transformselectors/fixtures/complex.css, tools/postcss-transformselectors/fixtures/regex.css, tools/postcss-transformselectors/fixtures/replace.css, tools/postcss-transformselectors/fixtures/transform.css, tools/postcss-transformselectors/index.js, tools/postcss-transformselectors/package.json, tools/postcss-transformselectors/test.js, tools/postcss-varfallback/README.md, tools/postcss-varfallback/expected/basic.css, tools/postcss-varfallback/expected/functions.css, tools/postcss-varfallback/expected/nested.css, tools/postcss-varfallback/fixtures/basic.css, tools/postcss-varfallback/fixtures/functions.css, tools/postcss-varfallback/fixtures/nested.css, tools/postcss-varfallback/index.js, tools/postcss-varfallback/package.json, tools/postcss-varfallback/test.js, yarn.lock
This PR adds two PostCSS plugins and some documentation on how to use them to optimize Spectrum CSS:
* `postcss-varfallback` - Uses the fallback values of CSS custom properties
* `postcss-transformselectors` - Lets you remap and search/replace CSS selectors
The documentation instructs users on how to use PostCSS to process Spectrum CSS, slimming down their output bundle size.
Additionally, documentation is included showing how to customize Spectrum CSS classnames.
- **How this was tested:** test repo was created internally for the optimization example, tests are included for transform example and other basic functionalities of the plugins
=> feat: add plugins and docs on how to optimize/customize Spectrum CSS

components/checkbox/skin.css
Modified to correctly support spectrum's WHCM defintion
#1117 
- **How this was tested:** Using steps in #1117 
- **Browser(s) and OS(s) this was tested with:** Edge 88.0 on Windows 10
=> fix: refine checkboxes for spectrum's High Contrast mode

components/button/index.css
Using top and bottom padding around `label` in `button` instead of the button itself.
=> fix: adjusted button label padding

components/tabs/index.css, components/tabs/metadata/tabs.yml
This adds t-shirt sizes to the Tabs component as requested in #688.
A size must now be specified by adding a .spectrum-Tabs--size* class to the markup.
=> Add tshirt sizes to tabs dna 7.0 beta

components/tabs/index.css
This fixes #1235, where we noticed that the vertical tab text was not vertically centered.
- Tested locally in the docs site
- Latest version of Firefox on MacOS
=> fix(tabs): vertically center tab item text in vertical tabs

site/resources/js/SpectrumSwitcher.js, site/resources/js/site.js, site/templates/siteComponent.pug
This adds a new switch to the website that allows for users to toggle back and forth between the default and express versions of the CSS vars.
We listen for a click or a key event that corresponds to the "vars version" drop down, get the version of the vars that the user has chosen, and change the resource URL in the `<link>` tags in the DOM. Key events will correspond to `control + e` (for expressvars) and `control + d` (for vars/the default option).
Refs #1238
- Manually tested in a local dev environment.
- Tested on MacOS in the latest versions of Firefox (91.0.2), Chrome (92.0.4515.159), and Safari (14.1.2 (16611.3.10.1.6)).
1. Pull down this branch and run it locally (`gulp dev`)
2. Navigate to any component page (ie: `http://localhost:3000/docs/accordion.html`)
3. Observe that a new …
=> feat: add ability to toggle between default & express vars

package.json, site/templates/siteComponent.pug
This changes the `dev` task by setting a `development` NODE_ENV variable at run time.
The `siteComponent` Pug template has been updated to conditionally display the vars version switch, depending on what value is read from the NODE_ENV.
--
Currently, we'd only like to show the "Vars Version" switch when running the site locally. We can do this by restricting that drop down to only run when a specified environment variable is set. We're not currently asking folks to use `.env` files for environment variable management, so I've gone the route of setting the `NODE_ENV` to `development` when the `yarn start` task is invoked.
Once merged, these changes will close #1263 
- Tested locally by changing the environment variables to see how the Pug conditional renders
=> feat: show vars switch when running in dev environments

components/table/metadata/table.yml
Removes duplicate classes from the Table examples
=> fix: remove duplicate class names in table examples

components/tabs/metadata/tabs.yml
This updates the Tabs component's examples page to add unique IDs for the examples. The Backstop visual regression tests were not accurate because we previously didn't provide unique IDs to each of our examples.
Refs: #1275 
N/A
N/A
=> docs(tabs): resolve flaky visual regression tests

site/util.js
- **How this was tested:** Running docs site locally
- **Browser(s) and OS(s) this was tested with:** MacOS, Chrome
=> docs: ensure tables in docs are sized

components/dialog/index.css, components/tray/index.css
fixes #1306
I couldn't find any information about logical properties in media queries being a "thing" or tools to process them, so I've removed the two instances that I could find.
- **How this was tested:** Tried to run locally, but the build scripts failed. Will review that separately.
- **Browser(s) and OS(s) this was tested with:** See above.
=> fix: remove logical property usage from media queries

components/button/index.css, components/button/skin.css
#1301
Also re-adds the keyboard focus ring for keyboard operation of LogicButton when high contrast mode is not turned on
- **How this was tested:** Windows High Contrast mode on relevant demo pages
- **Browser(s) and OS(s) this was tested with:** Edge 94 on Windows 10
###Before
=> WHCM fixes for button, logicButton, clearButton

components/dialog/metadata/dialog.yml
Fixes #1314, size and positioning verified against [Spectrum website](https://spectrum-contributions.corp.adobe.com/page/standard-dialog-beta/)
=> fix: add missing classes to Dialog's ActionButton, fixes #1314

components/icon/gulpfile.js, package.json, tools/bundle-builder/index.js, tools/bundle-builder/subrunner/index.js
This makes it so `yarn build` will catch undefined variable usage.
=> build: run buildMedium when built fron the top level

components/thumbnail/index.css, components/thumbnail/metadata/thumbnail.yml
Since we dropped support for IE, we can eliminate the hack. This is
not a breaking change because background still has the same properties,
but if image is dropped it, it will fill by default without the
background pseudo element hack.
=> Thumbnail object-fit

components/actionbutton/actionbutton-generated.css, components/actionbutton/index.css, components/actionbutton/metadata/actionbutton.yml, components/actionbutton/skin.css, components/site/index.css
This PR adds static colors for ActionButton with `.spectrum-ActionButton--staticWhite` and  `.spectrum-ActionButton--staticBlack`, closes #1224.
It also fixes the focus-ring for Emphasized Selected ActionButtons, fixes #1177
It also fixes the down state of the emphasized ActionButton, closes #877 
Finally, it fixes the incorrect sizing of the small icon-only ActionButton, closes #1237
=> feat: ActionButton staticColor

components/thumbnail/index.css, components/thumbnail/metadata/thumbnail.yml
This adds an additional class (`.spectrum-Thumbnail-image--cover`) for supporting image "covering" via `object-fit` and `object-position` and restores the previous behavior wherein landscape or portrait images filled horizontally or vertically, but left space between their container edges.
Closes #1134 
=> fix(thumbnail): prefer separate class for image covering

site/resources/js/SpectrumSwitcher.js
JS code assumed the path to `components/` was always at `/`, but it's in a sub-directory on the public site.
Fixes #1351
=> fix: correct match for stylesheets to replace

components/button/skin.css
Button was missing some tokens in the `@adobe/spectrum-tokens` package but they have been added, so the overrides are redundant; I removed them in this pr.
=> Remove button overrides

components/breadcrumb/index.css
ENG: this was probably a typo in the first place - autoprefixer flagged this when using spectrum-css, so fixing it here to get rid of the linter warning
=> fix(breadcrumb): use flex-start for justify content

components/button/index.css
Use the t-shirt sized border-radius variable for the focus-ring's border-radius.
=> fix: correct focus-ring border-radius, fixes #1378

components/inputgroup/metadata/datepicker.yml, components/textfield/metadata/textfield.yml, components/textfield/skin.css, site/resources/js/enhancement.js
In order to support future use cases, this adds and styles a `readonly` state to the textfield component.
It ultimately addresses the request in [CSS-30 (add readonly state to Datepicker)](https://jira.corp.adobe.com/secure/RapidBoard.jspa?rapidView=33123&projectKey=CSS&view=detail&selectedIssue=CSS-30) and adds an example to the Datepicker's documentation to show the proper markup to achieve a `readonly` Datepicker.
Additionally, this fixes two browser console errors where we were attempting to manipulate classes for elements that did not always exist.
URL for validation:
https://git.corp.adobe.com/pages/pfulton/spectrum-css-ccx-verify/docs/textfield.html
=> feat(textfield): add read-only state

components/checkbox/metadata/checkbox.yml, components/checkbox/skin.css, components/fieldgroup/index.css, components/fieldgroup/metadata/fieldgroup.yml
This adds a `readonly` option to a group of checkboxes by way of the Field Group component.
1. Provide a faux `readonly` state to the checkbox component by adopting the immutability of a `disabled` checkbox and the styles of a default checkbox. Read-only checkboxes should not be able to be changed, but their labels can be highlighted/copied/pasted.
2. Update Field Group to show a collection of `checked`, read-only checkboxes. As per design, the _actual_ checkbox UI element should be hidden, and the labels for the items should be displayed in a horizontal list, separated by a comma (in U.S. English).
For the separator character, I've provided a custom property that defaults to the unicode character for a comma. Downstream implementations will be able to modify that custom property if …
=> feat(checkbox, fieldgroup): add `readonly` state

README.md
This adds documentation for how we handle prerelease versions of our components.
=> docs: add prerelease information

components/menu/index.css, components/menu/metadata/menu.yml, components/menu/package.json, components/menu/skin.css
Menu isn't currently using the divider component; this fixes it.
=> Use divider component in menu

components/modal/index.css
This PR fixes issue [#1283 Modal: replace fill-available with stretch](https://github.com/adobe/spectrum-css/issues/1283). The `.spectrum-Modal-wrapper` class currently uses `height: fill-available;` [as shown here](https://github.com/adobe/spectrum-css/blob/7bd84e70209361c9b7bb787bf4263420c76d84c1/components/modal/index.css#L44). This is a webkit-specific value. The correct value is `stretch`.
The PR was tested locally by updating L46 in `/node_modules/@spectrum-css/modal/dist/index-vars.css` from `height: fill-available;` to `height: stretch;` and rebuilding the `aio-theme`.
After this change, the warning was no longer triggered in the console.
Warning from aio-theme dev build:
Warning no longer triggered after fix:
=> bug: replace fill-available with stretch

netlify.toml
This adds a `netlify.toml` file so that we can properly configure the redirects for deploy previews, and so that the site is actually viewable during any preview deploy.
Validation:
* Click on the "Deploy preview" link in the Netlify bot comment below. Your URL should be redirected to `/docs/index.html` automatically. Observe that the site renders correctly with no missing assets.
=> feat: add netlify config

README.md, site/includes/dependencies.pug, site/resources/js/SpectrumSwitcher.js, site/templates/individualComponent.pug, site/templates/siteComponent.pug
This doesn't really remove the `lightest` option from the `vars` package, it just removes it from the Spectrum CSS website switcher.
=> Remove lightest option from website switcher

components/actionbutton/index.css
Updates the ActionButton so that the icon + text variation matches the component prior to core tokens implementation.
=> fix(actionbutton): adjust icon margin to match spec

components/actionbutton/index.css, components/actionbutton/package.json, components/closebutton/index.css, components/picker/index.css
This removes the `!important` declarations that were placed upon `box-shadow`s to forcefully remove focus rings. Using `!important` was causing problems for folks who were trying to customize the focus rings, especially in a Windows High Contrast Mode context.
[CSS-154](https://jira.corp.adobe.com/browse/CSS-154)
=> fix(actionbutton, closebutton, picker): remove `!important` declarations

.github/PULL_REQUEST_TEMPLATE.md
Add a Checkbox to the PR template to prompt folks to check in High Contrast mode.
=> chore: add high contrast checkbox in PR template

components/swatch/index.css
Adds WHCM for swatch
#1467
Run Swatch and swatchgroup pages with WHCM enabled
=> fix: swatch high contrast support

package.json, yarn.lock
Updates the VRT references, which include the [`xs` size for ActionButton](1f18708d106ffa914b40db9ac3f4fa2cac3c3f7a) and the [core tokens version of HelpText](1d5a416e5bceb73e11aba9a471b39e0d5e13cf55)
=> test: update VRT references

package.json, yarn.lock
Increases the version number for our VRT reference images package
=> chore: consume latest VRT reference images

components/tokens/custom-spectrum/custom-large-vars.css, components/tokens/custom-spectrum/custom-medium-vars.css
This removes the custom medium and large radio tokens, as they are now implemented in `@adobe/spectrum-tokens`.
=> refactor(tokens): remove custom med, lg radio tokens

components/actionbutton/package.json, components/closebutton/package.json, components/helptext/package.json, components/radio/package.json
This pins the `@spectrum-css/tokens` package version at `1.0.7` for ActionButton, CloseButton, Helptext, and Radio
=> refactor: pin tokens dependency in four packages

components/tokens/package.json
This pins `@adobe/spectrum-tokens` to a specific release to mitigate the effects of a breaking change in a later patch version
=> refactor(tokens): pin dependency to specific version

components/helptext/index.css, components/radio/index.css, components/tokens/package.json, yarn.lock
BREAKING CHANGE: consumes the latest core tokens release, which is breaking due to the letter case change for `CJK-` tokens.
FIX: updates HelpText and Radio to use the lower case token names
=> fix(tokens, radio, helptext)!: use latest tokens release & fix missing tokens errors

components/buttongroup/gulpfile.js, components/buttongroup/index.css, components/buttongroup/metadata/buttongroup.yml, components/buttongroup/package.json, components/buttongroup/themes/express.css, components/buttongroup/themes/spectrum.css, yarn.lock
Migrate Button Group to use core tokens.
- Chrome
- Safari
- WHCM emulation
=> refactor(buttongroup)!: migrate to core tokens

components/card/index.css
The height of the content area of the Card (within `spectrum-Card-content`) won't grow when the actual content becomes tall. To fix it, I have changed the property name `block-size` to `min-block-size` under `.spectrum-Card-content`.
See #1521.
- **How this was tested:** Using steps in issue #1521
- **Browser(s) and OS(s) this was tested with:** Chrome 105.0.5195.125 on macOS 12.6
Before:
After:
=> fix(card): increase content area height when necessary

components/checkbox/index.css
I accidentally left this chunk of commented-out code in the CSS. This PR removes it.
=> refactor(checkbox): remove commented out code

components/tabs/index.css, components/tabs/skin.css
Resolves an issue with the selection indicator border when there is scrollable overflow.
Updated with the recommended solution using the background linear gradient rather than background-color.
Set `.spectrum-Tabs` width to less than the widths of its `.spectrum-Tab-item` children combined e.g. `200px`. Set `.spectrum-Tabs` to `overflow: auto`.  See examples of the bug and fix below.
https://user-images.githubusercontent.com/16216104/194005007-e61b01ee-3f0d-4563-b2c4-a127217171a0.mp4
https://user-images.githubusercontent.com/16216104/194003987-77d9c0f5-9aad-49f2-b57a-229ef2226e51.mp4
=> fix(tabs): selection indicator scroll overflow border

components/swatch/gulpfile.js, components/swatch/index.css, components/swatch/metadata/swatch.yml, components/swatch/package.json, components/swatch/themes/express.css, components/swatch/themes/spectrum.css, yarn.lock
- Update windows high contrast mode
- Update YAML examples
- Rename `--spectrum-picked-color` to `--mod-swatch-fill-background-color`
- Add `is-image` class to Image, Gradient, and Mixed Value swatches for transparent backgrounds 
Note: There are currently [two open questions](https://adobedesign.slack.com/archives/G019JTYMT6H/p1660685017664239) about border colors and the XS workflow icon size in Slack, however, these may not be blockers for this work.
- Tested locally referencing the Swatch XD file.
- Tested WHCM with forced colors in Chrome Emulation
- Medium and Large scales
=> feat(swatch)!: migrate swatch to core tokens

components/checkbox/index.css, yarn.lock
Fixes an issue where the `focus ring` thickness was too thick on Windows High Contrast Mode. Additionally, this fixes an issue where the `invalid` `focus` state was incorrect in Windows High Contrast Mode.
Finally, to be sure that the cascade is properly working, this moves the WHCM styles to the bottom of the `index.css` file.
**BEFORE**
**AFTER**
=> fix(checkbox): adjust WHCM focus ring

site/get-started.pug, site/index.pug
docs: update content on main page and get-started to match content strategy recommendations
From content strategy:
> Please edit the following two strings on the Spectrum CSS homepage:
> 1) Change the headline of "Meet Spectrum CSS" to just:
> **Spectrum CSS**
> (This is so the site can be more evergreen; it's in line with the content strategy we're going to have for all Spectrum implementations)
> 2) In the "Flexible" content block, please make the link sentence case, to follow content standards:
> **Get started**
> (not: Get Started)
=> Minor content update to main and get-started pages.

components/actionbar/gulpfile.js, components/actionbar/index.css, components/actionbar/metadata/actionbar.yml, components/actionbar/package.json, components/actionbar/themes/express.css, components/actionbar/themes/spectrum.css
BREAKING CHANGE: This migrates the ActionBar component to core tokens.
- Jira issue CSS-121 https://jira.corp.adobe.com/browse/CSS-121
- Chrome 103 for macOS
- Firefox 102 for macOS
- Safari 15.5 for macOS
- **How this was tested:** comparing local build of http://localhost:3000/docs/actionbar.html with XD redline components batch 2 and with https://spectrum.adobe.com/page/actionbar
Standard:
Emphasized:
Flexible width:
Sticky:
=> refactor(actionbar)!: migrate to core tokens

components/inlinealert/metadata/inlinealert.yml, components/textfield/metadata/textarea.yml, components/textfield/metadata/textfield.yml, components/toast/metadata/toast.yml, components/tooltip/metadata/tooltip.yml
Minor docs update to get around us not featuring the icon-changes for Express
https://jira.corp.adobe.com/browse/CSS-241 Update a few components to use correct Express Alert Icon
Add this note.
=> feat: docs updates for Express icons (CSS-241)

tools/component-builder/package.json
It wasn't possible to install this outside of the monorepo before this change.
This was discovered when trying to update @spectrum-css/component-builder in React Spectrum (install failed).
=> fix: add missing dependency for component-builder

components/progresscircle/index.css
Minor color token change for Progress Circle. 
https://jira.corp.adobe.com/browse/CSS-246 Progress Circle - Update token
simple rename:
looks the same in system Express and Spectrum:
- **How this was tested:**go to http://localhost:3000/docs/progresscircle.html
- **Browser(s) and OS(s) this was tested with:** Version 110.0.5423.0 (Official Build) canary (x86_64)
Express:
Spectrum:
=> feat: minor color token change for accent color (CSS-246)

components/inputgroup/index.css
rtl support uses end instead of right.
https://jira.corp.adobe.com/browse/CSS-168 
https://jira.corp.adobe.com/browse/CSS-168  InputGroup-input uses padding-right which doesn't work correctly on RTL
Class `spectrum-InputGroup-input` impacts Combobox & Datepicker http://localhost:3000/docs/combobox.html
- **How this was tested:**  http://localhost:3000/docs/combobox.html looks the same
- **Browser(s) and OS(s) this was tested with:** Version 110.0.5454.1 (Official Build) canary-dcheck (arm64)
Testing RTL looks like this is fixed:
https://pr-1560--spectrum-css.netlify.app/docs/combobox.html
=> feat: using inline-end for rtl support (CSS-168)

components/tooltip/index.css
This updates Tooltip to have identical inline padding for start and end when no icon is present. Previously, start padding was equal to the margin from the icon to the label.
- Jira issue CSS-350 https://jira.corp.adobe.com/browse/CSS-350
**Revised XD redline:**
**Illustration of difference:**
Pixel numbers in the above illustration represent medium/large.
- Chrome 108 for macOS
- Firefox 107 for macOS
- Safari 16 for macOS
- **How this was tested:** comparing local build of http://localhost:3000/docs/tooltip.html with revised XD redline component.
=> fix(tooltip): update inline padding

components/link/index.css
This corrects link colors in Windows High Contrast mode.
- Jira issue CSS-333 https://jira.corp.adobe.com/browse/CSS-333
- Using Chrome emulation of WHCM + dark mode. You can replicate this test by opening the rendering drawer in Chrome dev tools (Command + P, search "rendering", open the rendering drawer) and activating prefers-color-scheme: dark and forced-colors: active.
-  Chrome 108 for macOS
**Primary keyboard focus:**
=> fix(link): correct highcontrast custom properties

components/fieldlabel/index.css
This adds the missing text color token to field label.
- Jira issue CSS-347 https://jira.corp.adobe.com/browse/CSS-347
- Chrome 108 for macOS
- Firefox 107 for macOS
- Safari 16 for macOS
- **How this was tested:** comparing local build of http://localhost:3000/docs/fieldlabel.html with XD redline components Batch 1
**Prior to this change, field label color was inherited from the body, seen here overridden in the browser with red:**
**Adding the missing color token allows field label to self-manage its color:**
=> fix(fieldlabel): add missing color token

components/actionbar/index.css
This removes unnecessary selectors from Actionbar.
- Jira issue CSS-360 https://jira.corp.adobe.com/browse/CSS-360
- Chrome 108 for macOS
- Firefox 107 for macOS
- Safari 16 for macOS
- **How this was tested:** viewing local build of http://localhost:3000/docs/actionbar.html.
=> fix(actionbar): remove selectors

components/tokens/custom-spectrum/custom-vars.css
Adds a set of custom properties for animation. These are copied over from the legacy `vars` package.
*Reason for adding:*
These are added as a response to [this PR comment](https://github.com/adobe/spectrum-web-components/pull/2585#pullrequestreview-1180051361), but we've also been discussing adding global animation vars for several months. The time to add these is now!
=> feat(tokens): adds global animation vars

README.md, tools/generator/templates/stories/template.js.hbs, tools/generator/templates/stories/{{ folderName }}.stories.js.hbs, tools/preview/assets/index.css, tools/preview/decorators/index.js, tools/preview/global.js, tools/preview/main.js, tools/preview/manager.js, tools/preview/preview-head.html, tools/preview/preview.js
While populating stories, a few optimizations were identified for the storybook tooling & for the files being generated.  This PR updates:
- Add a readonly `rootClass` property to store the class name of the component.
- Add a `customClasses` and `content` property to the story to facilitate nesting components dynamically.
- Template syntax to read the `rootClass` property defined in the storybook file.
- Template syntax to use the example mark-up instead of adding it as commented out code.
- Reduced motion properties were not being loaded; this fixes them so they load and have the appropriate specificity.
- Parameters were not being passed correctly in the decorator.
- A shared typography loading .js file for use for the UI and the nested story.
- Minor listing updates.
- **How this was …
=> chore: update storybook tooling & generator files

tools/generator/templates/stories/template.js.hbs
During demo we uncovered a syntax error in one of the handlebars templates for the generator. This PR resolves that syntax issue.
=> chore: fix handlebars template error

components/dialog/index.css
This mitigates the clipping of focus indicators of components within Dialog Fullscreen's content area. 
- Jira issue CSS-79 https://jira.corp.adobe.com/browse/CSS-79
- Chrome 109 for macOS
- Firefox 109 for macOS
- Safari 16.2 for macOS
- **How this was tested:** Temporarily added Close Button and Button components to the top of the content area (spectrum-Dialog-content) of the fullscreen dialog in the YML for dialog on local build http://localhost:3000/docs/dialog.html. Viewed the error and the correction on the local build. 
The error is present in the following screenshot. A pink "16px" bar has been added to show spacing. 16px is the correct spacing for the margin below the HR (horizontal rule) on medium screens, medium HR. We need to maintain this spacing while preventing the focus …
=> fix(dialog): adjust padding and margins to avoid focus indicator clip

package.json
While trying to run a release on a single package change, the command failed.
`npx lerna changed` shows that a package is ready for publication, but it looks like the filtering may have been too aggressive while building the scope.
=> build: fix broken lerna scope

components/fieldlabel/index.css
Fixes an issue where we were using hard-coded (previously undefined) incorrect values for the spacing between field labels and their asterisks
**Before:**
**After:**
=> fix(fieldlabel): use proper tokens & resolve incorrect gap size

components/progressbar/index.css, components/progressbar/package.json
Uses global animation vars from `@spectrum-css/tokens` instead of defining its own vars. As described in [this PR comment](https://github.com/adobe/spectrum-web-components/pull/2585#pullrequestreview-1180051361), this has a number of benefits to what we're shipping, but it allows for consumers to more easily alter motion settings (where reduced motion is preferred).
=> refactor(progressbar): prefer global animation vars to component-defined

components/progressbar/index.css
Small typo in the name of the mod variable for inline alert:
`--mode-progressbar-label-and-value-white` corrected to -> `--mod-progressbar-label-and-value-white`
- Empty var but should communicate this out in the next release.
=> fix(progressbar): typo in --mod-progressbar-label-and-value-white variable

components/sidenav/index.css, tools/component-builder-simple/css/plugins/postcss-transform-logical.js, tools/component-builder/css/plugins/postcss-transform-logical.js
Y'all should probably share the code for `postcss-transform-logical` between the two builders, but this quickfix addresses the ActionButton and SideNav issues I saw when I was trying to create a brown bag preso telling folks to use logical directions
- **How this was tested:** Switch to RTL, look at the hold icon on ActionButton, look at text alignment for SideNav
- **Browser(s) and OS(s) this was tested with:** Chronumenium
Before
After
=> fix: correct RTL issues with SideNav and ActionButton

components/inlinealert/themes/spectrum.css
Found that the inline alert customizations for the spectrum theme were using `.spectrum-InlineAlert` instead of `.spectrum-InLineAlert`.
=> fix(inlinealert): correct spectrum theme capitalization

components/tokens/package.json, yarn.lock
Uses the "full" v12 release of `@adobe/spectrum-tokens`.
=> feat(tokens): use full v12 release

components/actionbutton/metadata/actionbutton.yml
=> fix(actionbutton): fix variable used in documentation

components/tokens/custom-spectrum/custom-large-vars.css, components/tokens/custom-spectrum/custom-medium-vars.css
Adds a few new custom platform scale tokens for ColorWheel and Color Handle.
=> feat(tokens): adds colorwheel and colorhandle custom tokens

components/picker/index.css, components/picker/package.json, components/picker/themes/express.css, components/picker/themes/spectrum.css, site/templates/siteComponent.pug
This addresses several issues with the Picker:
* Uses `font-style: normal` instead of `italic` for the placeholder
* Fixes an issue where the `focus-ring` wasn't aligned properly in Express
* Updates the values for a custom property which were causing both Spectrum and Express to have a `border-width` when Express _should not_ have a border.
* Updates the docs site to add classes to the "switcher" implementations of the Picker so that they'll display properly.
=> fix(picker): resolve font-style, focus-ring, border issues

components/fieldlabel/stories/fieldlabel.stories.js, components/fieldlabel/stories/template.js
This adds a storybook instance for the Field Label component.
[Jira CSS-405](https://jira.corp.adobe.com/browse/CSS-405)
**Note: This does have a width style attribute hard coded and this is in order to demonstrate the alignment options, like how they do on [the docs site](https://opensource.adobe.com/spectrum-css/fieldlabel.html#left)**
=> feat: field label storybook

components/tokens/custom-express/custom-large-vars.css, components/tokens/custom-express/custom-medium-vars.css
Adds ColorWheel clip path custom tokens for express. The border property applied to the ColorWheel increase from 1px to 2px when viewed in express. The clip paths also need to adjust accordingly. 
=> feat(tokens): adds colorwheel custom express tokens

components/tabs/stories/tabs.stories.js, components/tabs/stories/template.js
This PR adds the Tabs storybook instance. 
The only additional options on the documentation site that I did not add were "[Basic Tabs with Overflow](https://opensource.adobe.com/spectrum-css/tabs.html#basictabswithoverflow)". This was really going to muddy up the template in my opinion and it just implemented two additional components that already have their own stories (Picker and Popover). There wasn't anything specific for tabs being passed into the components that I could see. Because of this, I felt that it wasn't needed. I'm happy to add it if others have different opinions.
=> chore: tabs storybook

components/tokens/custom-spectrum/custom-large-vars.css, components/tokens/custom-spectrum/custom-medium-vars.css
Adds a new token for `--spectrum-rating-icon-spacing` at both medium and large scales.
=> feat(tokens): add medium, large tokens for rating-icon-spacing

components/steplist/stories/steplist.stories.js, components/steplist/stories/template.js
Adds completed Steplist story to Storybook, matching the options and markup on the documentation site for this component. Includes Storybook controls for small, interactive, and tooltip variants.
=> chore(steplist): storybook setup

gulpfile.js, package.json, tasks/checkPeerDependencies.js
Pulls out the peer dependency check into its own command to be run by CI in future. Validates that peer dependencies and dependencies are not mismatched.
- **How this was tested:** `yarn check:peerDeps` (I went in and edited a file to be incorrect to test that it would catch broken cases as well).
=> chore: migrate check peer dependencies script to node

.gitignore, netlify.toml
Looking at the netlify documentation for 11ty integration, it suggests updating the .gitignore to use `**/node_modules/**` rather than `node_modules`.
I also updated the netlify config to include:
- Build commands so that if they change locally, we can update them via the repo
- An alias from storybook to preview b/c storybook is a common url pattern
- From a component name as a folder to the component html asset
- Post-processing support for non-deploy preview builds (minification & bundling)
=> chore: update netlify settings

components/actionbutton/index.css, components/actionbutton/metadata/mods.md, components/button/index.css, components/button/metadata/mods.md
The use of the `+` combinator to style icon/label layout in the Button requires SWC to leverage content observers in order to mimic the relationship across the slots leveraged to accept these two pieces of content. More heavily leveraging `display: inline-flex` and some alternate padding/margin applications should allow the same layout without requiring the use of a combinator.
**_Works best for SWC when the same can be done for Action Button (which used the `+` AND `:only-child`), will investigate further._**
TK baring preview site build
=> refactor(button): combinator free layout rules

components/inputgroup/CHANGELOG.md, components/inputgroup/package.json, components/pickerbutton/CHANGELOG.md, components/pickerbutton/index.css, components/pickerbutton/package.json, components/stepper/CHANGELOG.md, components/stepper/gulpfile.js, components/stepper/index.css, components/stepper/metadata/stepper.yml, components/stepper/package.json, components/stepper/stories/stepper.stories.js, components/stepper/stories/template.js, components/stepper/themes/express.css, components/stepper/themes/spectrum.css, components/textfield/CHANGELOG.md, components/textfield/index.css, components/textfield/metadata/textarea.yml, components/textfield/metadata/textfield.yml, components/textfield/package.json, components/textfield/stories/template.js, components/textfield/stories/textfield.stories.js, components/textfield/themes/express.css, components/textfield/themes/spectrum.css, yarn.lock
BREAKING CHANGE: This migrates the Text field and text area component to core tokens. This also relates the focus indicator border radius for customization.
- Jira issue CSS-153 https://jira.corp.adobe.com/browse/CSS-153
- Jira issue CSS-185 https://jira.corp.adobe.com/browse/CSS-185
- Jira issue CSS-161 https://jira.corp.adobe.com/browse/CSS-161
- Jira issue CSS-388 https://jira.corp.adobe.com/browse/CSS-388
**EDIT:** This PR now includes partial migration of Stepper. It was necessary to migrate Stepper with Textfield in order to overcome VRT failures in Spectrum Web Components. Migration work aims to maintain existing styles of Stepper, making only the updates which Design approves of at this time. Design provided background and border colors as well as new styling for Express. Express …
=> refactor(textfield): migrate spectrum tokens

components/colorwheel/index.css
As a follow up to, #1619 this PR moves the custom properties `--trackWidth` and `--border-width` to `.spectrum-ColorWheel` to make accessing them more straight forward for SWC. 
[See slack convo. ](https://adobedesign.slack.com/archives/CS22GNRU2/p1679587915417799)
Ran branch locally, ensured changes did not visually change anything 
No visual change
=> fix(colorwheel): move custom properties

components/colorslider/index.css, components/colorslider/skin.css, components/swatch/index.css
BREAKING CHANGE: This migrates the using opacity checkerboard core tokens. 
Uses new tokens for opacity checkerboard with in ColorSlider and Swatch 
- also refactors checkerboard to use `repeating-conic-gradient` 
- [caniuse for repeating-conic-gradient]( https://caniuse.com/?search=repeating-conic-gradient) 
Does not include ColorHandle, ColorLoupe, or Thumbnail. Each of which will be addressed when component is migrated. 
comparing local build with[ figma](https://www.figma.com/file/nchxla8gD4CxWYwt9eiRrz/Token-definition-library?node-id=202-4135&t=evkhgWs0xvGXQfL8-0) for Opacity Checkerboard
Browser(s) and OS(s) this was tested with:
Chrome 109 on macOS
Safari 16.2 on macOS
Firefox 109 on macOS
=> feat(colorslider)!: Use new tokens for opacity checkerboard

.github/dependabot.yml
Dependabot ignore was expecting an object and not an array. https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#ignore
=> chore: fix dependabot ignore error

components/button/index.css, components/button/metadata/button-accent.yml, components/button/metadata/button-negative.yml, components/button/metadata/button-primary.yml, components/button/metadata/button-secondary.yml, components/button/metadata/button-staticcolor.yml, components/button/metadata/mods.md, components/button/stories/button.stories.js, components/button/stories/template.js
This adds styling for an icon-only variation of Button that results in a circular button and updates the docs to include it.
This PR also removes an unneeded control from Storybook `justified` and fleshes out the stories more to help make VRTs more robust.
- Safari Version 16.4
- Chrome Version 111.0.5563.146
=> fix(button): add icon only variant

package.json, tools/preview/package.json
Fix the storybook compilation task to pre-build assets
=> fix(preview): storybook precompilation task

tools/documentation/_data/component.js, tools/documentation/_includes/meta-info.njk, tools/documentation/_layouts/pages.njk
Added a loop on metadata/*.js and read all the js files and stored it in a variables which is parsed out in pages.njk
After running 
``` yarn dev:docs ```
The following script tags are embedded in Accordion component's index.html
=> Ensure that all metadata/*.js assets are being loaded on the site into a bundle

tools/documentation/_includes/example.njk, tools/documentation/_includes/link-cards.njk, tools/documentation/_includes/sidenav.njk, tools/documentation/_layouts/pages.njk, tools/documentation/assets/js/Search.js, tools/documentation/assets/js/docs.js, tools/documentation/content/components.njk, tools/documentation/content/index.njk
loadIcons path fixed: loadIcons('../../components/icon/spectrum-css-icons.svg');
html in example.njk, components.njk & sidenav.njk are fixed.
resources in GitHub and npm svg rendering issue fixes
Chrome
=> chore: Validate pathing to the component pages looks right and is loading from navigation with a single click

components/picker/themes/spectrum.css
This PR updates the border color tokens for Picker based on updated designs for Spectrum to meet accessibility guidelines. There were no changes to Express styling.
=> fix(picker): update border colors

components/tokens/custom-spectrum/custom-large-vars.css, components/tokens/custom-spectrum/custom-medium-vars.css
This adds custom tokens for `--spectrum-button-top-to-text-{size}` and `--spectrum-button-bottom-to-text-{size}` to adjust for the new 1.2 line-height that we will be using to keep the heights as round numbers for buttons. Values were added for both medium and large.
=> chore(tokens): add custom tokens for button text spacing

components/stepper/index.css, components/stepper/stories/template.js, components/textfield/index.css
This PR makes two updates to help with accessibility for the Textfield and Stepper components based on feedback from the SWC team:
- Updates the WHCM color for the focus ring for Textfield in both the default and quiet variants to be `HIghlight`
- Updates the Stepper button width to match the current wider implementation to allow for a larger target size
Previous WHCM Focus
Updated WHCM Focus
=> fix(textfield, stepper) : textfield and stepper accessibility fixes

components/colorarea/package.json, components/colorhandle/package.json, components/colorloupe/package.json, components/colorwheel/package.json
Lerna didn't handle the graduation for some of the Color-* components. This is a PR to bring several `package.json` files up-to-date with the full releases.
=> chore: update color-* component dependencies

site/templates/siteComponent.pug
Fixes an issue where the "details table" section of each component wasn't properly switching text color along with theme changes.
before:
after:
=> fix: resolve always black text in docs site

site/includes/nav.pug, tools/bundle-builder/dev/index.js, tools/bundle-builder/index.js
- Remove clean task from bundle-builder (duplicated by npm scripts)
- This command was cleaning out resources that had already been migrated
- Update storybook link to remove absolute pathing & only show the link in non-dev environments
- Update browser sync to remove the docs folder from the startPath
=> chore: remove duplicate clean tasks from site build

components/icon/stories/template.js
Fix issue where use of Icon in other stories would not change its sizing (scale) based on the value of the size arg. The conditional with uiIcons.includes was comparing against the icon name which still contained the sizing number, so was always failing.
Also adds some docs around this.
Chrome, Mac. Testing 'Table' in storybook with t-shirt sizes ("small" should now show smaller icon). Tested some of the other components in Storybook that are using Icon to make sure they still look the same: checkbox, closebutton, textfield
=> fix(icon): correct storybook icon sizing substitution

components/combobox/index.css, components/combobox/metadata/mods.md, components/textfield/index.css, components/textfield/stories/textfield.stories.js
Some fixes for Textfield and Combobox:
- **Textfield** and **Combobox**: Subtract border width from padding calculations because most of the "...to-edge" tokens include the border. The values were previously 1px larger than they should have been.
- **Textfield** and **Combobox**: fix corner radius of focus indicator when using a larger border radius or a larger indicator width (e.g. to test, try setting a  larger `--mod-textfield-border-width` or `--mod-textfield-focus-indicator-width`. Changed the calculation  to add the focus indicator width instead of the border width)
- **Combobox**: adjust styles so custom property for border width is correctly overriding everything from its sub-components. Previously, using `--mod-combobox-border-width` had no effect.
- **Combobox**: simplify/remove …
=> fix: textfield and combobox fixes, adjust padding calculations 

components/tokens/custom-express/custom-dark-vars.css, components/tokens/custom-express/custom-darkest-vars.css, components/tokens/custom-express/custom-light-vars.css, components/tokens/custom-spectrum/custom-dark-vars.css, components/tokens/custom-spectrum/custom-darkest-vars.css, components/tokens/custom-spectrum/custom-light-vars.css
This adds custom tokens for `--spectrum-drop-zone-background-color-rgb` since the current token for `--spectrum-drop-zone-background-color` references another token and therefore doesn't have an RGB token. We need it for Drop Zone because there is an opacity applied to this background color.
=> feat(tokens): add custom drop zone rgb background color tokens

components/contextualhelp/index.css, components/contextualhelp/metadata/contextualhelp.yml, components/contextualhelp/metadata/mods.md, components/contextualhelp/stories/template.js
Adds `.spectrum-Heading` and `.spectrum-Body` classes to the heading and paragraph tags in order to get the global font colors needed since font color was not a specified token for this component. 
- Latest versions of Chrome, Safari, Firefox
=> fix(contextualhelp): dark mode font color

components/actionbar/metadata/actionbar.yml, components/actionbar/stories/template.js
Adds `aria-label="Clear selection"` to the Close Buttons found within the Action Bar component.
[CSS-464](https://jira.corp.adobe.com/browse/CSS-464)
=> docs: add aria-label for actionbar close button (CSS-464)

components/tokens/package.json, yarn.lock
Updates to the `12.7.0` [release](https://github.com/adobe/spectrum-tokens/releases/tag/%40adobe%2Fspectrum-tokens%4012.7.0) of @adobe/spectrum-tokens.
=> feat(tokens): use spectrum-tokens at 12.7.0

components/floatingactionbutton/README.md, components/floatingactionbutton/gulpfile.js, components/floatingactionbutton/index.css, components/floatingactionbutton/metadata/floatingactionbutton.yml, components/floatingactionbutton/metadata/mods.md, components/floatingactionbutton/package.json, components/floatingactionbutton/stories/floatingactionbutton.stories.js, components/floatingactionbutton/stories/template.js, components/floatingactionbutton/themes/express.css, components/floatingactionbutton/themes/spectrum.css, components/textfield/metadata/mods.md, yarn.lock
This adds a new FloatingActionButton component with two variants: primary and secondary.
This currently contains "hard coded" values for the `--spectrum-floating-action-button-drop-shadow-y` and `--spectrum-floating-action-button-drop-shadow-color` because we are waiting for these tokens to get added per this ticket
- Latest versions of Chrome, Firefox, and Safari
=> feat(floatingactionbutton): add new component

components/stepper/index.css
Removes a misspelled `align-items` property, which was not being evaluated by browsers. The component displays properly without this property, so we're removing it.
=> fix(stepper): remove misspelled flex property

package.json
Resolves an issue where trying to release a build of the docs site threw an error due to a script trying to move files to a non-existent destination.
=> fix: resolve missing preview destination

components/tokens/package.json, yarn.lock
Updates to `@adobe/spectrum-tokens@12.8.0`, which contains 2 token value updates for color handle to remove express specific values. Full details in the [release notes](https://github.com/adobe/spectrum-tokens/releases/tag/%40adobe/spectrum-tokens%4012.8.0).
=> feat(tokens): use v12.8.0 of @adobe/spectrum-tokens

components/stepper/index.css, components/stepper/metadata/mods.md, components/stepper/themes/express.css, components/stepper/themes/spectrum.css, components/textfield/stories/template.js
This PR fixes the appearance of the Stepper buttons. They were slightly off center due to how the padding and borders were being applied. This PR updates the styling to more closely resemble what is currently shown in SWC and what was there previously. 
**NOTE:** The Stepper component is not yet migrated, so these changes are just a band-aid for now. The component was slightly migrated to allow for Textfield to get through.
=> fix(stepper): fix stepper button padding and borders

components/colorhandle/index.css, components/colorloupe/index.css, components/tokens/custom-express/custom-large-vars.css, components/tokens/custom-express/custom-medium-vars.css, components/tokens/custom-spectrum/custom-large-vars.css, components/tokens/custom-spectrum/custom-medium-vars.css
Follow up to [migration](https://github.com/adobe/spectrum-css/pull/1753) for ColorHandle 
The following tokens were updated after the migration to account for spectrum vs express styling changes: 
- color-loupe-bottom-to-color-handle
- color-loupe-height
- color-loupe-inner-border-width
- color-loupe-width
- color-handle-inner-border-opacity
- color-handle-outer-border-opacity
- color-handle-size
- color-handle-size-key-focus
This PR removes hard coded values, custom tokens, and related comments to use the newly updated tokens. 
To test view the ColorHandle and ColorLoupe component as spectrum and express, there should be no styling difference between the 2 themes. 
=> chore(colorhandle, colorloupe): remove custom tokens 

tools/component-builder-simple/css/index.js, tools/preview/package.json, yarn.lock
We will need to lock down the version of @etchteam/storybook-add-on-status as a breaking change was released under a patch. I've opened an [issue](https://github.com/etchteam/storybook-addon-status/issues/48).
Additionally, this PR converts the unused variables to a warning rather than a blocking error.
=> chore: lock @etchteam/storybook-addon-status version

components/floatingactionbutton/package.json, yarn.lock
A fresh install was breaking the build due to the token dependency for Floating Action Button not being high enough. This bumps the dev dependency up to the latest version and increases the peer dependency to 9, as that is needed for all of the tokens to be included.
=> fix(floatingactionbutton): update token dependency

components/actiongroup/index.css, components/colorhandle/index.css, components/colorloupe/index.css, components/colorwheel/index.css, components/datepicker/index.css, components/swatch/index.css, tools/bundle-builder/package.json, tools/component-builder-simple/css/index.js, tools/component-builder-simple/css/processors.js, tools/component-builder-simple/package.json, tools/component-builder/css/vars.js, tools/component-builder/package.json, tools/generator/package.json, tools/postcss-dropdupedvars/index.js, tools/postcss-dropunusedvars/index.js, tools/preview/postcss.config.js, yarn.lock
After discussion, the team has opted to allow custom property passthroughs in css files; this allows design direction to be handed to nested components in a way that is easier for web components to consume and makes better use of the cascadability of custom properties.
To this end, this PR updates build scripts to change the errors to informational so we can continue to ensure no unexpected variables are unused and the PostCSS steps are updated to prevent them from removing unused variables from compiled output. I've also removed the hacks from the css files as they are no longer necessary.
I want to note, some of the warnings that show up in the logs are false because this is running on the css files before resolving any imports. If variables are defined in the imports, this script does …
=> fix: allow custom property passthroughs

components/fieldlabel/index.css, components/fieldlabel/metadata/fieldlabel.yml
Very small PR to add `--highcontrast-disabled-content-color` to the FieldLabel component. This is needed for Slider component and is something that Westbrook caught in that PR over in SWC.
I also went ahead and removed placeholders from the docs examples while I was in there, since those are being deprecated from the Textfield component.
=> style(fieldlabel): add highcontrast color

tools/component-builder-simple/css/index.js
In researching the change to output of the themes folder in the component dist, discovered that the processor functions were using the old input values where the first function input was keepVars. This was removed in PR #1874 to allow passthrough customizations.
=> fix(component-builder-simple): correct processor function inputs

components/checkbox/index.css, components/checkbox/metadata/mods.md
**Checkbox**
- Rename misspelled custom property mod `--mod-checkox-height` to `--mod-checkbox-height`
- Also adds mods to a few usages of var() that were missing them.
=> fix(checkbox): rename misspelled mod and add missing mods

components/combobox/index.css, components/stepper/index.css, components/stepper/metadata/mods.md, components/stepper/themes/express.css, components/stepper/themes/spectrum.css, components/textfield/index.css
- Removes `padding-block-end` to fix the Express version of the Stepper button.
- Switches Textfield and Stepper to use `outline` for the focus indicator rather than an `::after` pseudo element.
=> fix(textfield, stepper): button padding and focus indicator

components/stepper/index.css, components/stepper/themes/express.css
This adds margin to the right side of the buttons for the Stepper in Express.
=> fix(stepper): fix express button width and spacing

components/stepper/index.css
There was an issue in SWC where the `border-radius` property was overriding some other things due to how they were compiling the CSS. This makes the two instances where `border-radius` is combined with more specific properties utilize the individual properties rather than the all-encompassing `border-radius` to prevent compilation differences.
=> refactor(stepper): use explicit border radius properties

.github/workflows/pr-update.yml, .github/workflows/testing.yml
The auto-updater we were using was not configurable to allow us to control what PRs get updated so I'm swapping it for this one that I forked that adds the functionality we need. 
- Filters out draft PRs
- Limits to 50 PRs to update per push
- Excludes PRs with blocked or wip labels
Moved the skip_vrt label to the Chromatic skip input which will pass PRs when the label is present. This will let us put the VRT as a required action.
=> chore: update auto-updater to configurable version

components/textfield/index.css, components/textfield/stories/template.js
**fix(textfield): valid in storybook - display correct icon size**
Fixes the 'valid' checkmark icon not displaying as the right size in Storybook. Needed to add the sizing number, which is programattically replaced with the right size based on the t-shirt size passed to the icon.
**fix(textfield): mod name for keyboard focus color**
Mod custom property for one of the keyboard focus styles was using the focus mod instead of the keyboard focus mod.
Tested in Storybook, Chrome on Mac
Storybook valid icon before:
Storybook valid icon after:
=> fix(textfield): storybook valid icon size and rename mod

components/divider/index.css
The Divider currently does not display in WHCM because the background-color is being overwritten by the size-specific class styling. This makes the WHCM styling more specific so that it applies at the right time.
=> fix(divider): WHCM color

components/popover/index.css, components/popover/stories/popover.stories.js
This is in response to [Issue #1873](https://github.com/adobe/spectrum-css/issues/1837) where the drop-shadows of nested Popovers affected each other due to the use of the `filter` property. 
This PR adds a filter variable to prevent any nested Popovers from doubling down on the filter. 
- **How this was tested:** A Nested story was added to Storybook in order to test nested Popovers
The difference is subtle but you can see that the drop-shadow is much darker in the original as the filter was being layered
**Current**
**Updated**
=> fix(popover): keep nested drop shadows from affecting the other

.prettierignore, .prettierrc, package.json
A prettier config was required for a utility being used in the updated 11ty site so I thought we could pull the implementation out into it's own PR and evaluate if we want to add it as a linter during commits.
Implementation options:
- Merge this and let prettier do it's thing as files are updated in PRs
- Merge this and then run it across all our relevant files and commit that in one go
=> chore: add prettier configuration

.github/workflows/linting.yml, .prettierignore, .stylelintignore, .stylelintrc.json, components/checkbox/index.css, components/switch/index.css, package.json, plugins/README.md, plugins/stylelint-no-missing-parenthesis/CHANGELOG.md, plugins/stylelint-no-missing-parenthesis/README.md, plugins/stylelint-no-missing-parenthesis/index.js, plugins/stylelint-no-missing-parenthesis/package.json, plugins/stylelint-no-missing-parenthesis/test.js, plugins/stylelint-no-missing-var/CHANGELOG.md, plugins/stylelint-no-missing-var/README.md, plugins/stylelint-no-missing-var/index.js, plugins/stylelint-no-missing-var/package.json, plugins/stylelint-no-missing-var/test.js, plugins/stylelint-suit-naming-pattern/CHANGELOG.md, plugins/stylelint-suit-naming-pattern/README.md, plugins/stylelint-suit-naming-pattern/index.js, plugins/stylelint-suit-naming-pattern/package.json, plugins/stylelint-suit-naming-pattern/test.js, yarn.lock
* Adds Stylelint to the project & borrows from some of the standard config.
* Adds a new `linting` GH Action to allow for linting in CI.
``` yarn lint:styles ```
Chrome and in Github workflow
=> feat: add stylelint

components/thumbnail/index.css
I noticed that border on thumbnail was missing and found a small typo.
Changes `var(--spectrum-thumbnail-border-color-opacity)` to `var(--spectrum-thumbnail-border-opacity)`
Browser(s) and OS(s) this was tested with:
Chrome Version 113.0.5672.63 on macOS
Safari 16.4 on macOS
Firefox 112.0.2 on macOS
=> fix(thumbnail): border opacity typo

components/tokens/package.json, yarn.lock
* Updates to `@adobe/spectrum-tokens@12.12.0`.
* Changelog for `12.12.0` (adds Tabs tokens): https://github.com/adobe/spectrum-tokens/releases/tag/%40adobe%2Fspectrum-tokens%4012.12.0
* Changelog for `12.11.0` (deprecates a misspelled Picker token): https://github.com/adobe/spectrum-tokens/releases/tag/%40adobe%2Fspectrum-tokens%4012.11.0
=> feat(tokens): update to spectrum-tokens v12.12.0

package.json
The `build:all` command was throwing errors due to the order of tasks conflicting with the caching technique. Removed the `build:components` task as this is being performed during the `build:preview` command; components are dependencies of the storybook build and so are always built before storybook starts. The `build:site` task is still managed by gulp but this will also be optimized when it migrates to being fired & cached by nx.
=> fix: reorder build:all script

components/accordion/stories/accordion.stories.js, components/colorhandle/stories/colorhandle.stories.js
Updates a few stories to reflect our new "Components" organization in Storybook.
=> docs: update story titles to reflect components categorization

.prettierignore, components/expressvars/custom.css
https://github.com/adobe/spectrum-css/blob/73400d88b4aa7afd535a161eba81a644baf7235f/components/expressvars/custom.css#L24
Fixes typo in slider variable for custom express vars. I did a search and did not see this variable used in the slider component b/c it's already been migrated to the new token system.
That makes this a pretty low-priority PR but in case someone downstream wanted to use this I guess. 🤷 
=> fix(expressvars): slider variable typo

components/actionbar/stories/actionbar.stories.js, tools/preview/decorators/index.js
* Allows for story-level parameters to be defined for the `withTextDirectionWrapper` decorator. This will allow us to create individual stories for RTL text directions + test them in Chromatic.
=> feat: add story-level parameter overrides for withTextDirectionWrapper decorator

.github/workflows/testing.yml, tools/preview/preview.js
RELEASE THE KRAKEN!!!
Unblock VRT runs for all active PRs.
Only run VRT for draft PRs if the run_vrt label is present.
=> chore: unlock vrt runs to all PRs

components/actiongroup/index.css, components/actiongroup/metadata/mods.md, components/actiongroup/stories/actiongroup.stories.js
This updates the pass-through variable names that were supposed to update the focus indicator border-radius when the `compact` variant was used. The variable names were incorrect so the value was not being updated and the focus indicator border radius was incorrect. 
This PR also adds a few more stories to Storybook to further flesh out or VRTs.
=> fix(actiongroup): focus indicator border radius

.github/workflows/testing.yml
To ensure up-to-date ancestors for Chromatic, we'll need to ensure we rerun VRT on every push to main.
=> chore: add main pushes to vrt

components/calendar/stories/calendar.stories.js, components/calendar/stories/template.js
VRT throwing errors on the today highlighter as it updates every day the tests are run.
This leverages the isChromatic() flag to hardcode the "today" value for VRT but leaves it variable in development mode.
=> chore(calendar): storybook fix for today highlighter

components/swatch/index.css
* Adds a `forced-colors` style for the custom property that controls the border color in `disabled` Swatches
Refs: https://github.com/adobe/spectrum-web-components/issues/3295
=> fix(swatch): specify forced-color style for disabled swatch borders

components/tag/index.css
The issue was related to the ::after pseudo-element being positioned absolutely with a top, bottom, left, and right value of 0, and having negative margin values for margin-inline-start and margin-block-start and the pseudo-element was covering the entire element, including the interactive parts.
Chrome, Storybook
https://github.com/adobe/spectrum-css/assets/8790510/d2701e92-9ae1-4194-b9aa-adb8ec490580
- [] I have tested these changes in Windows High Contrast mode.
=> fix: tag focus issue solved

tools/preview/DocumentationTemplate.mdx, tools/preview/decorators/index.js, tools/preview/package.json, tools/preview/preview.js, yarn.lock
* Provides the ability to pass a story-level parameter to set the language direction global
* Updates our "Autodocs" template to remove the stories list for a given component
This will give us the ability to pass a parameters object with a preset `textDirection` on the story level, and have the story render in that mode.
"ltr" is our default, and "rtl" is the other option.
```js
ActionButton.parameters = {
textDirection: "rtl"
}
```
=> feat: allow story-level params to be passed to RTL decorator

components/tokens/package.json, package.json, tools/preview/package.json, yarn.lock
We're encountering an error with our release process that appears to be due to an incompatibility in the latest release of Prettier, which we recently moved to as per Dependabot. This reverts that change to the version we had been using.
=> fix: revert prettier version bump

components/checkbox/index.css
=> fix: use language code, not coding language name

components/button/index.css, components/button/stories/button.stories.js
In SWC, the highcontrast text color for disabled buttons was incorrect. We were not explicitly assigning that color variable, so this PR adds `--highcontrast` variables for disabled color and border color.
[SWC Github Issue](https://github.com/adobe/spectrum-web-components/issues/3244)
- **How this was tested:** Tested using `yarn link` to verify that the change does indeed make the desired update in SWC
=> fix(button): add explicit highcontrast variables for disabled color

tools/preview/main.js, tools/preview/package.json, yarn.lock
Adds the Storybook Pseudo States addon so that we can more easily test hover states in Chromatic.
- [Testing hover and focus states in Chromatic](https://www.chromatic.com/docs/hoverfocus)
- [Storybook addon](https://storybook.js.org/addons/storybook-addon-pseudo-states)
=> feat: add Storybook Pseudo States addon

.github/dependabot.yml
A grouping setting is in public beta now for dependabot which would combine dependency updates for packages that exist within the same monorepo ecosystem. I have set up groups for storybook and commitlint. Hopefully this reduces the amount of dependabot PRs we get; especially ones that are redundant.
=> chore: add groups to dependabot

.github/workflows/testing.yml
This reverts to the older way that we were choosing to run Chromatic against Pull Requests.
Validate:
=> ci: prefer on-demand VRT instead of always-on

components/accordion/stories/template.js, components/actionbutton/stories/template.js, components/checkbox/stories/template.js, components/clearbutton/stories/template.js, components/closebutton/stories/template.js, components/combobox/stories/template.js, components/fieldlabel/stories/template.js, components/icon/stories/template.js, components/infieldbutton/stories/template.js, components/pagination/stories/template.js, components/picker/stories/template.js, components/pickerbutton/stories/pickerbutton.stories.js, components/pickerbutton/stories/template.js, components/tag/stories/template.js, components/textfield/stories/template.js, components/treeview/stories/template.js
Updates the Icon component (and all affected components) to no longer overwrite scale that is passed in with the icon name. Default icon sizing still exists if a scale is not passed in but an icon name and size is passed (i.e. "ChevronDown" along with a size param). This was the previous behavior. If an icon name is passed in along with the scale (i.e. "ChevronDown100") that scale will be kept and not overwritten. This allows for the few components that utilize different icon sizing than the default.
Validate:
2. A migrated documentation page …
=> fix: icon sizing

components/colorarea/index.css
In bringing in latest spectrum-css changes into SWC, some inconsistencies with tab index among the color components was pointed out. https://github.com/adobe/spectrum-web-components/pull/3477 
It was determined that the focused z-index for color area should be returned and this PR returns it. 
[PR where it was incorrectly removed](https://github.com/adobe/spectrum-css/pull/1753/files#diff-2a9b4d683047d5be7d0434985be0f220abc6b0a0e65e9c21230a738401946f23L53)
Validate:
2. A migrated documentation page (such as [action …
=> fix(colorarea): return z-index

components/tooltip/metadata/mods.md, components/tray/index.css, components/tray/metadata/mods.md
Update to **Tray** to use the new token `tray-top-to-content-area` that applies to both the top and the bottom (per design). This adds top and bottom padding to the tray. The tray is changed to `box-sizing: border-box` so that `max-block-size` and other size properties are not changed by the added padding.
CSS-469
Reviewing the docs page and Storybook in Firefox and Chrome (Mac).
Validate:
=> feat(tray): use token for top and bottom edge to content area

components/colorhandle/index.css, components/colorhandle/metadata/colorhandle.yml, components/colorhandle/metadata/mods.md, components/colorhandle/package.json, components/colorslider/index.css, components/colorslider/metadata/colorslider.yml, components/colorslider/package.json, components/opacitycheckerboard/README.md, components/opacitycheckerboard/gulpfile.js, components/opacitycheckerboard/index.css, components/opacitycheckerboard/metadata/mods.md, components/opacitycheckerboard/metadata/opacitycheckerboard.yml, components/opacitycheckerboard/package.json, components/opacitycheckerboard/stories/opacitycheckerboard.stories.js, components/opacitycheckerboard/stories/template.js, components/opacitycheckerboard/themes/express.css, components/opacitycheckerboard/themes/spectrum.css, components/swatch/index.css, components/swatch/metadata/swatch.yml, components/swatch/package.json, components/thumbnail/index.css, components/thumbnail/metadata/mods.md, components/thumbnail/metadata/thumbnail.yml, components/thumbnail/package.json, yarn.lock
- Creates new component for Checkboard Opacity and refactors ColorSlider, Swatch, ColorHandle, and Thumbnail to use new component for their background checkerboards. 
- Address lint failures as needed 
[Jira Ticket](https://jira.corp.adobe.com/browse/CSS-482)
Browser(s) and OS(s) this was tested with:
Chrome Version 113.0.5672.63 on macOS
Safari 16.4 on macOS
Firefox 112.0.2 on macOS
=> feat(opacitycheckerboard)!: new component

components/checkbox/index.css
Removes the need for the `.spectrum-Icon` class specifics in the Checkbox component by nesting to maintain specificity.
Validate:
=> refactor(checkbox): remove .spectrum-Icon from Checkbox styles

tools/preview/package.json
Adds the `--only-changed` flag to our CLI command for local Chromatic runs
Validate:
=> test: prefer enablement of TurboSnap for local Chromatic usage

components/popover/index.css, components/popover/metadata/popover.yml
Add highcontrast variables for Popover tip fill and stroke
Make dummy spacing a bit larger to keep from hiding the Popover tip on our docs site
Fixes Issue #1885 
1. Open the [docs site](https://pr-###--spectrum-css.netlify.app/popover.html) for the Popover component:
Validate:
=> fix(popover): add highcontrast variables and additional height in docs

components/tag/index.css, components/tag/metadata/tag.yml
Addresses [CSS-551](https://jira.corp.adobe.com/browse/CSS-551) and [SWC issue 3365](https://github.com/adobe/spectrum-web-components/issues/3365) by adding WHCM system color for focus ring abd border. 
Also addressed an issue where one of the disabled variants was receiving keyboard focus. 
Test outline:
1. Open the [deployed URL](https://pr-2043--spectrum-css.netlify.app/tag.html) for the tag component:
Validate:
1. A legacy documentation page (such as [accordion](https://pr-2043--spectrum-css.netlify.app/accordion.html)), including:
2. A migrated documentation page (such as [action group](https://pr-2043--spectrum-css.netlify.app/actiongroup.html)), including:
=> fix(tag): update whcm focus ring color

components/colorhandle/index.css, components/colorhandle/metadata/mods.md
Add the custom property `--mod-colorhandle-hitarea-border-radius` for the border radius of the hit area, so that other components that use colorhandle can easily customize it. Color slider sets it to square, not rounded in PR #1924 -- this update is cherry-picked from that PR so that it can merge in first.
Validate:
=> feat(colorhandle): add --mod-colorhandle-hitarea-border-radius

components/picker/index.css, components/picker/metadata/picker.yml, components/picker/stories/picker.stories.js, components/picker/stories/template.js, site/resources/js/enhancement.js
This adds a side label variant and styling to Picker. 
- In order for this to work correctly, the Picker component must be wrapped in a `div` with `display: inline-block`. This allows for the picker to be placed next to the inline label. The styling cannot be added to the Picker itself as it throws off the positioning of the Menu. This is already being implemented in SWC. 
- Added a `spectrum-Picker--sideLabel` class to allow for easier targeting (and translating in SWC) for when additional styling needs to be applied, specifically when used with the quiet variant.
- `margin-block-start` is changed to match the label when side label is used with the Quiet variant
=> fix(picker): add side label variant

site/resources/js/enhancement.js
Noticed an issue on main with the docs site scale, theme, directions, and vars popovers not appearing and I was seeing an error in console. 
Determined that `parent` [enhancement.js: 295](https://github.com/adobe/spectrum-css/pull/1991/files#diff-0ca3b69929af0604381cde30c53cb81b0e8be463dbbcfe37852529e8b15e6690R295) was returning `null` for these popovers. 
Fixes:
- Added fallback to body for when `popover.closest('.spectrum-CSSExample-container')` is null 
- removed console.log 
- addressed issue existing after fix with popover not closing when another was opened 
1. Open the [Docs Site](https://pr-2068--spectrum-css.netlify.app/calendar) for the any component:
2. …
=> fix(popover): docs site popover bug fix

components/combobox/package.json, components/picker/package.json, components/pickerbutton/package.json, components/popover/package.json, components/tabs/package.json, tools/component-builder-simple/package.json, tools/component-builder/package.json
1. Pull down this branch and run a clean install:
Validate:
1. A legacy documentation page (such as [accordion](https://pr-2069--spectrum-css.netlify.app/accordion.html)), including:  [@castastrophe]
2. A migrated documentation page (such as [action group](https://pr-2069--spectrum-css.netlify.app/actiongroup.html)), including:  [@castastrophe]
=> chore: update packages to migrated menu version

.github/dependabot.yml, components/tokens/package.json, package.json, tools/preview/package.json
There's some kind of incompatibility with the `3.x` releases of Prettier and our project. When we accept the Dependabot PRs that bump it to the latest version, we encounter errors during the Lerna-driven release process.
Validate:
=> fix: revert prettier

components/badge/index.css, components/badge/metadata/badge.yml, components/badge/metadata/mods.md, components/badge/stories/badge.stories.js, components/badge/stories/template.js, components/tokens/custom-spectrum/custom-dark-vars.css, components/tokens/custom-spectrum/custom-darkest-vars.css, components/tokens/custom-spectrum/custom-light-vars.css
[CSS-478](https://jira.corp.adobe.com/browse/CSS-478)
- Adds non-semantic color variants to the Badge component
- Adds the `notice` variant to the Badge component
- Removes the `black-text` custom text color options
- Updates `customLayout` to `fixed` to match design spec
- Docs and Storybook updated accordingly
1. Open the [docs](url) for the Badge component:
Validate:
=> feat(badge): add non-semantic colors

components/tag/index.css, components/tag/metadata/tag.yml, components/tag/stories/tag.stories.js, components/tag/stories/template.js, components/tag/themes/express.css, components/tag/themes/spectrum.css
This PR updated the Tag component to use new color tokens. 
- use new tokens for selected, not emphasized background colors 
- Updated content color for selected not emphasized to be `gray-50` in order to match XD file 
- Change instances of `--spectrum-Tags` to be `--spectrum-Tag` 
- Updated storybook to include variants: with Avatar, with Icon, and Removable 
Breaking Change:
- updated two class names from `--spectrum-Tags-*` to `--spectrum-Tag` 
Test outline:
1. Open the [deploy url](https://pr-2039--spectrum-css.netlify.app/tag.html) or storybook for the tag component:
- neutral-background-color-selected-default
- neutral-background-color-selected-hover
- …
=> fix(tag)!: update tag color tokens

components/picker/index.css, components/picker/metadata/mods.md, components/picker/stories/template.js
[CSS-573](https://jira.corp.adobe.com/browse/CSS-573)
This adds a `font-weight` property with a mod to the `.spectrum-Picker-label` class. There is a font-weight mod that already existed for the placeholder (if the label also had the `.is-placeholder` class) so I also updated that mod to be `--mod-picker-placeholder-font-weight` so that they stayed separate.
In testing this I also realized that the Picker storybook did not implement customStyles so I added that ability too. I also renamed the internal component of PickerButton to Picker to avoid confusion with the actual Picker Button component. 
1. Open the [docs](url) for the Picker component:
Validate:
1. A …
=> fix(picker): add separate mod for label font-weight 

components/slider/index.css, components/slider/metadata/mods.md, components/slider/metadata/slider.yml, components/slider/stories/slider.stories.js, components/slider/stories/template.js
This adds a side label variant to the Slider component and adds CSS to support it.
1. Open the [docs site](https://pr-2067--spectrum-css.netlify.app/slider) for the Slider component:
2. Open the [storybook](https://pr-2067--spectrum-css.netlify.app/preview/?path=/docs/components-slider--docs) for the Slider component
Validate:
1. A legacy documentation page (such as [accordion](https://pr-2067--spectrum-css.netlify.app/accordion.html)), including:
2. A migrated documentation page (such as [action group](https://pr-2067--spectrum-css.netlify.app/actiongroup.html)), including:
=> feat(slider): add side label variant

components/switch/index.css, components/switch/stories/switch.stories.js, components/switch/stories/template.js, components/switch/themes/express.css, components/switch/themes/spectrum.css
Updated selected (not emphasized) background color tokens to use: 
- neutral-background-color-selected-default
- neutral-background-color-selected-hover
- neutral-background-color-selected-down
- neutral-background-color-selected-key-focus
Updated storybook to include disabled and emphasized variants and controls for sizing and label
1. Open the [storybook](https://pr-2057--spectrum-css.netlify.app/preview/?path=/docs/components-switch--docs) for the Switch component:
2. Open the [Docs Site](https://pr-2057--spectrum-css.netlify.app/switch.html) for the Switch component:
Validate:
1. A legacy documentation page (such as …
=> fix(switch): update selected background color tokens

.github/dependabot.yml
For some reason dependabot opened several storybook prefixed packages as separate PRs rather than as part of the grouping we defined. This attempts to manually call those to see if we can force dependabot to correctly group the packages.
I expect (after this merges and if we close the current pull requests) dependabot to reopen a single storybook pull request for all the package updates.
=> chore: Update dependabot groups

components/actionbutton/index.css, components/actiongroup/index.css, components/assetcard/index.css, components/breadcrumb/index.css, components/button/index.css, components/clearbutton/index.css, components/closebutton/index.css, components/colorhandle/index.css, components/commons/basebutton-coretokens.css, components/commons/basebutton.css
This PR replaces `:focus-ring` with `:focus-visible` for the following components:
- Action Button
- Action Group
- Asset Card
- Breadcrumbs
- Button
- Clear Button
- Close Button
- Removes some duplicated styles that are already applied to the `:after` element on lines 159-170. 
- Color Handle
No visible styling changes should be present in this PR. 
1. Open the [docs](https://pr-2082--spectrum-css.netlify.app/) for this PR and compare to the [live docs site](https://opensource.adobe.com/spectrum-css/index.html):
Tested by @jawinn 
Validate:
1. A legacy documentation page (such as [accordion](https://pr-2082--spectrum-css.netlify.app/accordion.html)), including:
4. …
=> refactor!: replace focus-ring with focus-visible

components/checkbox/index.css, components/radio/index.css
Updates the Radio and Checkbox components to use new token for disabled content 
- replaces `--spectrum-gray-400` with `--spectrum-disabled-content-color` 
Note that the [Jira ticket ](https://jira.corp.adobe.com/browse/CSS-390) calls for the Switch component to also be updated, however this was already done in [this previously merged PR](https://github.com/adobe/spectrum-css/pull/2057/files#diff-ea9307b0b8fe931f6510d7704e8c86a215ec97918c5e306eaf8aa2074ba718a2R22). 
1. Open the [docs site](https://pr-2097--spectrum-css.netlify.app/checkbox) for the Checkbox component, find a disabled variant 
2. Open the [docs site](https://pr-2097--spectrum-css.netlify.app/radio) …
=> refactor(radio, checkbox): use new disabled content color token

components/tokens/custom-spectrum/custom-large-vars.css, components/tokens/custom-spectrum/custom-medium-vars.css
Adds  custom tokens needed for Alert Dialog #1862 
`--spectrum-alert-dialog-padding`
` --spectrum-alert-dialog-description-to-buttons`
There should be no UI changes! 
Validate:
1. A legacy documentation page (such as [accordion](https://pr-2101--spectrum-css.netlify.app/accordion)), including:
2. A migrated documentation page (such as [action group](https://pr-2101--spectrum-css.netlify.app/actiongroup)), including:
=> chore(alertdialog): adds custom tokens

site/resources/js/enhancement.js
Removing the focus-ring polyfill affect some custom JavaScript that we had running on the docs site to add/remove the `.is-focused` and `.is-keyboardFocused` classes for certain components. This PR updates that JavaScript to run without the need for the focus-ring class.
- Verify that a few other component focus states match the current production site 
Validate:
1. A legacy documentation page (such as [accordion](https://pr-2102--spectrum-css.netlify.app/accordion.html)), including:
2. A migrated documentation page (such as [action group](https://pr-2102--spectrum-css.netlify.app/actiongroup.html)), including:
=> chore: update javascript for site to account for removal of focus-ring

components/textfield/index.css
This adds a line-height definition to the textfield's input and sets that value equal to the height of the input. This prevents diacritics from being cut off in certain languages. Only applies to non-multiline (textarea) inputs.
Similar to https://github.com/adobe/react-spectrum/pull/4579 in React Spectrum.
[Jira ticket](https://jira.corp.adobe.com/browse/CSS-532)
There's no visual difference for English.
Local with changes vs. production
Validate:
2. A migrated documentation page (such as [action …
=> fix(textfield): add line-height to prevent missing diacritics

components/dialog/stories/dialog.stories.js, components/dialog/stories/template.js, components/underlay/gulpfile.js, components/underlay/index.css, components/underlay/metadata/mods.md, components/underlay/package.json, components/underlay/stories/template.js, components/underlay/stories/underlay.stories.js, components/underlay/themes/express.css, components/underlay/themes/spectrum.css
The DIY migration for Underlay 
- updates build system
- implements `--mods`
- uses custom tokens for animation values 
- adds `Underlay` to Storybook
- updates `Dialog` story to use the underlay component 
1. Open the [docs site](https://pr-2096--spectrum-css.netlify.app/dialog) for the dialog component. Scroll to Dialog - Alert Confirmation, Click on the cancel button to close it, then use the `Open Alert Confirmation Dialog` button to reopen. Inspect underlay compared to the underlay on the [live docs site](https://opensource.adobe.com/spectrum-css/dialog.html) for any design regressions.
2. Open the [storybook …
=> feat(underlay)!: diy migration

components/tokens/custom-spectrum/custom-dark-vars.css, components/tokens/custom-spectrum/custom-darkest-vars.css, components/tokens/custom-spectrum/custom-large-vars.css, components/tokens/custom-spectrum/custom-light-vars.css, components/tokens/custom-spectrum/custom-medium-vars.css
Add custom tokens for Coach Indicator, DIY migration with in #1992 
Should be no visible changes. 
Validate:
=> chore(coachindicator): adds custom tokens

components/button/stories/template.js, components/checkbox/stories/checkbox.stories.js, components/checkbox/stories/template.js
Cherry-pick of updates from the Table core tokens migration branch.
- Updated storybook for Checkbox to include the missing `is-indeterminate` option.
- Updated storybook for Button to include optional props for `aria-expanded` and `aria-controls`.
Validate:
=> docs: additional args for checkbox and button

components/checkbox/index.css
Fixes Issue #2054 
Removes `.spectrum-Icon` class name from the Checkbox CSS to prevent the components from bleeding into each other. The CSS should be specific enough already to not need that additional selector.
1. Open the [docs](url) for the checkbox component:
Validate:
3. A migrated documentation page (such as [action group](https://pr-###--spectrum-css.netlify.app/actiongroup.html)), including:
=> refactor(checkbox): remove spectrum-Icon class from checkbox css

components/page/gulpfile.js, components/page/package.json, components/page/themes/express.css, components/page/themes/spectrum.css
BREAKING CHANGE: migrates the Page component to use `@adobe/spectrum-tokens`
Validate:
=> feat(page)!: migrate to spectrum-tokens

components/colorhandle/metadata/colorhandle.yml
In a [previous PR](https://github.com/adobe/spectrum-css/pull/1916/files#diff-cef567e64c5625ed55f2621dd2f740ccdbe66ecde7c18c440ef1fcf386e6f6e8R19) the `is-disabled` class was dropped from the disabled variant. This puts it back. 
1. Open the [docs site] () for the ColorHandle component. 
Validate:
=> fix(colorhandle): disabled class

components/tokens/custom-express/custom-dark-vars.css, components/tokens/custom-express/custom-darkest-vars.css, components/tokens/custom-express/custom-light-vars.css, components/tokens/custom-spectrum/custom-dark-vars.css, components/tokens/custom-spectrum/custom-darkest-vars.css, components/tokens/custom-spectrum/custom-large-vars.css, components/tokens/custom-spectrum/custom-light-vars.css, components/tokens/custom-spectrum/custom-medium-vars.css, components/well/gulpfile.js, components/well/index.css, components/well/metadata/mods.md, components/well/metadata/well.yml, components/well/package.json, components/well/stories/template.js, components/well/themes/express.css, components/well/themes/spectrum.css
The DIY migration for Well
Build system updated
implemented --mods
used custom tokens for padding, background color values
Validate:
=> feat(well)!: diy migration 

components/actionbutton/index.css
This PR updates the XS size of the Action Button to use the correct tokens for `min-inline-size`.
[CSS-271](https://jira.corp.adobe.com/browse/CSS-271)
Please tag yourself on the tests you've marked complete to confirm the tests have been run by someone other than the author. 
1. Open the docs page for Action Button
Validate: @jawinn 
3. A migrated documentation page (such as [action group](https://pr-###--spectrum-css.netlify.app/actiongroup.html)), including:
=> fix(actionbutton): fix min-width var for xs size

components/actiongroup/index.css, components/actiongroup/metadata/actiongroup.yml, components/actiongroup/stories/actiongroup.stories.js
Add extra small spacing support to Action group
Extra small was recently added to Action button, but support for it had not yet been added to Action group.
Includes same spacing token as small, as defined in token specs design. Adds XS to examples and storybook.
CSS-273
1. Open the [storybook](https://pr-2154--spectrum-css.netlify.app/preview/?path=/story/components-action-group--default&args=size:xs) for the Action group component:
2. Open the [docs](https://pr-2154--spectrum-css.netlify.app/actiongroup) for the Action group component:
Validate: …
=> feat(actiongroup): add support for extra small

components/tokens/custom-express/custom-dark-vars.css, components/tokens/custom-express/custom-darkest-vars.css, components/tokens/custom-express/custom-light-vars.css, components/tokens/custom-spectrum/custom-dark-vars.css, components/tokens/custom-spectrum/custom-darkest-vars.css, components/tokens/custom-spectrum/custom-large-vars.css, components/tokens/custom-spectrum/custom-light-vars.css, components/tokens/custom-spectrum/custom-medium-vars.css
- Add missing semicolons to two custom properties added to custom-large-vars and custom-medium-vars
- Cleans up formatting to remove/add some extra spaces on some other declarations with the custom CSS files.
Validate:
=> fix: missing semicolons in custom vars

components/accordion/index.css, components/table/metadata/table.yml
A small update to the docs
- Remove old link at top of Accordion CSS that shouldn't be there
- Move emphasized class to parent in Table scroller example markup
=> docs: minor docs cleanup for table and accordion

components/infieldbutton/metadata/infieldbutton.yml
Now that we have the Chevron50 icon, this just adds back in the example for the small stacked variant of In-Field button to the docs site.
Validate:
=> chore(infieldbutton): adding back in example of small stacked variant

components/fieldlabel/index.css, components/fieldlabel/metadata/fieldlabel.yml, components/fieldlabel/metadata/mods.md, components/fieldlabel/stories/fieldlabel.stories.js, components/fieldlabel/stories/template.js
Update the required asterisk icon (which is set to `display: inline-block`) to be vertically aligned with the baseline of the text using the `vertical-align` property, instead of using new snapshot tokens. Removes some margin-block from the asterisk that was not needed.
Also adds stories for required and wrapping + required, and updates the docs.
Note: Per confirmation with design about the original Slack discussion, the asterisk should stay inline at the end of the text. It's not currently achievable in Figma due to container/frame layouts in the tool. Because of that, the asterisk placement in Figma will not match the asterisk placement in code.
CSS-582
1. Design …
=> feat(fieldlabel): required asterisk vertical alignment

components/tokens/custom-spectrum/custom-vars.css
Adds additional animation duration token, 3000ms, to be used in coach indicator for `--spectrum-coach-animation-indicator-ring-duration` 
Validate:
=> chore(tokens): add custom animation token

components/popover/metadata/popover.yml, components/popover/package.json
Noticed an error introduced with recent alert dialog changes to an example on the popover component. 
Changes:
- Added new markup for the alert dialog
- Updated variant description to include alert dialog 
- Updated dependency to include alert dialog 
1. Open the Docs Page for the Popover component and scroll to Popover - Dialog Style
Validate: @jawinn
3. A migrated documentation page (such as [action group](https://pr-###--spectrum-css.netlify.app/actiongroup.html)), including:
=> fix(popover): correct use of alert dialog with in popover

components/tokens/custom-express/custom-large-vars.css, components/tokens/custom-express/custom-medium-vars.css, components/tokens/custom-spectrum/custom-dark-vars.css, components/tokens/custom-spectrum/custom-darkest-vars.css, components/tokens/custom-spectrum/custom-large-vars.css, components/tokens/custom-spectrum/custom-light-vars.css, components/tokens/custom-spectrum/custom-medium-vars.css
Batch adding component-specific custom tokens from PRs #2164, #2168, #2185, #2175, #2188, and #1971 (all custom tokens that are ready for merge according to our merge queue doc).
Validate:
=> chore(tokens): batch add component-specific diy migration tokens

components/commons/metadata/mods.md, components/commons/overlay-coretokens.css, components/overlay/index.css, components/overlay/metadata/mods.md
Migrating overlay component to diy core tokens.
Adding --mod values to `commons/overlay-coretokens.css`
Validate:
=> feat(overlay): diy migration

components/modal/gulpfile.js, components/modal/index.css, components/modal/metadata/mods.md, components/modal/package.json, components/modal/stories/template.js, components/modal/themes/express.css, components/modal/themes/spectrum.css, components/tokens/custom-spectrum/custom-large-vars.css, components/tokens/custom-spectrum/custom-medium-vars.css
Migrating modal component to diy core tokens.
Validate:
=> feat(modal): diy migration 

components/assetlist/stories/template.js, components/miller/gulpfile.js, components/miller/index.css, components/miller/metadata/miller.yml, components/miller/metadata/mods.md, components/miller/package.json, components/miller/themes/express.css, components/miller/themes/spectrum.css
Migrates the MillerColumn component
Also:
- updates asset list storybook to correctly display Files Selectable variant
[Jira Ticket 509](https://jira.corp.adobe.com/browse/CSS-509)
Does not address issues within the asset list, added comment to Jira ticket for the Asset List migration detailing issues. 
Tested by @jawinn 
1. Open the [docs site](https://pr-2191--spectrum-css.netlify.app/miller) for the MillerColumns component: 
1. Open the [storybook site](https://pr-2191--spectrum-css.netlify.app/preview/?path=/story/components-miller-columns--files-selectable) for the MillerColumns component: 
Validate:
1. A legacy documentation page (such as …
=> refactor(millercolumns)!: tokens migration

components/button/stories/template.js, components/pagination/gulpfile.js, components/pagination/index.css, components/pagination/metadata/mods.md, components/pagination/metadata/pagination-explicit.yml, components/pagination/package.json, components/pagination/stories/pagination.stories.js, components/pagination/stories/template.js, components/pagination/themes/express.css, components/pagination/themes/spectrum.css, components/splitbutton/stories/splitbutton.stories.js, components/splitbutton/stories/template.js
Migrates the **Pagination** component to use Spectrum tokens.
This also:
- Removes the `.spectrum-Pagination-pageButton` class styles, as this is no longer used anywhere in the repository
- Fixes the following bug with RTL arrows, as seen in prod:
CSS-505
Validate:
=> refactor(pagination)!: migrate to spectrum tokens

components/dialog/index.css
* removes two unused custom properties: `--spectrum-dialog-confirm-max-inline-size` `--spectrum-dialog-confirm-max-height`
Those have been in the repo for quite some time, but have never been used in Spectrum CSS itself.
Validate:
=> refactor(dialog): remove unused custom properties

components/fieldlabel/index.css, components/fieldlabel/metadata/form.yml, components/fieldlabel/metadata/mods.md, components/fieldlabel/stories/form-template.js, components/fieldlabel/stories/form.stories.js, components/picker/metadata/picker.yml, components/picker/stories/template.js
- Fixes missing spacing between form items in Labels Above variant. This was using the wrong token (top-to-asterisk)
- Removes --spectrum-field-label-top-to-asterisk as it is no longer used
- Cleans up the CSS and its custom properties a bit. Adds some additional -mod properties.
- Removed two comments that were no longer applicable. One mentioned a docs file that does not seem to exist anymore, and the other mentioned a token value of 20px but it didn't equal 20px.
- Fixes form negative margin being too large and it moving outside its container. Instead use same value as border-spacing to remove the extra space, to make this like a margin top and bottom of zero which seems like the intention.
- Adds Form stories to Storybook (previously did not exist within Storybook)
- Fixes some …
=> refactor(fieldlabel): spectrum-Form cleanup and fixes

components/menu/index.css, components/menu/stories/menu.stories.js
A drill-in set to "open" was no longer showing the disabled color for the chevron icon. Moves disabled CSS after other CSS, which resolves this issue.
Also adds this case in the existing Storybook example for drill-in.
Fixes #2176
Validate:
=> fix(menu): drill-in disabled menu item chevron

components/splitbutton/metadata/splitbutton.yml
Update spectrum link because the one introduced in #2134 seems to be failing and it isn't the official public documentation anyway
Open the [Docs Site](https://pr-2178--spectrum-css.netlify.app/splitbutton) for the Split Button component:
Validate:
=> docs(splitbutton): fix spectrum link

components/checkbox/stories/checkbox.stories.js, components/checkbox/stories/template.js, components/menu/stories/template.js, components/switch/stories/template.js
This PR includes some minor Storybook updates to fix duplicate ID messages noticed in the console:
**Checkbox**
The same value was being used for the ID attribute on the checkbox label and checkbox itself. This update makes sure they are both given different IDs based on the passed in ID, by adding a suffix to the ID used on the checkbox input.
This also fixes the markup previously showing an empty ID attribute on the checkbox when the ID was not set.
**Switch**
The switch was using a hardcoded ID for the input and its label, so showing multiple switches resulted in duplicate IDs. This now sets unique IDs based on the passed in ID, along with a fallback.
Open the …
=> docs: storybook - fix duplicate ids for checkbox and switch

tools/preview/global.js
To confirm my theory that typography was not properly loading in Storybook before the build rework, I'm opening this PR which just fixes typography to see if the baselines differ.
Do the baselines diff?
=> chore: fix typography loading in storybook

.github/PULL_REQUEST_TEMPLATE.md
**GitHub PR template update**
Now that migrations are concluding, the part of the PR template under "regression testing" about migrated and non-migrated components no longer applies. Currently it references a non-migrated component that has already been migrated.
I've included some additions about running VRTs that could use some feedback.
Could we remove the "1. The documentation pages..." checkbox entirely? Is it still useful to have this or was that more of a temporary item for the previous build system?
=> docs: update pr template testing information

components/opacitycheckerboard/package.json, yarn.lock
Token version for opacitycheckerboard was out of sync causing an old version of tokens to be loaded as a dependency.
=> fix(opacitycheckerboard): align token version to latest release

components/dropindicator/gulpfile.js, components/dropindicator/index.css, components/dropindicator/metadata/mods.md, components/dropindicator/package.json, components/dropindicator/stories/template.js, components/dropindicator/themes/express.css, components/dropindicator/themes/spectrum.css, components/tokens/custom-spectrum/custom-dark-vars.css, components/tokens/custom-spectrum/custom-darkest-vars.css, components/tokens/custom-spectrum/custom-light-vars.css
Migrate Drop Indicator to Spectrum Tokens
1. Open the [storybook](url) for the drop indicator component:
Validate:
=> feat(dropindicator): migrate to spectrum tokens

components/tokens/custom-spectrum/custom-dark-vars.css, components/tokens/custom-spectrum/custom-darkest-vars.css, components/tokens/custom-spectrum/custom-large-vars.css, components/tokens/custom-spectrum/custom-light-vars.css, components/tokens/custom-spectrum/custom-medium-vars.css
=> chore(tokens): add custom tokens for dropindicator, assetlist, treeview

components/textfield/index.css, components/textfield/metadata/mods.md
Address issue with Text field and Text area where input text was appearing behind the icon when the user entered text (see screenshots). 
- added padding inline end to inputs of valid and invalid variants to match designs and address reported issue
- looked into and removed old code as indicated with TODO comments 
1. Open the [docs site](https://pr-2220--spectrum-css.netlify.app/textfield#valid) for text-field. 
2. Open the [docs site](https://pr-2220--spectrum-css.netlify.app/textarea#valid) for text-area. 
Validate:
3. A migrated documentation …
=> refactor(textfield): invalid and valid padding inline end 

components/thumbnail/index.css, components/thumbnail/stories/template.js, components/thumbnail/stories/thumbnail.stories.js
Addresses [SWC issue #3405](https://github.com/adobe/spectrum-web-components/issues/3405)
-adds `is-focused` to storybook controls 
- add window high contrast mode custom properties to layer variants to match expected behavior as reported on issue. 
Validate:
=> feat(thumbnail): add whcm for layer variants

components/treeview/index.css, components/treeview/metadata/mods.md, components/treeview/metadata/treeview.yml, components/treeview/stories/template.js, components/treeview/stories/treeview.stories.js, site/resources/js/enhancement.js
**Tree view fixes**
A refactor to fix these various issues discovered with Tree view:
- Incorrect indentation at various t-shirt sizes.
- Tree view items and their link element had irregular heights depending on whether they had a chevron or not. 
- Tree view items were not the correct component heights at various t-shirt sizes.
- Tree view item indicator (chevron) was not square and not the right size at various t-shirt sizes.
- Font-size was not changing. Now uses font-size tokens, confirmed with design.
- Standalone was not showing rounded corners (now renamed to "detached" per guidelines).
- Selected Thumbnail items were showing focus styles instead of selected styles; examples now include the "layer" variant of Thumbnail.
- "Section" had heading divs that were a child of `ul`, which …
=> refactor(treeview): fixes for sizes, height, and indicator alignment

components/picker/metadata/picker.yml
Update picker docs site menu mark up to address #2180
- added class `spectrum-Menu-itemIcon--workflowIcon` to the menu item icons (thumbnails) to fix icon spacing
- added class  `is-selectable` to menu <ul> to fix check mark visibility
1. Open the [docs site](https://pr-2226--spectrum-css.netlify.app/picker) for the picker component and the [live docs site](https://opensource.adobe.com/spectrum-css/menu.html#standardwithsectionheadersanddividers) for the menu
Validate:
2. A migrated documentation page (such as [action …
=> docs(picker): update markup for menu 

components/slider/index.css, components/slider/metadata/slider.yml, components/slider/stories/slider.stories.js, components/slider/stories/template.js
This PR addresses issue #2200.
- Adjust focus state to match [the spec](https://spectrum.corp.adobe.com/page/slider/#Keyboard-focus) (previously it looked like the active state which was incorrect)
- Standard variant works in high contrast mode. See Xd file in spec for reference.
- Disabled slider has the default cursor on hover. This was already set in a couple places (`.spectrum-Slider` and `.spectrum-Slider-handle`) but needed to be explicitly set on `.spectrum-Slider-controls` to take effect since this class has a specified `cursor: pointer` when the slider isn't disabled.
Validate:
1. A legacy documentation page (such as …
=> fix(slider): focus state matches spec, supports forced-colors

components/fieldgroup/metadata/fieldgroup.yml, components/fieldgroup/stories/fieldgroup.stories.js, components/fieldgroup/stories/template.js, components/helptext/stories/helptext.stories.js, components/helptext/stories/template.js, components/radio/index.css, components/radio/metadata/radio.yml
The invalid state of radios is now defined on the Field group (with `role="radiogroup"`):
> In updating documentation on properly showing invalid state in radio groups in SWC. We discussed removing the invalid attribute from the Radio component—favoring the Radio Group instead. In WAI-ARIA 1.2, the aria-invalid state is deprecated on role="radio"...
Some of the Spectrum CSS documentation was updated previously, but there were specific styles covering the invalid state in the Radio component's CSS. This `is-invalid` class has been removed in this PR. This does not to appear to have any visual effect, as the color was already a default. Per the guidelines and existing Field group example, "the error is indicated with negative Help text, along with an Icon."
The `aria-invalid` attribute …
=> refactor(radio): remove deprecated use of invalid

components/tokens/custom-spectrum/custom-large-vars.css, components/tokens/custom-spectrum/custom-medium-vars.css, components/tooltip/index.css
Per issue #2156, Tooltips (all variants except the hover variant) were inheriting the wrong animation distance (6px instead of the 4px that is [noted in the spec](https://spectrum.adobe.com/page/tooltip/#Offset)). This work adjusts the animation distance for the component.
Validate:
=> fix(tooltip): custom animation distance overrides overlay value

.github/workflows/build.yml, .github/workflows/compare-results.yml, .github/workflows/lint.yml, .github/workflows/production.yml, .github/workflows/publish-site.yml, .github/workflows/vrt.yml
This sets stricter timeout limits on the updated CI tasks.
=> chore(ci): add stricter timeouts to jobs

components/stepper/stories/template.js, components/textfield/stories/template.js
A small update for Storybook components that do not allow unique IDs to be set on their inputs, which need to be associated with a label.
**docs(textfield): add arg to storybook for input id**
Add ability to pass in an ID for the Text field input. Needed for components such as Label that can refer to this ID.
**docs(stepper): storybook - use an id on its input**
Also set an ID on the input created by Stepper when an ID is passed in.
Validate:
=> docs: storybook - allow ids for textfield and stepper

.storybook/main.js
When building the static storybook, a stray `../` (which is represented in webpack with `_/`) is messing with the pathing to the vars & expressvars.  This should correct for that.
CI 🎈
=> chore: patch storybook build for ci

.storybook/postcss.config.js
There was a typo in the postcss.config.js for storybook where it was not capturing the foldername accurately. If the package existed in the node_modules folder, it was returning `../` instead of the foldername as expected. This means the tokens were not running through the postcss parsing they were supposed to that adds the `.spectrum--express` modifier and allows us to support loading styles for vars & expressvars at the same time. This led to coachmark and searchwithin to loading the expressvars stylesheet when taking baseline snapshots and failing VRT.
=> fix(storybook): postcss parsing error for node_modules paths

components/radio/index.css
Per issue #2251, the focus outline wasn't being positioned correctly for radio buttons in RTL. This work adjusts the horizontal spacing for RTL by tweaking the transform property.
In [the docs site](https://pr-2315--spectrum-css.netlify.app/radio):
In [Storybook](https://pr-2315--spectrum-css.netlify.app/preview/?path=/story/components-radio--default):
Validate:
=> fix(radio): focus outline has correct position for rtl

components/popover/index.css, components/popover/metadata/mods.md, components/popover/metadata/popover.yml, components/popover/stories/template.js, site/resources/js/enhancement.js
This has been a difficult component to test without implementing it. What I landed on is that the [8px offset distance in the spec](https://spectrum.adobe.com/page/popover/#Offset) should be accomplished by the animation.
For popovers without a tip, we can simply customize the animation-distance value to align with the spec.
For popovers with a tip, we need to add an offset margin equal to the width or height of the tip (depending on the position of the popover) so that the animation-distance is applied against the popover + tip.
- Popover (or it's tip if there is one) is offset 8px from the source [per the spec](https://spectrum.adobe.com/page/popover/#Offset)
- Docs have been updated to reflect the change to default
- Storybook examples have been updated to show the correct default …
=> fix(popover): offset matches spec

components/checkbox/stories/template.js, components/menu/index.css, components/menu/metadata/menu.yml, components/menu/metadata/mods.md, components/menu/package.json, components/menu/stories/menu.stories.js, components/menu/stories/template.js, components/tray/metadata/tray.yml
**Menu - Tray Submenus**
Adds the "Tray submenus" feature to the **Menu** component. [Guidelines](https://spectrum.adobe.com/page/menu/#Tray-submenus):
> When a menu is displayed within a tray, a submenu will replace the tray content when the parent menu item is selected. A submenu displays a back button (labeled by the title of the parent item) at the top of the tray to return the user to the previous level of the menu.
This adds some additional CSS, a new example on the docs, and a new story in Storybook.
Some additional markup was adjusted in the docs to rename some duplicate IDs.
The markup for this is based on the existing "Standard with section headers and dividers" example. As the back item functions like a "section header", but with an additional button for navigating back. I've …
=> feat(menu): tray submenus

components/fieldgroup/metadata/fieldgroup.yml, components/fieldlabel/index.css, components/fieldlabel/metadata/form.yml, components/fieldlabel/metadata/mods.md, components/fieldlabel/stories/form-template.js
Refactors `.spectrum-Form` (which currently exists within the FieldLabel component) to modernize its layout. This changes the display to use CSS `grid` instead of `table`, which helps get rid of the need for negative margins and different ways of handling spacing between the two variants. 
Deprecates some Form --mod properties:
- `--mod-tableform-border-spacing` has been renamed to `--mod-form-item-block-spacing` and has a temporary fallback for the old name.
- `--mod-tableform-item-block-spacing-labels-above` has been renamed to `--mod-form-item-block-spacing-labels-above` and has a temporary fallback for the old name.
- `--mod-tableform-margin`
- `--mod-tableform-margin-labels-above`
Additional mods have been added for modifying the size of the the grid tracks.
**FieldGroup**: Removes …
=> refactor(fieldlabel): form - replace table layout with grid

components/breadcrumb/metadata/breadcrumb.yml, components/breadcrumb/stories/breadcrumb.stories.js, components/breadcrumb/stories/template.js, components/card/index.css, components/card/metadata/card.yml, components/dropzone/index.css, components/dropzone/metadata/dropzone.yml, components/floatingactionbutton/index.css, components/tabs/index.css, components/textfield/index.css, components/textfield/metadata/textfield.yml, components/textfield/stories/textfield.stories.js
Some of our components (breadcrumb, card, dropzone, floatingactionbutton, tabs, textfield) were showing and persisting a keyboard focus indicator on mouse focus. This PR adjusts those components to show the correct focus indicators for keyboard and mouse.
In [Storybook](https://pr-2306--spectrum-css.netlify.app/preview/?path=/story/components-breadcrumbs--default):
In [Storybook](https://pr-2306--spectrum-css.netlify.app/preview/?path=/story/components-card--default):
[Docs site](https://pr-2306--spectrum-css.netlify.app/card) includes:
In [Storybook](https://pr-2306--spectrum-css.netlify.app/preview/?path=/story/components-drop-zone--default):
In …
=> fix: focus outlines only on keyboard focus

components/infieldbutton/index.css
This work addresses issue #2233, which noted that focus shouldn't persist after mouse interaction.
Validate:
=> fix(infieldbutton): focus wont persist after mouse interaction

.github/workflows/build.yml
This addition will fail the CI workflow if any uncommitted assets are found at the end of the build process.
On a fork branch of this PR, remove one or more of the mods.md assets from any component.
=> chore(ci): error if uncomitted changes found on build

.github/workflows/publish-site.yml
When chromatic isn’t run as part of the ci workflow, the site should kick off a local storybook build. This fixes the path to that build.
For a build without vrt, validate storybook is built locally to the dist/preview path.
=> chore(ci): fix workspace path for storybook build

components/tag/metadata/tag.yml, components/tag/stories/tag.stories.js, components/tag/stories/template.js, components/taggroup/metadata/taggroup.yml
Removed all examples of invalid tags with out the correct icon from the docs site and storybook. 
Updated storybook controls so invalid tags always have the alert icon. 
[Design Docs](https://spectrum.adobe.com/page/tag/#Error) 
Addresses [SWC issue 3378]( https://github.com/adobe/spectrum-web-components/issues/3378)
@mdt2 
Validate:
=> docs(tag): invalid tags should always include icon

.github/actions/file-diff/index.js, .github/actions/file-diff/utilities.js
A small patch to the details table formatting in the CI diff output comment and a clarification of values with less than 0.01KB difference.
You can see these issues in the screenshots below from https://github.com/adobe/spectrum-css/pull/2338#issuecomment-1841084699
Should see these fixes in the comments of this PR.
=> chore(ci): correct data formatting for diff comment

.github/actions/file-diff/index.js
The filemap object in the compare results workflow was not correct deconstructed so that it could be run through the reduce function. This fixes that issue.
=> chore(ci): deconstruct filemap in workflow

components/infieldbutton/index.css, components/infieldbutton/metadata/mods.md, components/stepper/index.css, components/stepper/metadata/mods.md, components/stepper/themes/express.css, components/stepper/themes/spectrum.css
Per issue #2234, Stepper shouldn't be using classes that it doesn't own. This PR adds some properties to InfieldButton and uses their mods to modify them for Stepper so that we no longer touch InfieldButton classes inside our Stepper component. There should be no visual differences to the components.
**Note:** When reviewing the code, [filter commits](https://github.com/adobe/spectrum-css/pull/2300/files/2c9965dd3b7b93eeeb21ba83f37964fac5863d61..4dc140f81210b5b36020899df381c25c229d4e7b) so that you aren't reviewing separate changes made in PR #2234.
1. Stepper variants match prod:
2. InfieldButton variants match prod:
3. The naming of the custom props in [the …
=> fix(stepper): no longer touches InfieldButton classes

.gitignore, .storybook/package.json
In order to run the chromatic command locally, a build script must exist in the package.json. This brings back the build command so that the chromatic build continues to work locally.
=> fix(storybook): chromatic requires build script

.storybook/postcss.config.js, components/assetlist/package.json, components/dropzone/package.json, components/icon/stories/icon.stories.js, components/icon/stories/template.js, components/icon/stories/utilities.js, components/miller/package.json, ui-icons/svgo.config.js
Storybook: Set up storybook's postcss tool to check all available dependencies in a package for a vars dependency to determine which builder to load - this is a preparation for the nx builder updates.
Storybook: Load icons in preview rather than on the fly to prevent duplicate loads.
Icon: Update storybook loader to allow users to preview Arrow & Chevron in the icon story (currently fails to load).
UI-Icons: Prevent SVGO from removing hidden elements.
=> chore(storybook,ui-icons): clean-up and preparations for nx build

components/picker/themes/express.css, components/picker/themes/spectrum.css
Addresses current issue with the express picker where text positioning and focus indicators did not match design specs. 
Fix: the token values for border width on the picker was set to `0` for express. For any of the css where we were using `calc()` with the border width being `0` the calc() was returning 0. Created custom tokens for the border width and set the express values to `0px` instead of `0` 
This was [changed in the tokens repo](https://github.com/adobe/spectrum-tokens/blob/0d1a03f7dafbd67c50b976ad0ab54674a242929f/packages/tokens/CHANGELOG.md?plain=1#L54) relatively recently. 
Validate:
1. The documentation pages for at least two other components are still …
=> fix(picker): express border width values

components/dropzone/stories/dropzone.stories.js, components/dropzone/stories/template.js, components/illustratedmessage/stories/illustratedmessage.stories.js, components/inlinealert/stories/inlinealert.stories.js, components/inlinealert/stories/template.js, components/menu/stories/menu.stories.js, components/miller/stories/miller.stories.js, components/picker/stories/picker.stories.js, components/progressbar/stories/meter.stories.js, components/progressbar/stories/metertemplate.js, components/progressbar/stories/progressbar.stories.js, components/radio/stories/radio.stories.js, components/radio/stories/template.js
Adjusts some components in Storybook to include wrapping and truncation examples, visually where needed and for Chromatic otherwise.
- **Dropzone**: Adds a Chromatic-only instance with wrapping heading and description. I chose Chromatic-only on this one since it uses Illustrated Message, a component that already shows a wrapping description as a visual example.
- **Illustrated Message**: Adds a Chromatic-only instance with a wrapping heading since we already have a visual example (also tested in Chromatic) with a wrapping description.
- **In-Line Alert**: Adds a Chromatic-only instance with wrapping heading and description.
- **Menu**: Adjusts existing labels to wrap to the next line.
- **Miller Columns**: Adjusts an existing label to truncate.
- **Meter**: Updates the template to a …
=> docs: storybook wrap, truncate examples part 2

components/picker/index.css
**Picker**: A few fixes for forced-colors/Windows High Contrast Mode to address the bugs in CSS-636, along with a few more discovered when working on it. Along with some cleanup work.
- The focus indicator ring now only shows on keyboard focus. It was showing all the time by default.
- The color of the focus indicator and the border are no longer reversed. This now matches the visual behavior that was decided upon for Text field, where the indicator is blue and the border color inside it is the default grey (keyboard focused).
- The hover `Highlight` border color now appears on hover (except when keyboard focused).
- Proper [matching foreground/background pairs](https://www.w3.org/TR/css-color-4/#css-system-colors) are now used for the system colors defined. The `ButtonText` foreground …
=> fix(picker): high contrast and other color fixes

components/accordion/stories/accordion.stories.js, components/accordion/stories/template.js, components/actionbutton/stories/index.js, components/alertbanner/stories/alertbanner.stories.js, components/alertbanner/stories/template.js, components/alertdialog/stories/alertdialog.stories.js, components/assetlist/stories/assetlist.stories.js, components/badge/stories/badge.stories.js, components/badge/stories/template.js, components/card/stories/card.stories.js, components/card/stories/template.js, components/checkbox/stories/checkbox.stories.js, components/checkbox/stories/template.js, components/combobox/stories/combobox.stories.js, components/combobox/stories/template.js, components/contextualhelp/stories/contextualhelp.stories.js, components/contextualhelp/stories/template.js, components/dialog/stories/dialog.stories.js
Add truncate/wrap examples to storybook for: 
- added a story with a max-width
- adjusted card title and item to display wrapping
- added another example to already in place action button grouping
- added stories to display all three alert banner variants (default, info, negative)
- adjusted content to better display wrapping and not wrapping behaivor 
- increased length to one of the asset items to display truncating
- added grouping of badges that displays: label only, icon online, icon+ label, and icon + label + wrapping
- adding grouping of checkboxes that displays: checkbox, checkbox checked, checkbox indeterminate, and checkbox with wrapping label 
- changed content and custom styling for focused variant to also display wrapping 
- Added quiet story 
- Added control for readOnly 
- …
=> docs: storybook wrap and truncate examples part 1

components/infieldbutton/index.css
Addresses issue #2232. Per [the spec files](https://www.figma.com/file/nchxla8gD4CxWYwt9eiRrz/Token-definition-library?type=design&node-id=814-8857&mode=design&t=HifoxkguijiFSIM0-0), the In-field Button component shouldn't have an outline on keyboard focus. Keyboard focus also looks the same as hover focus for this component.
1. Open the component in [the docs site](https://pr-2288--spectrum-css.netlify.app/infieldbutton)
2. In the docs site, turn on WHCM
4. Open the component in [Storybook](https://pr-2288--spectrum-css.netlify.app/preview/?path=/story/components-in-field-button--default)
Validate:
1. The documentation pages for at least two other components are …
=> fix(infieldbutton): no outline on focus-visible

components/asset/skin.css
Addresses SWC issue [3376](https://github.com/adobe/spectrum-web-components/issues/3376)
"When running in high contrast mode the file and folder asset types should use the high contrast mode colours so they are always visible no matter the theme chosen"
Fix: 
- use `currentColor` on the background fill of the file and folder background when `forced-colors: active` 
- `currentColor` matches the inherited color property which unlike svg fill is overwritten with WHCM values 
Open the docs site and emulate WHCM 
Validate:
2. If components have been modified, VRTs have been run on …
=> fix(asset): add whcm values for asset background color

.github/actions/file-diff/README.md, .github/actions/file-diff/action.yml, .github/actions/file-diff/index.js, .github/workflows/compare-results.yml, .vscode/settings.json
This is clarifying some of the equations used to determine file diffs and creates a clearer variable naming for the head and base branches being evaluated.
* path renamed to head-path
* diff-path renamed to base-path
* this same renaming is carried throughout the file-diff/index.js file
* before the summary table, I added the following note: `Table below reports only on changes to a package's main file. Other changes can be found in the collapsed "Details" below.`
* fixed the summary table to report on changes to the main file (before it was reported whatever the last file in the list was)
* more comments throughout
=> chore(ci): correct the direction of diff equations

.storybook/main.js, .storybook/package.json, yarn.lock
Removes the Storybook addon `storybook-addon-pseudo-states`.
This addon for Storybook injects some CSS that results in components displaying differently. Resulting in incorrect component previews and VRTs. This was noticed in both Stepper and Combobox, especially with any styles containing `:not` selectors.
Validate:
An example of how this addon was causing components to render incorrectly in PR #2375 :
Addon enabled (Storybook):
Addon disabled (Storybook):
=> fix: remove storybook-addon-pseudo-states

.env.example
Chromatic's config is looking for a build script in the .storybook config folder but the current script defined is one that exists at the root package. This corrects this and thus allows us to re-run baselines from the UI in a local storybook instance.
1. Delete any existing `.env` files and `.storybook/chromatic.config.json` files.
2. `yarn install` - after the install, this runs the config script which generates a new set of the above files.
```
{
"projectToken": "********",
"projectId": "Project:64762974a45b8bc5ca1705a2",
"buildScriptName": "build"
}
```
```
CHROMATIC_PROJECT_ID="Project:64762974a45b8bc5ca1705a2"
CHROMATIC_BUILD_SCRIPT_NAME="build"
```
1. `yarn start`
2. Go to a story (not a docs page) and click the `Visual Tests` tab in the panel.
3. Click the `Sign in with Chromatic` …
=> chore: update build script used in chromatic config

README.md, package.json, tasks/compare-compiled-output.js
During parallelization, the latest files are being unpacked into the same folder and so compare scripts are sometimes being run against another component's assets as a baseline resulting in invalid results.
This ensures each run is unpacked into a distinct folder.
This is also correcting an issue when running the compare script against multiple components using the yarn shortcut as they each spin up separate HTML summary pages rather than combining results into 1 summary page as expected. By running the script directly, this ensures results are collated.
1. `yarn install`
2. `yarn build`
=> chore: update compare script to fix an issue when runs are parallelized

tools/component-builder-simple/css/index.js, tools/component-builder/css/lib/varUtils.js, tools/component-builder/css/vars.js
Currently, whether a package uses the themes/*.css assets for styling or not, those placeholder files must exist in order for the build to work. If you remove empty theme files, the build for that component will fail even though the files are not needed.
This fix removes that requirement so that we can delete theme assets when they are not needed and clean-up technical cruft.
- Remove the themes folder in `components/accordion` (**note** do not commit this change to the branch)
=> build: allow empty theme assets during build step

components/stepper/index.css
Currently the disabled express stepper does not display a border around the buttons part of the stepper 
Fix: change the border width for the buttons border to 2px when `forced-colors: active`
On the [docs site]( https://pr-2384--spectrum-css.netlify.app/stepper) for stepper emulate WHCM 
Validate:
=> fix(stepper): express whcm

components/menu/index.css, components/menu/metadata/menu.yml, components/menu/stories/menu.stories.js, components/menu/stories/template.js
BREAKING CHANGE
"Previously the spectrum-Menu-itemLabel--wrapping class could be added to the spectrum-Menu-itemLabel element in a Menu Item to prevent it from wrapping and force it to use an ellipsis instead."
Fix: 
- the css to truncate was not able to be applied because `spectrum-Menu-itemLabel` had `display: flex;`
[read more about flex causing issues with truncate](https://css-tricks.com/flexbox-truncated-text/)
- I was able to remove this by changing the mark up of the Multi Selection with icons example which had the SVG with in the label 
- Rename classes to indicate truncating and not wrapping
- removed any html that was making it appear that the text with truncating `...`
Docs: 
- added example to docs site 
- added example to Storybook 
- added control to Storybook to toggle on …
=> fix(menu)!: reimplement text truncating

site/resources/js/enhancement.js
In some cases, we use `is-focused` and `is-keyboardFocused` classes in components where targeting `:focus` and/or `:focus-visible` aren’t enough to apply focus styles. This work aligns our docs site to limit application of those classes to components that need them and implement them in their CSS (vs before it was applying them to every component).
A couple interesting things that came up during this work:
- Some components (close button for instance) may not need to rely on `is-focused` and `is-keyboardFocused`. I’ll create a card in the backlog to evaluate this and adjust where needed.
- The mousedown functionality in enhacement.js seems a bit buggy. Sometimes when you mousedown on the element, it reports that you’re mousedown on the `<body>`, which must be why we have the check for …
=> refactor(site): programmatic focus is component-specific

components/calendar/index.css, components/swatch/index.css
Adjusting a couple components to use display instead of visibility. This can help improve performance by removing the unused elements from the DOM.
- Calendar days that aren't in the month being shown are hidden with display instead of visibility
- Swatch icons for disabled and mixedValue use display instead of visibility
A note: Overlay uses visibility in order to utilize the CSS transition property on visibility and opacity. This animation won’t work if we use the display property. This effects Modal and the use of Quick Actions in the Card component, which is why we aren't changing the visibility property in those components.
Evaluate the **Calendar component**, …
=> fix(calendar, swatch): use display instead of visibility

components/combobox/index.css, components/combobox/metadata/combobox.yml, components/combobox/stories/template.js, site/resources/js/enhancement.js
Combobox was migrated to core tokens before Textfield's migration was finished and we started using passthrough mod properties for the sub-components. This is a broad stroke refactor of the CSS to simplify much of it by using the mods available in Textfield and Picker Button. Removing mods was avoided in this PR to avoid breaking changes.
- Refactors much of the CSS to use mod properties for its sub components Textfield and Picker Button. 
- Includes some additional selectors to fix the border styles around the picker button so they match when interacting with the textfield, which is in more alignment with the gifs shown in the Guidelines. Previously when the textfield was focused for example, the focus border color did not extend around the whole combobox because the picker button border …
=> refactor(combobox): use sub component mod properties

.github/dependabot.yml
Due to a bug in the [addon-console](https://github.com/storybookjs/storybook-addon-console/issues/80#issuecomment-1876601028), we need to temporarily lock "@storybook/addon-actions" to ~7.5.
=> chore: lock addon-actions for dependabot

components/table/index.css
Replace one leftover token value referencing a _--spectrum-global_ token with the new token value.
This change should not affect anything visually as it's a fallback value.
Validate:
=> fix(table): replace leftover global color token

components/actionbutton/metadata/mods.md, components/button/metadata/mods.md, components/closebutton/metadata/mods.md, components/commons/basebutton-coretokens.css, components/logicbutton/metadata/mods.md, components/picker/metadata/mods.md
Some mod properties had been misnamed with reference to the global tokens. This adds the renamed mods to the _commons_ styles, with the old mods as a fallback, and adds deprecation notice comments. 
- `--mod-animation-duration-100` is now `--mod-button-animation-duration`
- `--mod-sans-font-family-stack` is now `--mod-button-font-family`
- `--mod-line-height-100` is now `--mod-button-line-height`
- `--mod-focus-indicator-gap` is now `--mod-button-focus-indicator-gap`
CSS-651
Validate:
=> fix(commons): rename and deprecate mods referencing global tokens

components/card/index.css
The custom mod property for the background color was named incorrectly as `--mod-spectrum-card-background-color` in one of the declarations. The correct mod name `--mod-card-background-color` already exists and is used by the rest of the file, so this is more of a bug fix than an overall renaming. A fallback and deprecation notice were left in case of existing usage of the old mod name.
Validate:
=> fix(card): rename misnamed instance of background color mod

.github/workflows/build.yml, .github/workflows/production.yml, .github/workflows/publish-site.yml, README.md
The production workflow has been [failing on pushes to main](https://github.com/adobe/spectrum-css/actions/runs/7559341848/job/20583250566); this PR resolves those errors.
- Move from `yarn cache:clean` to `yarn nx reset` for clarity and to prevent unexpected regressions when changes made to package.json
- Additional comment blocks in production workflow
- Add size change reporting - should add details to the build console if we want to see changes to main
- Remove built asset download for publish site as it's duplicative & add the storybook fallback task to after the site build so it isn't overwritten by the site clean
Can't be tested without merging it unfortunately 😭
=> ci: production workflow fixes

components/card/index.css
Reverts adobe/spectrum-css#2417
=> fix(card): revert misnamed instance of background color mod

components/quickaction/stories/quickaction.stories.js
The wrong root class for quickaction was being used in Storybook, resulting in missing styles. This updates the args to use the correct class, which is plural: `spectrum-QuickActions`.
Validate:
=> fix(quickaction): storybook using wrong root class 

components/card/index.css
Address [issue 3843](https://github.com/adobe/spectrum-web-components/issues/3843) by adjusting border-radius of horizontal card's preview.
Validate:
Before fix:
After fix:
=> fix(card): gap between preview and horizontal card border

components/opacitycheckerboard/README.md, components/opacitycheckerboard/index.css, components/opacitycheckerboard/metadata/opacitycheckerboard.yml, components/opacitycheckerboard/stories/opacitycheckerboard.stories.js, components/opacitycheckerboard/stories/template.js
Addresses: #2139 
> "With both the spectrum-ColorHandle and the spectrum-OpacityCheckerboard classes applied to the host element the rules within those selectors will race depending on how CSS is deployed in a consuming application. Specifically, the size rules for .spectrum-OpacityCheckerboard
> Can overwrite those of .spectrum-ColorHandle:"
> 
Changes: 
- removes "inline-size": "100%", "block-size": "100%", since the background should be used with a component with these properties already set, this is not needed with in this classes CSS
- move from components in storybook into utilities 
- improve docs for component and update storybook 
These changes as well as the SWC documentation improvements merged in with [SWC PR 3651 ](https://github.com/adobe/spectrum-web-components/pull/3651) …
=> refactor(opacitycheckerboard): address concerns about inclusion order

.github/workflows/development.yml, .github/workflows/production.yml
Set up the `spectrum-two` branch as a base branch for CI. Allows PRs to be opened against it and have all CI run to validate.
=> ci: allow spectrum-two PRs

package.json
The @spectrum-css/ui-icons package was missing from the pre-release build task. This PR adds it to prevent any missing dist output for future ui-icons releases.
=> chore: incorporate ui-icons build into prerelease task

components/menu/index.css, components/tag/index.css, components/tooltip/metadata/tooltip.yml, tools/component-builder-simple/css/processors.js, tools/component-builder-simple/package.json, tools/component-builder/css/processors.js, tools/component-builder/package.json, yarn.lock
Adds the `postcss-hover-media-feature` [plugin](https://github.com/saulhardman/postcss-hover-media-feature) to the build. This extracts and wraps rules containing :hover pseudo-classes in `@media (hover: hover) {}` media queries.
Reasoning: certain mobile browsers apply `:hover` styles on 'tap', which (in most cases) isn't desirable. By wrapping `:hover` styles with a [Hover Media Feature](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/hover) Media Query these styles will only be applied on devices that support them.
This plugin will change the `dist` of every component where `:hover` is used, so we'll want to be sure that there are no visual defects after …
=> feat: add postcss-hover-media-feature plugin to build

components/buttongroup/index.css, components/buttongroup/metadata/buttongroup.yml, components/buttongroup/stories/buttongroup.stories.js
BREAKING CHANGE 
Migrations the button group component to S2 
- updates tokens for vertical and horizontal spacing with in the buttongroup component 
- includes size small with in Chromatic 
Validate:
=> feat(buttongroup)!: migrate to S2

.gitignore, tokens/custom-spectrum/custom-large-vars.css, tokens/custom-spectrum/custom-medium-vars.css, tokens/dist/css/spectrum/custom-large-vars.css, tokens/dist/css/spectrum/custom-medium-vars.css, tokens/dist/index.css
Tokens additions for #2347 .
- Add icon XXL token, that is currently being used in a Card variant and at the top of each docs page. XXL does not currently exist as part of the formal design specs. Custom-vars are necessary to facilitate the migration to core tokens. The XXL size is planned to be deprecated in Spectrum 2.
- Add XXS token to support existing SWC size. The XXS size is also planned to be deprecated in Spectrum 2.
- Add large tokens used for combined UI Icon display.
CSS-511
Validate:
=> feat(tokens): add icon xxl and xxs tokens

components/actionbutton/stories/template.js, components/combobox/stories/template.js, components/pagination/stories/template.js, components/picker/stories/template.js, components/pickerbutton/stories/template.js, components/treeview/stories/template.js
Related component story fixes for a [fix](https://github.com/adobe/spectrum-css/pull/2347/commits/50ff030c9a2e2af7807a0c82e63eccb845806c52) in the Icon migration #2347 , that helps fix the wrong workflow icons appearing for arrow and chevron.
These are both icons with names that exist in both icon sets. Some component stories need the icon set specified. These changes were cherry-picked from that PR to avoid breaking changes.
Validate:
If components have been modified, VRTs have been run on this branch:
- [x I have updated relevant storybook stories and templates.
=> docs: storybook updates for icon sets, arrow and chevron

components/splitbutton/index.css, tools/component-builder/css/processors.js, tools/component-builder/package.json, yarn.lock
This plugin is no longer needed. It previously was adding support for logical properties when they were new to the CSS spec, but our dist CSS files are already making use of logical properties directly and not converting properties back to their non-logical alternatives.
This plugin affected the dist output of all un-migrated components still using `component-builder` rather than the newer `component-builder-simple`. It had replaced the use of logical properties with non-logical equivalents, for example creating additional style rules with `[dir="ltr"]` and `[dir="rtl"]` prepended, and replacing `min-inline-size` with `min-width`.
_Note: the difference in dist output can be compared locally be running `yarn compare` and clicking on each component._
Please tag yourself on the tests you've …
=> build: remove postcss-logical plugin

components/actionbar/metadata/actionbar.yml, components/modal/metadata/modal.yml, components/modal/stories/modal.stories.js
**docs(actionbar): change table example to demonstrate sticky variant**
The table example was no longer showing sticky behavior. Adjusts example to be similar to SWC. The Table component was causing problems in the build of this docs page and was missing CSS because it's not a dependency of action bar. This solves both issues.
**docs(modal): improve docs language around not using a modal**
Improves some slightly confusing and short docs text for Modal. Open to more suggestions here for those who may have some more context!
Validate:
2. If components have been modified, VRTs …
=> docs: actionbar example and modal docs text update

tokens/project.json
During development, the committed token assets sometimes revert to a compiled result without the -rgb postfixed properties. This is due to an issue with how caching is being handled. By removing caching from the tokens package, we can prevent bad dist results being generated for tokens.
To test this update, we run a collection of the commands and check each time that tokens output has not regressed. We expect after each command, there should be no tokens/dist results to be committed.
- `yarn build`, validate with `git status` (✅ @pfulton)
- `yarn start`, validate with `git status` (✅ @pfulton)
- `yarn build`, validate with `git status` (components should use the …
=> chore(tokens): inconsistent compilation results caused by caching

tools/component-builder/css/processors.js, tools/component-builder/package.json, yarn.lock
The postcss-svg plugin lets you inline svgs in CSS: https://www.npmjs.com/package/postcss-svg
As we aren't doing this anywhere, the plugin is going unused. Safe to remove!
Expect no regressions.
Validate:
=> fix(component-builder): remove unused postcss-svg plugin

.github/workflows/build.yml, .github/workflows/compare-results.yml, .github/workflows/lint.yml, .github/workflows/publish-site.yml, .github/workflows/vrt.yml
CI console is outputting warnings for each use of the actions/cache@v3 which is using a node 16 environment image. This PR updates our use to actions/cache@v4 which has been updated to node 20.
Expect to see no more warnings in the console and all CI tests to pass.
=> ci(actions): bump to v4, resolve outdated node messages

.storybook/README.md, .storybook/decorators/contextsWrapper.js, .storybook/decorators/index.js, .storybook/decorators/withTestingPreviewWrapper.js, .storybook/preview.js, components/accordion/stories/accordion.stories.js, components/alertbanner/stories/alertbanner.stories.js, components/calendar/stories/calendar.stories.js, components/calendar/stories/template.js, components/coachindicator/stories/coachindicator.stories.js, components/dropzone/stories/dropzone.stories.js, components/icon/stories/icon.stories.js, components/illustratedmessage/stories/illustratedmessage.stories.js, components/inlinealert/stories/inlinealert.stories.js, components/statuslight/stories/statuslight.stories.js, components/stepper/stories/stepper.stories.js, components/tray/stories/tray.stories.js
As we expand our Chromatic test coverage leveraging the `isChromatic` flag, there's a larger need to be able to preview the "kitchen sink" set-up without having to take a snapshot. Enter, the global "Testing preview" setting!
https://github.com/adobe/spectrum-css/assets/1840295/b9ec5c75-38f8-48bf-8335-935e61033118
With the global setting, you can activate "Testing preview" mode and see all storybook stories the way Chromatic will see them. It persists as you navigate through components until you deactivate it in the global toolbar.
Going forward, all use of the `isChromatic` function should be sourced from `window.isChromatic` rather than imported manually into each story.
Please tag yourself on the tests you've marked complete to confirm the tests have been run by someone other than the …
=> chore(storybook): allow local preview of chromatic snapshots

components/textfield/metadata/textarea.yml, components/textfield/metadata/textfield.yml
Adjusting the example text in the TextArea docs page to be more realistic for what the component is used for.
Validate:
=> docs(textarea): example text is more relevant to component

components/fieldlabel/index.css, components/fieldlabel/metadata/mods.md, components/fieldlabel/stories/form-template.js, components/picker/index.css, components/picker/stories/picker.stories.js, components/picker/stories/template.js
Addresses concerned raised in https://github.com/adobe/spectrum-web-components/issues/2963 where the quiet picker and it's associated side label does not align with text of other components, making it appear incorrect when used with other components.
For before look at https://github.com/adobe/spectrum-css/pull/2231
FieldLabel: 
- use `--spectrum-field-label-top-margin-*` tokens and margin to adjust position of side label to match design specs 
Picker
- Remove negative top margin from the quiet side label 
- Use correct tokens for picker side label margins 
- add displaying with the switch component to controls for picker storybook
On the docs site for picker and …
=> fix(picker): quiet side label picker positioning

.storybook/decorators/withTestingPreviewWrapper.js, .storybook/preview.js, components/calendar/stories/calendar.stories.js, components/calendar/stories/template.js
A flaw in the logic for determining a static "today" value for testing purposes was introduced in #2499. This fixes it!
Validate:
VRTs have been run on this branch:
=> chore(calendar): correct fallback date for testing

.github/workflows/lint.yml
=> revert: resolve reviewdog CI failures by using older version

components/slider/index.css
Filled sections of the track get the Highlight color when in high contrast mode to differentiate them from the rest of the track, which remains the ButtonText color (even on hover/focus/keyboard focus/active state). Slack receipts [in this thread](https://adobedesign.slack.com/archives/GQ09RCBA5/p1697227853534239).
Validate:
=> fix(slider): high contrast improvements for filled track

.github/workflows/build.yml, .github/workflows/compare-results.yml, .github/workflows/development.yml, .github/workflows/production.yml
Separate the build matrix testing from the CI workflows.
The macos environments build a minute or two slower than ubuntu. As the ubuntu environment is used for the rest of the CI workflow, it would speed up the overall run-time to allow these tasks to run separately.
(Note that Matrix: Compare & fetch are separate from Matrix: Verify)
=> ci: separate build matrix from workflow

.github/workflows/development.yml
When VRT was skipped, the storybook build was not being kicked off.  This attempts to fix that issue.
1. Add the `skip_vrt` label.
2. Check that the VRT run was skipped.
3. Check that the publish task runs the Storybook build.
4. Check that the storybook build is linked in the PR's published docs site.
=> ci: allow skip_vrt to build preview site

components/button/index.css, components/button/metadata/button-pending.yml, components/button/package.json, components/button/stories/button.stories.js, components/button/stories/template.js, components/progresscircle/stories/progresscircle.stories.js, components/progresscircle/stories/template.js
Add pending state variant to the existing button
- Outstanding design questions [and answers](https://adobedesign.slack.com/archives/G019JTYMT6H/p1705609053178079?thread_ts=1705006780.231489&cid=G019JTYMT6H):
Validate:
=> feat(button): pending state

components/combobox/stories/combobox.stories.js
Changes to combobox, including using `isChromatic()`, snuck in before the [local Chromatic preview PR](https://github.com/adobe/spectrum-css/pull/2499) was merged. This adjusts the combobox story to use the new setup.
Note that I've noticed sometimes Storybook shows a hooks error. That is a separate issue from this PR that Cassondra is taking a look at. If you run into it, refresh the page and you should be able to review.
Validate:
=> docs(combobox): update to use local chromatic preview

package.json, tools/bundle-builder/dev/index.js, tools/bundle-builder/docs/index.js, tools/bundle-builder/index.js, tools/bundle-builder/package.json
This update allows us to load CSS assets for packages that no longer live in the monorepo structure to maintain their rendering on the docs site even after deprecation.
- `index-vars.css`
- `index`
- `mods.json`
- `package.json`
- `vars.css`
Validate:
=> docs: allow loading assets from node_modules

README.md
Adds a section to the main project README that explains what browsers are currently supported by Spectrum CSS. IE11 is no longer supported and there was a 404 link to legacy IE11 support that needed to be removed.
=> docs: readme - clarify browser support and remove ie11 broken link

components/searchwithin/metadata/searchwithin.yml, components/searchwithin/stories/searchwithin.stories.js
Preparation for deprecating the searchwithin component
Check that the steps for [flagging a component as deprecated](https://github.com/adobe/spectrum-css/blob/main/.storybook/guides/deprecation.mdx#L29-L55) have been completed in this PR:
Validate:
=> chore(searchwithin): setup for deprecation

.storybook/guides/deprecation.mdx, components/cyclebutton/metadata/cyclebutton.yml, components/cyclebutton/stories/cyclebutton.stories.js
Preparation for deprecating the cyclebutton component. Includes a small change to docs to recommend markdown syntax for links instead of html (since markdown automatically handles links, vs needing to add classes when using html)
Check that the steps for [flagging a component as deprecated](https://github.com/adobe/spectrum-css/blob/main/.storybook/guides/deprecation.mdx#L29-L55) have been completed in this PR:
Validate:
=> docs(cyclebutton): setup for deprecation

components/textfield/index.css, components/textfield/stories/template.js
Previously some styles were adding a small amount of extra inline-start padding to the label and help text, when they are nested within Text field (as shown on the docs page for Text field). This was particularly noticeable on the quiet variation—see screenshot.
It looks like this previously was adding padding that matched the amount of corner rounding, so the label text would start where the corner started its curve.
On the design, there is no additional left padding. This update removes that padding to adhere to the design.
This also includes a small Storybook fix for the alignment of the valid checkmark. Due to recent Icon fixes, it was necessary to specify the icon set as "ui" in some of the args.
CSS-674
Please tag yourself on the tests you've marked complete to confirm the tests …
=> fix(textfield): remove extra padding on nested label and help

components/button/index.css, components/button/metadata/mods.md, components/button/package.json, components/button/stories/button.stories.js
This update allows text wrapping within the **Button** component and updates the alignment of the label and icon when wrapping to conform with the design specs.
- Fixes a previously introduced bug that disabled wrapping of lengthy text inside a Button. This removes the white-space property that prevented wrapping.
- BREAKING CHANGE: Updates styles so that buttons that contain a workflow icon have the correct icon and text alignment. Previously everything was vertically aligned center and the text was aligned center, which did not match the design in the case of wrapping text. See screenshots for reference to the design.
This is a significant change as the vertical flex alignment of the icon is now to the top/start instead of the center, and the design defined …
=> fix(button): support for wrapping text

components/tray/index.css, components/tray/metadata/mods.md, components/tray/metadata/tray.yml, components/tray/stories/template.js, components/tray/stories/tray.stories.js
The Tray was not appearing at the intended 100% width in portrait orientation because of a `max-inline-size` declaration coming from the `.spectrum-Modal` class used alongside `.spectrum-Tray`. This makes sure that the `max-inline-size` is 100%. 
This also:
- Adds a requested mod for rounding in portrait orientation:  `--mod-tray-corner-radius-portrait`. The landscape rounding can already be changed by `--mod-tray-corner-radius`.
- Cleans up some of the docs, including the guidelines link that was previously 404.
- forced-colors: Replaces an unknown system color with the one that is defined in the current spec.
- forced-colors: applies border to the correct element, so that rounded corners appear. Previously the border was on a nested element with padding around it, so the borders weren't …
=> fix(tray): full width at portrait orientation

tasks/clean-up-after-migration.sh
Currently, packages must be manually flagged for removal to prevent empty folders from breaking build scripts. This updates the clean-up script to remove any empty folder within components or plugins that doesn't contain a package.json. This is a solid indicator that a package was previously removed and can be safely deleted from the local repository.
=> chore: update clean-up script for more flexible removals

.github/workflows/development.yml, .github/workflows/production.yml
The optimal way to run VRT on a feature branch is to manually create a review. To support that, we need to prevent automated VRT from running on spectrum-two based PRs.
To validate this work, I'm going to create a fork branch off `spectrum-two` and copy this code into it. I'll open a PR against `spectrum-two` and see if it fires VRT. 
- https://github.com/adobe/spectrum-css/pull/2568
=> ci: remove spectrum-two from automated VRT runs

components/menu/index.css, components/menu/stories/menu.stories.js, components/menu/stories/template.js
Increased Storybook coverage for **Menu** and a fix for a color issue noticed when additional coverage was added.
- Updates two existing stories to include a disabled menu item with the Switch input.
- Updates disabled styles so that the value area text also appears with the disabled content color when the menu item is disabled. Confirmed on newer design spec.
Validate:
=> fix(menu): disabled color for value text and add disabled stories

.storybook/DocumentationTemplate.mdx, components/accordion/stories/accordion.stories.js, components/accordion/stories/template.js
A few changes to enhance the Accordion story:
- Moved the description to a [JSDoc comment](https://storybook.js.org/docs/api/doc-block-description#writing-descriptions) so it will show up in the autodocs
- Leverage practical real-world content (inspired by feedback Jess provided in a design meeting) by pulling an accordion example from the marketing site
- Move the items definition to the args to prevent duplication and simplify the template calls
- Update the import to use the package name instead of relative pathing, this will make our stories more portable
- Move disableAll usage out of the AccordionItem so that it is passed down and processed only by the parent
- Use an updateArgs from the parent via an onclick event to trigger the AccordionItem
Please tag yourself on the tests you've …
=> chore: minor accordion story updates

components/actionbutton/metadata/actionbutton.yml, components/actionbutton/metadata/mods.md, components/button/metadata/button-accent.yml, components/button/metadata/button-negative.yml, components/button/metadata/button-primary.yml, components/button/metadata/button-secondary.yml, components/button/metadata/button-staticcolor.yml, components/button/metadata/mods.md, components/closebutton/metadata/closebutton.yml, components/closebutton/metadata/mods.md, components/commons/basebutton.css, components/logicbutton/metadata/logicbutton.yml, components/logicbutton/metadata/mods.md, components/picker/metadata/mods.md, components/picker/metadata/picker.yml
Remove mod properties that were renamed and previously marked for deprecation, and regenerate the mods lists. This will help in reviewing the accuracy of other components' mods lists as they are being migrated to s2. Also updates some Close Button documentation.
Validate:
=> fix(commons): remove renamed mods marked for deprecation

.github/workflows/lint.yml
=> ci: revert faulty version of reviewdog action

components/button/index.css, components/button/metadata/button-pending.yml, components/button/stories/button.stories.js, components/button/stories/template.js, components/progresscircle/index.css, components/progresscircle/metadata/mods.md
This PR addresses [two issues SWC reported](https://adobedesign.slack.com/archives/G019JTYMT6H/p1708595849739049?thread_ts=1705006780.231489&cid=G019JTYMT6H) with Button's pending state:
- Button width was not being preserved when pending state was activated
- No animation/transition provided when going to pending state
Validate:
=> fix(button): pending state width, transition

components/tabs/index.css, components/tabs/metadata/mods.md
This PR fixes an issue a user reported in [Adobe Slack](https://adobedesign.slack.com/archives/C5N154FEY/p1710842359652389) that the `.spectrum-Tabs-itemLabel` had a typo in the mod for font-size. It was `--mod-tabs-font-weight`, but should be `--mod-tabs-font-size`.
In storybook with dev tools: @jawinn
=> fix(tabs): mod typo for font-size

components/button/stories/template.js
The pending icon was not appearing in the Button story titled "With Forced Colors". Updates a conditional in the template so the progress circle renders.
Validate:
1. If components have been modified, VRTs have been run on this branch:
=> docs(button): fix appearance of pending in forced colors story

.github/CONTRIBUTING.md, .github/QUICK-START.md, .storybook/guides/develop.mdx, README.md, site/get-started.pug
In an effort to create a single source of truth for our documentation and make it easier for users to get started working with Spectrum CSS, this work:
- Includes a Quick start guide in the readme, inspired by the tutorial that used to live in the docs site
- Removes said tutorial from the docs site and links to the quick start guide in the readme instead
- Removes contributing guidelines from the readme, which are replaced with a link to the contributing doc in github
- Storybook contributing docs link to the more general contributing docs in github
- General updates to readme language
=> docs: update + centralize project docs

.storybook/foundations/corner-rounding/action-button-corner-rounding.stories.js, .storybook/foundations/corner-rounding/checkbox-corner-rounding.stories.js, .storybook/foundations/corner-rounding/component-size-tokens-medium.md, .storybook/foundations/corner-rounding/component-size-tokens-small.md, .storybook/foundations/corner-rounding/corner-rounding.mdx, .storybook/foundations/corner-rounding/corner-rounding.stories.js, .storybook/foundations/corner-rounding/index.css, .storybook/foundations/corner-rounding/template.js, components/actionbutton/index.css, components/checkbox/index.css, components/closebutton/index.css
S2 migration work for corner rounding tokens. Includes:
- Foundations page for documenting corner rounding as a concept for consumers (according to direction from this Slack thread https://adobedesign.slack.com/archives/G019JTYMT6H/p1708721169366349)
- Checkbox, action button component changes to partially migrate to only include new corner rounding
- Close button update to use the new custom token from #2597 
[Jenn's code pen](https://codepen.io/forthewinn/pen/zYbLGmp) that shows why this is needed for posterity)
=> feat(cornerrounding): add custom token and foundations documentation

.storybook/main.js
This changes a [Storybook core configuration option](https://storybook.js.org/docs/api/main-config-core#disablewhatsnewnotifications) to prevent the intrusive "What's new in..." Storybook popup from appearing whenever Storybook is run. Previously this would appear every time when running `yarn start` locally:
=> feat: storybook - disable whats new notification popup

tokens/custom-spectrum/custom-large-vars.css, tokens/custom-spectrum/custom-medium-vars.css, tokens/dist/css/spectrum/custom-large-vars.css, tokens/dist/css/spectrum/custom-medium-vars.css, tokens/dist/index.css
**Removes unused custom variables for edge-to-visual-only and chevron size**
These custom vars are no longer referenced anywhere in the repo:
- `--spectrum-edge-to-visual-only-75`
- `--spectrum-edge-to-visual-only-100`
- `--spectrum-edge-to-visual-only-200`
- `--spectrum-edge-to-visual-only-300`
- `--spectrum-icon-chevron-size-50`
In the removed comment above these edge-to-visual-only tokens, it mentioned that this was for the icon only button. The icon only button currently uses other existing tokens (e.g. `component-pill-edge-to-visual-only-*`).
The chevron custom variable has already been replaced by an existing token, that has the same values:
`--spectrum-chevron-icon-size-50`
Please tag yourself on the tests you've marked complete to confirm the tests have been run by someone other …
=> refactor(tokens): remove some unused custom variables

components/card/index.css, components/card/metadata/mods.md
fix(card): rename misnamed instance of background color mod
The custom mod property for the background color was named incorrectly in one of the declarations.
This mod renaming was made in the reverted PR #2417 , which had some issues with the Horizontal variant. This does an additional bit of refactoring cleanup to address this:
refactor(card): cleanup mods and vars around use of preview bg
The custom properties and mods were not differentiating between the card background and the preview div background used in the quiet, gallery, and horizontal variations. This did not work well with the horizontal variant which has both a card background and a preview background, when some of the mis-named mods were fixed.
A few unset custom properties with spectrum prefixed naming also appeared to be …
=> refactor(card): rename mod and refactor some usage of mods and vars

.github/workflows/development.yml
In this [PR](https://github.com/adobe/spectrum-css/pull/2617), I noticed that the base branch being used by the compare tool was main and not spectrum-two as expected. When I investigated further, I found in [the logs](https://github.com/adobe/spectrum-css/actions/runs/8483292394/job/23244124885) that it was using the default base branch rather than the base branch for the PR. To fix this, I've added a get-SHAs workflow that will fetch and pass the appropriate SHA values to the compare script.
=> ci: ensure the shas used by compare match the current PR

components/actionbutton/package.json, components/button/package.json, components/closebutton/package.json, components/commons/package.json, components/modal/package.json, components/popover/package.json, components/tooltip/package.json, components/underlay/package.json
The commons package is at 9.1.3 on npm but 9.1.2 in the project. Updating versions locally to align with npm.
Expect no changes.
Validate:
=> chore: align commons version with npm

components/logicbutton/package.json, components/picker/package.json
Add missing devDependency @spectrum-css/commons to logicbutton and picker.
Should see no changes or regressions.
Validate:
=> fix(logicbutton,picker): add missing commons devDep

.github/workflows/development.yml, .github/workflows/production.yml, .github/workflows/publish-site.yml, .github/workflows/vrt.yml
When VRT is skipped, Chromatic is returning "undefined" as the value of storybook-url. This needs to be an empty string in order to trigger the local CI build.
This also corrects the SHAs being used - NX was not providing the correct base and head SHAs so this moves those to using the ones provided in the pull_request event.
=> ci: base and head ref fix

components/logicbutton/package.json, components/picker/package.json
During rebase, the picker and logicbutton commons packages got out of sync with the version of commons on the branch. This re-aligns those versions.
=> chore(logicbutton,picker): align commons package

components/actionbutton/metadata/actionbutton.yml, components/buttongroup/metadata/buttongroup.yml, components/closebutton/metadata/closebutton.yml, components/fieldlabel/metadata/fieldlabel.yml, components/fieldlabel/metadata/form.yml, components/logicbutton/metadata/logicbutton.yml, components/picker/metadata/picker.yml
Remove dates from in front of version numbers on migration guides (recently added), as we're adjusting to this format with just the version number going forward. Includes removal of the placeholder "x/x/2024" dates that were added. The button component was excluded from this update as they're already removed in the button S2 migration PR.
=> docs: update migration guide headings to remove dates

.eslintignore, .eslintrc, .gitignore, .prettierignore, .stylelintignore, nx.json, package.json, plugins/stylelint-no-missing-var/index.js, plugins/stylelint-no-missing-var/project.json, plugins/stylelint-no-missing-var/test.js, plugins/stylelint-no-unknown-custom-properties/index.js, plugins/stylelint-no-unknown-custom-properties/project.json, plugins/stylelint-no-unknown-custom-properties/test.js, plugins/stylelint-no-unused-custom-properties/expected/unused.css, plugins/stylelint-no-unused-custom-properties/expected/varRefs.css, plugins/stylelint-no-unused-custom-properties/index.js, plugins/stylelint-no-unused-custom-properties/project.json, plugins/stylelint-no-unused-custom-properties/test.js, yarn.lock
Set up a more detailed JS-linter with support for JSON assets with a structured formatting order to reduce unnecessary re-ordering diffs in PRs.
Improve the prettier, stylelint, and eslint ignore rules for wider coverage.
Add lint assets to the nx dependency inputs to ensure accurate caching when changes are made to supporting configurations.
Add lint fixing to the lint-staged workflow.
Apply linting updates to the plugins and support the lint and format commands for them as well.
Do not commit the changes from the below tests:
=> build: hardening linter settings

.storybook/assets/base.css, .storybook/decorators/contextsWrapper.js, components/closebutton/stories/closebutton.stories.js, components/fieldlabel/stories/fieldlabel.stories.js, components/fieldlabel/stories/template.js
Adds new gradient backgrounds to Storybook, that are displayed for static black and static white variants. These are used for examples only. This adds CSS custom properties available globally within Storybook and sets them on the existing decorator.
Validate:
=> feat: add example gradients for static black and white

components/card/index.css
Adds overflow hidden to the .spectrum-Card-coverPhoto class, to help resolve an issue in the SWC implementation that uses sp-asset.
In SWC the photo could appear from behind the corners of the card. For example, when increasing the corner rounding when setting the mod --mod-card-corner-radius. This issue is not visible in Spectrum CSS. This overflow property used to exist in SWC as a CSS override, but is preferred to exist here in CSS.
**Example of the issue in SWC:** 
Set `--mod-card-corner-radius: 24px` on the sp-card in the [first example on the SWC docs site](https://opensource.adobe.com/spectrum-web-components/components/card/):
Setting `overflow: hidden` on the `#cover-photo` selector via the inspector fixes the issue. The spectrum-config in SWC converts our class to that ID …
=> feat(card): overflow hidden on cover photo for swc implementation

.eslintrc
Adjusts eslint config to have the case statements indented from "switch". The default was zero, which has the "switch" at the same indentation level as "case".
=> style: adjust eslint config to have indented case statements

components/checkbox/stories/template.js, components/fieldlabel/stories/template.js, components/icon/stories/template.js, components/inlinealert/stories/template.js, components/menu/stories/template.js, components/picker/stories/template.js, components/progresscircle/stories/template.js, components/stepper/stories/template.js, nx.json
In a previous PR, the switch case indent rules were not being applied when running the `yarn format` command. Upon investigation, we found that the `|| exit 0` at the end of the command for eslint was causing the command not to run. I removed this line and successfully ran the formatter on files with the old switch syntax.
=> chore: fix eslint formatting command

.storybook/decorators/index.js
This PR removes the Storybook "r" and "n" key shortcuts for the text direction toolbar control.
When pressing the "r" or "n" key, the document direction would change due to this custom keydown code. This was causing problems such as typing into a text input and the document direction would flip if you typed anything with the letter "r". This also conflicted with other shortcuts, such as Cmd+Shift+R to reload the page.
CSS-647
Validate:
=> fix: remove custom storybook keyboard shortcuts for text direction

.storybook/decorators/contextsWrapper.js, components/button/stories/template.js, components/progresscircle/stories/progresscircle.stories.js, components/progresscircle/stories/template.js
Leveraging the story's id context in order to attempt to more accurately apply a story's individual contexts. In addition, this update uses querySelectors to determine if a context includes static(Black|White) or overBackground classes in it's content and applies the styles based on those settings.
Validate:
=> chore: storybook context application

.storybook/deprecated/cyclebutton/cyclebutton.stories.js, .storybook/deprecated/quickaction/quickaction.stories.js, .storybook/deprecated/searchwithin/searchwithin.stories.js, .storybook/deprecated/splitbutton/splitbutton.stories.js, .storybook/main.js, .storybook/preview.js
This PR pulls in deprecation notices to Storybook for the components and adds support for mdx files in components and deprecated folders in order to open support for alternative docs pages.
Validate:
=> chore: add deprecation notes to storybook docs; support mdx assets for components

.changeset/kind-mangos-jam.md, components/tooltip/index.css, components/tooltip/metadata/tooltip.yml, components/tooltip/stories/tooltip.stories.js
This PR aims to address issue #2707 by adjusting the left and right positions of the Tooltip for RTL. Also included is an updated Chromatic kitchen sink story to increase VRT coverage.
Validate:
=> fix(tooltip): rtl places tip in correct position

.changeset/proud-jokes-rule.md, .storybook/decorators/contextsWrapper.js, components/progressbar/index.css, components/progressbar/metadata/progressbar.yml, components/progressbar/package.json, components/progressbar/stories/progressbar.stories.js, components/progressbar/stories/template.js, yarn.lock
Migrates Progress Bar to Spectrum 2 ([design spec](https://www.figma.com/file/eoZHKJH9a3LJkHYCGt60Vb/S2-token-specs?type=design&node-id=9602-4210&mode=design&t=dE1k2G9oVanenmOD-0)). Includes:
- Updated font sizes
- Updated colors
- WHCM improvement for Static White variant
- Increased Chromatic coverage
- Consolidation of Storybook stories (only Default now and users can use controls to see other variants/states)
- No mods were changed
@jawinn 
Validate:
=> feat(progressbar): s2 migration

.changeset/eight-spiders-help.md, postcss.config.js
A change in the build configuration had resulted in some regressions due to increased specificity created in the dist output of `:not` selectors. One issue was with a disabled Menu item showing a change in icon color on hover.
The postcss-preset-env config override being removed here sets it to the default stage 2 configuration that allows multiple comma separated selectors within `:not()`. The configuration had been using a polyfill that converted each item in the `:not` selector list into its own `:not` selector, increasing specificity for the rule for each additional item.
Example:
Selector in dist CSS before this change: 
`.spectrum-Menu-item:hover > .spectrum-Menu-itemIcon:not(.spectrum-Menu-chevron):not(.spectrum-Menu-checkmark)`
Selector in dist CSS after this change (and that was …
=> build: keep selector list in dist output of not pseudo-class

.changeset/new-sheep-bathe.md, components/datepicker/index.css, components/datepicker/metadata/mods.md, components/progressbar/stories/meter.template.js, components/radio/index.css, components/slider/index.css, components/slider/metadata/mods.md, components/splitview/index.css, components/splitview/metadata/mods.md, components/treeview/index.css, components/well/index.css, components/well/metadata/mods.md
Sets the `color` property in parts of some components that were relying on inheriting a color from higher up in the DOM. These affected components were noticed in VRTs during the work to create a single entry point for PostCSS. The following has been updated:
- **datepicker**: color added to the dash between dates in the "Range" variant. Adds a new property and mod.
- **splitview**: default body color added for its contents. Adds a new mod.
- **treeview**: section heading set to `spectrum-heading-color` token per design guidance. Adds a new property.
- **slider**: sets the missing color on the tick labels (appearing under each tick). Adds a new property and mod.
- **radio**: read-only variant now sets the color (same as label color) instead of inheriting.
- **well**: default body color …
=> feat: define missing color property in some components

lint-staged.config.js, nx.json
When running the format command, a notice would show up in the console log noting that the flag should be `log-level` and not `loglevel`. This PR corrects that typo.
=> chore: fix loglevel error message when running prettier commands

.storybook/project.json, nx.json, package.json, site/package.json, site/project.json, yarn.lock
- Add the guides folder to the storybook dependencies and include mdx assets as well
- Use a shared list of storybook dependencies called "tools" instead of redefining them in every tasks inputs
- Remove the manual ui-icons build task from the storybook build and start tasks and the site build task
- Remove the manual token build from the shared build task
- Add ui-icons to the default yarn builder and leverage the shared build task in subsequent commands
Validate:
=> chore: minor fixes in build workflow and package alignment

.changeset/tidy-olives-notice.md, components/popover/index.css
Fix for issue #2705. Previously, there were duplicate class selectors in dist. This update adjusts the selectors to remove the duplicates.
=> fix(popover): no more duplicate class selectors in dist

.changeset/slimy-donkeys-roll.md, .storybook/package.json, site/package.json, yarn.lock
Current build is failing because the documentation and storybook packages are bringing in the external @spectrum-css/tokens 14.0.0 rather than using the local 14.1.0 version. These version bumps were missed in the chromatic release. In order to prevent that issue in future, this updates those packages to use the `workspace:^` version instead.
Validate:
=> chore: use local workspace package to prevent version mismatch

.changeset/lazy-rivers-leave.md, components/textfield/index.css
Fixes an issue specifically for the Quiet variant where hovering over the focus pseudo element triggers the hover event, which causes the hover event to flicker if the user hovers over the focus, then the space between the focus (which doesn't have pointer events and turns off the hover effect), then onto the textfield (which does have pointer events and the hover effect).
See Josh's helpful screen capture for an example of the issue this fixes: 
https://github.com/adobe/spectrum-css/assets/23404383/148fee9f-1077-49c5-93c2-7acaeac23d8d
- Open the Quiet, keyboard-focused textfield in [Storybook](https://pr-2761--spectrum-css.netlify.app/preview/?path=/story/components …
=> fix(textfield): no pointer events for focus pseudo element

.changeset/brave-seas-retire.md, components/alertbanner/index.css, components/alertbanner/metadata/mods.md
The alert banner now occupies all available space until it reaches the maximum allowed width. By default it will no longer cut off in viewports smaller than the width token.
The token `--spectrum-alert-banner-width` was previously used as the width, as it was shown in the design specs. Per a discussion with design, this had been intended as a max width, to prevent having alert banners that are too wide and hard to read. That token is now used for `max-inline-size` and the `inline-size` is set to `auto`.
Includes addition of a new mod custom property: `--mod-alert-banner-max-inline-size`
Resolves #2715 
CSS-748
Validate:
1. The documentation pages for at least two …
=> feat(alertbanner): use width token for max-width instead of width

.storybook/guides/develop.mdx, .storybook/manager.js, components/accordion/stories/accordion.mdx, components/accordion/stories/accordion.stories.js, components/actionbar/stories/actionbar.mdx, components/actionbar/stories/actionbar.stories.js, components/actionmenu/stories/actionmenu.stories.js, components/alertdialog/stories/alertdialog.mdx, components/alertdialog/stories/alertdialog.stories.js, components/alertdialog/stories/template.js
- Accordion - got a new MDX page and some MDX-only stories
- Actionbar - got a new MDX page and one MDX-only story
- Actionmenu - doesn't require it's own MDX page since the DocumentationTemplate already covers the only variant, so just got an update to the description to include some additional details from the docs site.
- Alertdialog - got a new MDX page and one MDX-only story. Also got a small update to the template.js so that I could pass a custom height for the scroll story example
Also includes an addition to the storybook/manager.js to hide stories from the sidebar that have the tag `is-hidden-story`.
This PR shouldn't need a changeset since …
=> docs(accordion,actionbar,actionmenu,alertdialog): site docs to storybook

.changeset/neat-windows-yawn.md, components/radio/index.css, components/slider/index.css
Per issue #2703 and #2704, some parsers see `:pseudo:dir` as invalid, so we've changed it so that the pseudo element comes last `:dir :pseudo`. 
Before, the dist output was:
```
.spectrum-Slider-handle:before:dir(rtl),
[dir="rtl"] .spectrum-Slider-handle:before
.spectrum-Radio-button:after:dir(rtl),
[dir="rtl"] .spectrum-Radio-button:after
```
After, with this improvement, the dist output is:
```
.spectrum-Slider:dir(rtl) .spectrum-Slider-handle:before,
[dir="rtl"] .spectrum-Slider .spectrum-Slider-handle:before {
transform: translate(50%, -50%);
}
.spectrum-Radio:dir(rtl) .spectrum-Radio-button:after,
[dir="rtl"] .spectrum-Radio .spectrum-Radio-button:after {
transform: translateX(50%) translateY(-50%);
}
```
Please tag yourself on the tests you've marked complete to confirm the tests …
=> fix(slider,radio): dir before pseudo element

.changeset/three-geese-relax.md, components/popover/index.css, components/popover/stories/popover.stories.js, components/popover/stories/template.js
Fixes an issue in Popover where Left and Right tips were mirrored incorrectly for RTL. This is simliar to some [work done on Tooltip](https://github.com/adobe/spectrum-css/pull/2736). Note that the Left and Right placement for the tips are always on the LTR left and right, even if RTL is turned on. Start and End, however, are adjusted based on the text direction.
Also included Storybook enhancements including:
- Show all placement options (previously Start and End placements weren't included in the Storybook controls)
- Increase Chromatic VRT coverage for the tip variant
Validate:
1. The documentation pages for at least two other components are still loading, …
=> fix(popover): correct left/right tips for RTL, increase VRT coverage

components/asset/stories/asset.mdx, components/asset/stories/asset.stories.js, components/assetcard/stories/assetcard.mdx, components/avatar/stories/avatar.mdx, components/avatar/stories/avatar.stories.js, components/badge/stories/badge.mdx, components/badge/stories/badge.stories.js
- Asset - got a new MDX page and some MDX-only stories
- Assetcard - got a new MDX page but was able to use existing stories
- Assetlist - no changes required since this one already matches the docs site as is
- Avatar - got a new MDX page and some MDX-only stories
- Badge - got a new MDX page and some MDX-only stories
This PR doesn't need a changeset since it's docs-only.
Validate:
2. If components have been modified, VRTs have been run …
=> docs(asset,assetcard,avatar,badge): site docs to storybook 

components/colorhandle/stories/colorhandle.mdx, components/colorhandle/stories/colorhandle.stories.js, components/colorhandle/stories/template.js, components/colorloupe/stories/colorloupe.mdx, components/colorslider/stories/colorslider.mdx, components/colorwheel/stories/colorwheel.mdx, components/colorwheel/stories/colorwheel.stories.js, components/colorwheel/stories/template.js
Note that some of the docs site examples show implementation of combinations of the color components (colorhandle using colorloupe for example). I didn't include these examples in Storybook, but did include documentation about what's required when using components together at the implementation level.
- Colorhandle - got a new MDX page and one MDX-only story
- Colorloupe - MDX page wasn't required but got some usage notes added to the storybook description
- Colorslider - got a new MDX page and usage notes added to the storybook description
- Colorwheel - got a new MDX page, usage notes in the storybook description, and one MDX-only story
This PR …
=> docs(colorhandle,colorloupe,colorslider,colorwheel): site docs to storybook

components/asset/stories/template.js, components/calendar/stories/calendar.mdx, components/calendar/stories/calendar.stories.js, components/calendar/stories/template.js, components/card/stories/card.mdx, components/card/stories/card.stories.js, components/card/stories/template.js, components/coachmark/stories/coachmark.mdx, components/coachmark/stories/coachmark.stories.js, components/coachmark/stories/template.js, components/colorarea/stories/colorarea.mdx, components/colorarea/stories/colorarea.stories.js
- Calendar - got a new MDX page and one MDX-only story
- Card - got a new MDX page and some MDX-only stories
- Coachmark - got a new MDX page and some extra parameters to make sure "with media" variant shows whole component on Docs page
- Colorarea - got a new MDX page and one MDX-only story
This PR doesn't need a changeset since it's docs-only.
Validate:
=> docs(calendar,card,coachmark,colorarea): site docs to storybook

.changeset/eight-crabs-smile.md, components/slider/index.css
Updates the Slider high contrast styles to use all `--highcontrast` prefixed custom properties. It was noticed that some were being set with `--spectrum` prefixed custom properties. Some were duplicative, as they already had `--highcontrast` prefixed custom properties being set (which take precendence in the `var()` fallback chains). A few needed a rename.
In the process, it was also found that the ramp variant was missing the handle outer circle (gap between the ramp background and handle), that created contrast between the handle in the background. This was particularly noticeable on hover/active, as the handle was blending into the same ramp highlight color. The fix was already present but the nested `.spectrum-Slider--ramp` selector was missing an `&` to make it the same element as …
=> fix(slider): use high contrast properties and fix ramp handle circle

.changeset/fresh-seahorses-join.md, components/button/index.css, components/button/metadata/mods.md
**refactor: remove spectrum-ButtonWithFocusRing placeholder class** `extend` from the button component
Removes the need for the `extend` from this placeholder class in the button component, as the styles it provides have diverged slightly from what is in button and it was causing some unnecessary CSS to override. This should not result in any changed visuals or behavior, as the same CSS has been integrated.
Validate:
=> refactor(button): remove spectrum-ButtonWithFocusRing extend

components/combobox/CHANGELOG.md, components/combobox/stories/combobox.mdx, components/combobox/stories/combobox.stories.js, components/contextualhelp/stories/contextualhelp.mdx, components/contextualhelp/stories/contextualhelp.stories.js, components/datepicker/CHANGELOG.md, components/datepicker/stories/datepicker.mdx, components/datepicker/stories/datepicker.stories.js, components/datepicker/stories/template.js
Combobox, Contextual help, and Date picker all got new MDX pages and some MDX-only stories.
This PR doesn't need a changeset since it's docs-only.
- Note that these MDX previews look a bit big, but it's to accommodate the edge case of someone expanding the datepicker so they can see the whole thing
Validate:
=> docs(combobox,contextualhelp,datepicker): site docs to storybook

.storybook/guides/develop.mdx, components/button/stories/button.stories.js, components/button/stories/template.js, components/icon/stories/icon.stories.js, components/picker/stories/picker.stories.js, components/picker/stories/template.js, components/rating/stories/rating.stories.js, components/rating/stories/template.js
Express styles are loaded into Storybook from the index.css export and toggled through the .spectrum--express class.  The themes/express.css assets do not need to be imported at the template level (this is a duplicate action).
=> chore: remove duplicate express import from templates

.storybook/foundations/drop-shadow/drop-shadow.mdx, .storybook/foundations/drop-shadow/drop-shadow.stories.js, .storybook/foundations/drop-shadow/index.css
- Adds Storybook documentation (including code snippets and light/dark mode swatches) for Drop Shadow under the Foundations section
CSS-740
Validate:
=> feat(dropshadow): add dropshadow foundation

.changeset/sixty-pandas-impress.md, components/picker/index.css
**Picker**: The following states were showing a change of colors when they shouldn't:
- Disabled + hover
- Disabled + invalid + hover
- Disabled + open
- Disabled + open + hover
This was caused by a few different issues. One is that that the `.spectrum-Picker:hover` styles are being moved farther down in the built dist file, as part of the hover media query from the postcss-hover-media-feature plugin. The hover styles with the same specificity as the disabled styles were then later in the order than intended and overriding the disabled styles. The other is that the `.is-open` styles had a higher specificity than some of the disabled styles.
This also removes an unused variable flagged by the linter, `--spectrum-picker-spacing-top-to-text-side-label-quiet`. This was used nowhere in the …
=> fix(picker): correct disabled state colors

components/icon/stories/icon.mdx, components/icon/stories/icon.stories.js
Creates an MDX documentation page for the Icon component. Icon previously did not have a page on the docs site. This documentation covers some of the important info uncovered during some of the more recent icons work. It helps to explain the different icon sets, how they are used, and how they are sized differently.
CSS-671
CSS-759
_Note: a changeset should not be required, as this is a docs only update._
N/A for this PR.
=> docs(icon): storybook documentation page

.changeset/thin-jeans-wink.md, postcss.config.js
Set [`reduceIdents`](https://www.npmjs.com/package/postcss-reduce-idents) to false for cssnano minification as the grid-template-area and keyframe magnifications were causing mismatches in the resulting code.
Validate:
The pages render correctly, are accessible, and are responsive.
=> fix: remove abstractions from build process for grid and keyframe

.storybook/DocumentationTemplate.mdx, .storybook/assets/base.css, components/dropzone/stories/dropzone.stories.js, components/dropzone/stories/template.js, components/fieldgroup/stories/fieldgroup.mdx, components/fieldgroup/stories/fieldgroup.stories.js, components/fieldgroup/stories/template.js, components/floatingactionbutton/stories/floatingactionbutton.stories.js, components/illustratedmessage/stories/illustratedmessage.stories.js, components/infieldbutton/stories/infieldbutton.stories.js, components/infieldbutton/stories/template.js, components/radio/stories/template.js
This continues the migration work to move the documentation from the deprecated docs site to Storybook, covering components drop zone, field group, floating action button, illustrated message, and infield button. Variants shown on the docs site for these components have been added to Storybook if they did not already exist.
An MDX page was only created if the existing documentation template could not support displaying information in a manner consistent with the docs site. In this PR, the only component that received an MDX page was field group, because its variants encompass both checkbox groups and radio groups and organizing these stories to be displayed side-by-side felt more logical.
Since we anticipate that some components will use their own MDX docs page and others will use the …
=> docs(dropzone,fieldgroup,floatingactionbutton,illustratedmessage,infieldbutton): site docs to Storybook

.changeset/tidy-balloons-cover.md, components/accordion/index.css, components/commons/basebutton.css, components/statuslight/index.css, components/textfield/index.css
In this work I searched for all uses of `-webkit-*`, `-moz-*`, and `-ms-*` prefixed properties in the repo, to find any cases where we no longer need them. I discovered a few that could be removed, and some tied to normalization styles that needed some cleanup and clarification.
The `appearance` property no longer needs vendor prefixes. Any necessary vendor prefixes for supported browsers would be added in the build process (none are added for our current browser support list).
Removed the legacy `-ms-high-contrast-adjust` property. This CSS property was removed from Microsoft Edge starting with version 79 (when Edge started using Chromium). Our current browser support list does not support Edge versions before that.
This also moves the high contrast mode properties to the bottom of the …
=> feat: cleanup legacy vendor prefixes and normalization

components/dialog/metadata/dialog.yml, components/site/component.css
Currently on the [static docs site](https://opensource.adobe.com/spectrum-css/dialog.html), the dialogs don't really function properly (the default dialog does however, work properly in [Storybook](https://opensource.adobe.com/spectrum-css/preview/?path=/docs/components-dialog--docs). If you close any open dialog variant, and try to reopen it, it is "stuck" underneath `spectrum-Underlay`. I believe this is because a `z-index: 1 !important` is overriding other `z-index: 2`s for `spectrum-Modal`. 
This PR adds a new `.spectrum-CSSExample-modal` class to mimic `.spectrum-Modal-wrapper` with a `z-index` that should position it above `.spectrum-Underlay`. It also adds/removes classes in `dialog.yml` to better implement the open/close behaviors. 
**Note:** The hero, no-divider, and dismissible …
=> chore(dialog): z-index for dialog docs

.changeset/modern-ladybugs-wash.md, components/breadcrumb/index.css, components/breadcrumb/stories/template.js
Disabled breadcrumbs (except for action buttons) in storybook still had pointer events, hover and focus styles. There was no indication that a text-based breadcrumb was disabled. This was partially because the `tabindex` was being set to `0`, which then was adding specific styles. Additionally, the `is-disabled` class was not being added to the proper `.spectrum-Breadcrumb-itemLink` element. This PR should address these a11y concerns and disabled bugs.
@jawinn 
Validate:
=> fix(breadcrumb): disabled behaviors and styles

components/dialog/metadata/dialog.yml, components/dialog/package.json, yarn.lock
Currently on the [static docs site](https://opensource.adobe.com/spectrum-css/dialog.html), the dialogs don't really follow the guidelines and documentation according to the [internal/beta site](https://spectrum-contributions.corp.adobe.com/page/standard-dialog-beta/#Dismissible): 
> When not dismissible, the dialog needs to have one or more buttons in the footer for users to perform an action (including closing the dialog) and the background overlay cannot be clicked.
This PR implements the missing button groups on non-dismissible dialogs on the docs page. It also adds/removes classes in `dialog.yml` to implement the button groups.
[CSS-815](https://jira.corp.adobe.com/browse/CSS-815) 
Please tag yourself on the tests you've marked complete to confirm the tests have been run by someone …
=> fix(dialog): implement dialog button groups

.changeset/dull-coats-pull.md, .storybook/main.js
Add a look-through to the Spectrum Web Components Storybook project to create an easier connection between components that exist in CSS and those in SWC.
=> feat(storybook): add the swc preview

.storybook/assets/base.css
Adds some CSS to Storybook to adjust inline stories on the Docs pages. This stops them from cutting off content, by adjusting the overflow property. This was affecting components such as in-field button, color loupe, etc.
The display difference between regular stories and inline stories is because [Storybook sets an inline style with `overflow: auto` in its InlineStory function](https://github.com/storybookjs/storybook/blob/535f7b9ba3849719e10e4b577f78660b77cdcaec/code/ui/blocks/src/components/Story.tsx#L80C63-L80C74). This appears to be originally added in Storybook 6.1 to help fixed elements from leaking out; that does not appear to be an issue with our fixed elements after this fix (is it possibly not an issue anymore in Storybook due to other changes?).
CSS-816
Please tag yourself on …
=> fix(storybook): some inline stories in docs cutting off

.changeset/nasty-moose-act.md, components/picker/index.css, components/picker/stories/picker.stories.js
Addressing [CSS-810](https://jira.corp.adobe.com/browse/CSS-810), this fix addresses [a bug that was called out recently](https://adobedesign.slack.com/archives/CESK60MQD/p1718744842850969), similar to what was seen in Textfield for both [Spectrum CSS](https://github.com/adobe/spectrum-css/pull/2123) and [React Spectrum](https://github.com/adobe/react-spectrum/pull/4579) with text with diacritics being cut off vertically. In this case, as the affected text occurs in a `<span>` rather than an `<input>` tag, the line-height does not need an adjustment, and changing the margin to padding appears to be sufficient to allow the vertical cutoff to be displayed.
There is also a [draft PR](https://github.com/adobe/spectrum-css/pull/2913) to fix the same issue that uses the same line-height fix …
=> fix(picker): prevent diacritic text cutoff

.husky/commit-msg, .husky/pre-commit
When running a clean install, husky is updating our  commit message and pre commit scripts to remove the bash headers.
You can recreate this change with the following steps:
```
git clean -dfX
yarn install
```
=> chore: husky script changes on install

.storybook/main.js, .storybook/project.json
This PR fixes the port to 8080 to make rebuilds easier to navigate.
=> chore(storybook): update fixed port to 8080

tasks/component-builder.js
After adding `@spectrum-css/typography` imports to Storybook, we started seeing:
```
Error: An error occurred while trying to read the map file at components/typography/index.css.map
Error: ENOENT: no such file or directory, open '/Users/carobert/Projects/spectrum/spectrum-css/components/typography/dist/components/typography/index.css.map'
```
in the console which reflects an invalid path being used in the sourcemap files generated by the component-builder. This fix improves the path generated and removes the error messaging from our Storybook build.
1. Do a clean local build (storybook symlinks to local dist); `yarn build`.
2. Kick off the storybook server: `yarn …
=> chore(build): add additional metadata for mapping to improve map paths

.storybook/decorators/icon-sprites.js, .storybook/decorators/index.js, .storybook/loaders/icon-loader.js, .storybook/loaders/index.js, .storybook/preview.js
Icon sprite loading was hardcoded into the `.storybook/preview.js` file rather than imported as part of the decorators and loaders infrastructure. This cleans that up.
Please tag yourself on the tests you've marked complete to confirm the tests have been run by someone other than the author. No change to how the decorator or loaders work, just a shift in how they're imported.
Validate:
=> chore(storybook): organize icon loader into tooling

.github/workflows/lint.yml, .storybook/project.json, nx.json, package.json, site/project.json, tokens/project.json, ui-icons/project.json
With the update of our stylelint tooling to v16, we are seeing deprecations notices in our build tasks because postcss is running stylelint in a CJS script.  This update suppresses the node warnings for the console using `--no-warnings`.
This PR also updates our linting GitHub packages to their latest versions.
A side-effect of updating the *.json files is that the linter sorted the keys.
To ensure your run goes without referencing the build cache, start by running `nx cache`.
=> chore(build): update component builder to use modules; suppresses stylelint notice on build

components/checkbox/index.css, components/dial/index.css, components/slider/index.css
Adds some comments to clarify existing CSS that uses a low opacity (0.0001 and 0.000001) for visually hidden inputs. And explains why they are hidden this way with sizing and positioning for touch users, instead of using a screenreader only (.sr-only) technique.
**Reference info:**
- [Inclusively Hiding & Styling Checkboxes and Radio Buttons: Hiding the checkboxes inclusively](https://www.sarasoueidan.com/blog/inclusively-hiding-and-styling-checkboxes-and-radio-buttons/#:~:text=navigating%20by%20touch.-,Hiding%20the%20checkboxes%20inclusively,-Touch%20interface%20screen) (2020)  - Why this technique appears to be used and why a visually-hidden or sr-only class would not be an improvement over the current way that these inputs are hidden.
- [Inclusive Considerations When Restyling Form …
=> docs: clarify usage of very low opacity on some inputs

.github/workflows/lint.yml, nx.json
A hanging `stylelint.config.mjs` was left over in nx.json and the lint workflow from when I attempted to support mixed ESM and CJS in the monorepo for the stylelint migration to v16.  This removes those and ensures they are pointing to the `stylelint.config.js` file.
- [n/a] If my change impacts **documentation**, I have updated the documentation accordingly.
=> chore: fix stylelint extension error

.changeset/pretty-socks-notice.md, components/swatch/index.css, components/swatch/metadata/mods.md
During the documentation migration work in #2925, it was noticed that the "light border" variant didn't have corresponding CSS. After some digging, I found that we did support it at one point, but it may have accidentally gotten deleted. When reading the Slack messages linked in #1501, it sounds like a light border variant should have been supported, but I believe that was one of the "open questions" related to that PR. This PR re-implements the modifier class `.spectrum-Swatch--lightBorder` based on a new conversation with design.
I restarted this conversation with Miruna and got clarification from her:
me: 
...I've been migrating a bunch of documentation from our [static site](https://opensource.adobe.com/spectrum-css/swatch.html) to storybook. I saw on the static site there was a …
=> feat(swatch): add support for lightBorder

.changeset/gold-spies-learn.md, components/breadcrumb/index.css
During the [SWC implementation of breadcrumbs](https://github.com/adobe/spectrum-web-components/pull/4578), it was noticed that [there might be some misalignment of the breadcrumb items](https://adobedesign.slack.com/archives/CS22GNRU2/p1721217941481189?thread_ts=1720625760.158419&cid=CS22GNRU2), specifically for large/mobile scale: 
https://github.com/user-attachments/assets/33dc71fb-2f5a-4fee-8985-538457d914ac
In the video above, when breadcrumbs is toggled to the mobile scale, the margin around the separator icon increases from 19px to 25px. That margin causes the `spectrum-Breadcrumbs-item` element to increase in height in comparison to the last breadcrumb item, which has `display: none` set on its corresponding separator icon. You can see in the screenshots below that the last …
=> fix(breadcrumb): center breadcrumb itemLink

components/taggroup/CHANGELOG.md, components/taggroup/stories/taggroup.stories.js, components/taggroup/stories/template.js, components/thumbnail/CHANGELOG.md, components/thumbnail/stories/template.js, components/thumbnail/stories/thumbnail.stories.js, components/tray/stories/tray.stories.js, components/treeview/CHANGELOG.md, components/treeview/stories/template.js, components/treeview/stories/treeview.stories.js, components/well/stories/well.stories.js
Updates Storybook to contain information from Docs site for: Tag group, Thumbnail, Tray, Treeview, Well
(Underlay and Typography are also part of this card, but Underlay does not appear to exist on the docs site and Typography will have a separate PR.)
**Tag group**:
* `Standard` variant (docs site) --> `Default` (Storybook)
* `Removable` variant (docs site) --> `Removable` (Storybook)
`OverflowItems` story changed to `Removable` to align more closely with docs site, and because `Removable` is more of a variant, whereas `OverflowItems` describes default behavior. Tag wrapping behavior is noted in Storybook rather than having its own story.
**Thumbnail**:
* `Thumbnail` variant (docs site) --> `Default` (Storybook)
* `Thumbnail (focused)` variant (docs site) --> `Focused` (Storybook)
* …
=> docs(taggroup, thumbnail, tray, treeview, well): docs site to storybook

.changeset/lucky-dots-live.md, components/icon/icons.css
It was reported that this normalize CSS for IE 9/10/11, which Spectrum Web Components converts to the selector `:host(:not(:root))`, was leading to "clipping on iOS mobile (for Express) as well as on Safari on MacOS". An Express-specific hotfix was already put in to override this overflow declaration.
This is safe to remove as the project does not support IE 11.
**Reference:** 
The original `necolas/normalize.css` has this normalization labeled as "Correct overflow not hidden in IE 9/10/11."
CSS-700
@marissahuysentruyt 
Validate:
2. If components have been modified, VRTs have …
=> fix(icon): remove legacy ie overflow css causing ios clipping issues

.changeset/lucky-jeans-happen.md, components/progressbar/index.css, components/progressbar/stories/meter.stories.js
Because meter just extends the `ProgressBar.args`, `staticWhite` shows in the meter controls in Storybook. During the work in #2929, we noticed that the positive, negative and notice fill colors for meter do not respond as expected when looking at a `staticWhite` story. When `staticWhite` was turned on, the positive, negative and notice colors remained the same, while the default story (and all of the progress bar stories) have reinforced, white fill colors.
🚫 
After checking with design (Nadeen), it was confirmed all stories should have the same fill colors as the default story when `staticWhite` is toggled on: 
> if the component is in the static option - all the elements take on white (field label, value and fill of the progress bar) and transparent white for the progress bar track.
✅ …
=> fix: static white meter story and corrected fill colors

.changeset/little-dodos-peel.md, components/card/index.css
Updates the background color behind the default variant's cover photo to match the design spec and adds a mod property so it can be customized.
1. BREAKING CHANGE: The default variant's cover photo now uses the same grey background color as the preview area for the quiet variant, which is visible when the image does not take up the entire space. This intended background color for non-quiet `--spectrum-background-base-color` was confirmed by the design team.
Spectrum CSS currently always uses `background-size: cover` on a background image for this variant, but SWC uses an actual image with `object-fit`, so the use case of an image that did not fill the whole area was not present or testable on the CSS side. I created a followup Jira issue CSS-878 for getting this markup more in sync and …
=> fix(card)!: change cover photo background color and include mod

components/modal/stories/modal.stories.js, components/modal/stories/template.js, components/pagination/stories/pagination.stories.js, components/pagination/stories/template.js, components/pickerbutton/CHANGELOG.md, components/pickerbutton/stories/pickerbutton.stories.js, components/pickerbutton/stories/template.js
This continues the migration work to move the documentation from the deprecated docs site to Storybook, covering the components Modal, Pagination, and Picker button. Variants shown on the docs site for these components have been added to Storybook as new stories if they did not already exist. No custom MDX files were needed for these components.
- Modal
- Updates docs text and sets Docs story to `inline: false` to avoid it being cut off horizontally
- Pagination
- Makes sure pagination variants are included in the Storybook docs. Note: the "button" style variant is represented in VRTs but not included for users as it is using the deprecated Split button component. I wasn't sure about the best way to document this as deprecated. That variant has no unique CSS and is basically just a Split …
=> docs(modal,pagination,pickerbutton): site docs to storybook

.storybook/decorators/utilities.js, .storybook/guides/develop.mdx, components/breadcrumb/stories/breadcrumb.stories.js, components/breadcrumb/stories/breadcrumb.test.js, components/breadcrumb/stories/template.js, components/checkbox/stories/checkbox.stories.js, components/checkbox/stories/checkbox.test.js, components/checkbox/stories/template.js, components/clearbutton/stories/clearbutton.stories.js, components/clearbutton/stories/clearbutton.test.js, components/clearbutton/stories/template.js, components/coachindicator/stories/coachindicator.stories.js, components/coachindicator/stories/template.js
This PR continues migrating documentation from the docs site into Storybook. The focus is on `breadcrumb`, `checkbox`, `clearbutton` and `coachindicator`. All variants of the component should now be displayed on the Storybook `Docs` page.
- `breadcrumb`: ~~new MDX docs page and~~ 3 `docs-only` stories
- `checkbox`: ~~new MDX docs page~~, usage notes and a `docs-only` story
- `clearbutton`: ~~new MDX docs page and~~ additional docs (Usage Notes) regarding proper icon size
- `coachindicator`: ~~new MDX docs page~~
**This PR doesn't need a changeset since it's docs-only.**
@jawinn 
Validate:
1. The documentation pages for at least two other components are still …
=> docs(breadcrumb, checkbox, clearbutton, coachindicator): Site Docs to Storybook

components/dial/stories/dial.stories.js, components/dial/stories/dial.test.js, components/dial/stories/template.js, components/dialog/stories/dialog.stories.js, components/dialog/stories/dialog.test.js, components/dialog/stories/template.js, components/divider/stories/divider.stories.js, components/divider/stories/divider.test.js, components/divider/stories/template.js, components/dropindicator/stories/dropindicator.stories.js, components/dropindicator/stories/template.js, components/tray/stories/tray.stories.js, components/tray/stories/tray.test.js
This PR continues migrating documentation from the static docs site into Storybook. The focus is on `dial`, `dialog` (standard dialog), `divider` and `dropindicator`. All variants of the components should now be displayed on the Storybook `Docs` page.
- `dial`: ~~new MDX docs page~~ new stories
- `dialog`: !!new MDX docs page~~ new stories and controls (plus an additional note regarding alert dialog)
- `divider`: ~~new MDX docs page~~ new stories
- `dropindicator`: ~~new MDX docs page~~ 
**This PR doesn't need a changeset since it's docs-only.**
Validate:
2. If components have …
=> docs(dial,dialog,divider,dropindicator): Migrate docs to storybook pt7

components/inlinealert/stories/inlinealert.stories.js, components/inlinealert/stories/inlinealert.test.js, components/inlinealert/stories/template.js, components/link/CHANGELOG.md, components/link/stories/link.stories.js, components/link/stories/template.js, components/logicbutton/stories/logicbutton.stories.js, components/logicbutton/stories/template.js, components/miller/stories/miller.stories.js
This PR continues migrating documentation from the docs site into Storybook. The focus is on `inlinealert`, `link`, `logicbutton` and `miller`. All variants of the component should now be displayed on the Storybook `Docs` page. Additionally, Chromatic coverage was added to `inlinealert`, `link`, and `logicbutton`.
- `inlinealert`: new stories and enhanced chromatic coverage
- `link`: new stories and added chromatic coverage
- `logicbutton`: enhanced chromatic coverage
- `miller`: new story descriptions
**This PR doesn't need a changeset since it's docs only.**
Validate:
2. If …
=> docs(inlinealert,link,logicbutton,miller): docs migration from static site to storybook

components/slider/CHANGELOG.md, components/slider/stories/slider.stories.js, components/slider/stories/slider.test.js, components/slider/stories/template.js, components/steplist/stories/steplist.stories.js, components/steplist/stories/steplist.test.js, components/steplist/stories/template.js, components/stepper/CHANGELOG.md, components/stepper/stories/stepper.stories.js, components/stepper/stories/template.js
This PR continues migrating documentation from the static docs site into Storybook. The focus is on `slider`, `stepper`, and `steplist`. All variants of the components should now be displayed on the Storybook `Docs` page. All components have `autodocs` and/or `!dev` stories now. Some of the migration notes for `slider` and `stepper` have been added to the corresponding `changelog`s.
[Jira](https://jira.corp.adobe.com/browse/CSS-793)
No MDX pages were added for any components.
Initially, this work was supposed to include splitview, and a potential bug in the template regarding the focused story was uncovered. However, fixing that would require a CSS change (adding a class or pseudo-class), so a subsequent Jira ticket will be created to follow up on that.
**This PR doesn't need a changeset …
=> docs(slider,stepper,steplist): docs from static site to storybook 

.github/workflows/lint.yml
Update the linting action to report on errors to the PR as inline comments rather than as a boolean Pass/Fail check.
This will provide more meaningful feedback when a linting error is introduced in a pull request.
Setup:
1. Pull down this branch locally.
2. Create a fork branch of this pull request: git checkout -b fork-validate-linting
3. Move the properties defined on line 23 down below the &:lang selectors to line 34.
4. Commit that change to the fork branch.
5. Open a new pull request for this change with this branch as your base: `gh pr create --base chore-lint-review-action` (only works if you have the [GitHub CLI](https://cli.github.com) installed).
=> chore: set lint action to review PR not just check

.changeset/fuzzy-brooms-jam.md, .changeset/fuzzy-jokes-begin.md, components/combobox/index.css, components/combobox/themes/spectrum-two.css, components/tabs/index.css, components/tabs/themes/spectrum-two.css, components/treeview/index.css, components/treeview/themes/spectrum-two.css, tokens/custom/dark-vars.css, tokens/custom/light-vars.css, tokens/dist/css/dark-vars.css, tokens/dist/css/light-vars.css, tokens/dist/index.css
- Migrates `--mod` variables in `themes/` to `index.css` for treeview, tabs, combobox
- Defines undefined rgb variables for treeview
Validate:
=> fix(treeview, tabs, combobox): migrate --mods to index.css

.github/workflows/vrt.yml
Updates our GitHub Action for VRT to always run on pushes to `main`, as suggested in the Chromatic docs:
https://www.chromatic.com/docs/github-actions/#maintain-a-clean-main-branch
> A clean main branch is a development best practice and highly recommended for Chromatic. This means testing your main branch to ensure builds are passing. It’s important to note that baselines will not persist through branching and merging unless you test your main branch.
> If the builds result from direct commits to main, you must accept changes to keep the main branch clean. If they’re merged from feature-branches, you must ensure those branches are passing before you merge into main.
Please tag yourself on the tests you've marked complete to confirm the tests have been run by someone other than the …
=> test: always run Chromatic against main

.changeset/seven-ways-search.md, .storybook/blocks/ComponentDetails.jsx
1. Access Storybook (by fetching and running the branch or via the preview generated by this pull request).
2. Open any component and navigate to docs page.
3. Verify version number alignment.
Validate:
=> fix(ComponentDetails): apply sb-unstyled className to correct version number misalignment

components/button/stories/button.mdx, components/button/stories/button.stories.js, components/button/stories/template.js
Moves over custom **Button** documentation from the `spectrum-two` branch, and integrates it with the current organization of stories in `main`. As part of the effort to migrate the docs site to Storybook. Includes a custom `.mdx` file, additional docs-only stories, and some supporting templates.
Validate:
=> docs(button): custom storybook docs from spectrum-two

components/card/stories/template.js
Verified locally in storybook.
1. Navigate to the Storybook URL for the PR (or run the branch locally)
2. Open the `card` component.
3. Zoom in below the image to verify the border is present.
4. Toggle `isQuiet` to `true` and verify that the footer is hidden.
Validate:
5. If components have been modified, VRTs have been run on this branch:
=> chore(card): storybook component fixes

.changeset/selfish-readers-wave.md, components/card/index.css
This prevents `.spectrum-Card-actionButton` from spilling the available space in the header and aligns the title and action button at the opposite edges of the container.
1. Open the Storybook URL for the PR (or run against the branch locally).
2. Navigate to the card component.
3. Set **Card actions** to `true`
4. Hover over the action button to verify the proper card dimensions.
Validate:
5. If components have been modified, VRTs have been run on this branch:
=> fix(card -> action button): corrects the size and alignment of the card action button

.changeset/cyan-fishes-punch.md, components/toast/index.css
Added `overflow-wrap:anywhere` to wrap long words in toast body
Validate:
Before:
After:
=> fix(toast): added overflow css to toast for long words

components/card/stories/template.js
1. Fetch the branch and run Storybook locally, or reference the URL associated with the PR.
2. Navigate to the card component and verify the border renders under the image.
3. Inspect the border and verify `.spectrum-Divider` styles are applied.
Validate:
=> chore(card): import Divider and remove static hr from card story

.storybook/package.json, .storybook/project.json
When triggering a chromatic build locally, the `yarn test` command was building using `NODE_ENV=production` instead of the expected `NODE_ENV=development`. This caused the CSS to be generated without the `is-` prefixed classes we use to quickly validate states such as focus or hover.
This PR adds the `NODE_ENV` definition to the storybook build command in the `.storybook/package.json` so that local test commands generate the expected CSS output.
=> chore(storybook): add env variable for local testing

.changeset/clever-seas-smell.md, components/stepper/index.css, components/stepper/metadata/metadata.json
- This corrects the border color for the stepper component infield buttons by setting the border color property to Highlight when the parent stepper component is invalid.
- Verified in assistiv labs Windows High Contrast Mode
1. Run Storybook locally (or reference the link for this PR).
2. Navigate to Assistiv Labs and start a Windows High Contrast Mode VM (if running the branch locally, you'll need to enable the Assistiv Labs tunnel to access Storybook).
3. Enable Windows High Contrast Mode.
4. Navigate to the Stepper component in Storybook.
5. Verify that the stepper button border color matches the parent stepper field when the component is set to invalid.
Validate:
2. If components have been …
=> fix(stepper): corrects invalid button color border to match field in windows high contrast mode

.changeset/loud-pandas-act.md, components/treeview/index.css, components/treeview/stories/template.js, components/treeview/stories/treeview.stories.js, components/treeview/stories/treeview.test.js
The detached treeview variant was inadvertently removed in a refactor (#2218), this returns it to its original styling as seen before #2218, with corner rounding on items visible in the detached variant.
[CSS-871](https://jira.corp.adobe.com/browse/CSS-871)
Validate:
Before:
After:
=> fix(treeview): display corner rounding for detached treeview

.changeset/many-eels-protect.md, components/closebutton/index.css, components/closebutton/metadata/metadata.json, components/closebutton/stories/closebutton.stories.js, components/closebutton/stories/closebutton.test.js, components/closebutton/stories/template.js
Currently the t-shirt sizing for Close button is using "spectrum-Closebutton" as a prefix which does not align with the use of "spectrum-CloseButton" (capital B) for the root class. This PR adds sizing classes that use the capital B and labels the lowercase B class as deprecated.
Expands Close button test coverage to include the hover and focus states.
Validate:
=> feat(closebutton): fix close button sizing class name

.changeset/lemon-tools-look.md, components/calendar/index.css
- Makes text in the calendar in high contrast mode that is not in a selected cell visible again by removing redundant color property and allowing it to be set by the adjusted variable values.
Verified in Assistiv Labs high contrast mode-enabled Windows VM.
1. Run Storybook locally (or reference the link for this PR).
2. Navigate to Assistiv Labs and start a Windows High Contrast Mode VM (if running the branch locally, you'll need to enable the Assistiv Labs tunnel to access Storybook).
3. Enable Windows High Contrast Mode.
4. Navigate to the Calendar component in Storybook.
5. Verify that the selected and hover states behave as expected and that the text that is neither selected nor focused is visible.
Validate:
1. The documentation pages for at least two other components are still …
=> fix(calendar): addresses issue where text that was not selected was illegible in high contrast mode

.changeset/ninety-peas-approve.md, components/avatar/index.css
- Updates the avatar link styles to reduce redundancy and properly remove the border that was displayed in high contrast mode.
- Verified in assistiv labs Windows High Contrast Mode
1. Run Storybook locally (or reference the link for this PR).
2. Navigate to Assistiv Labs and start a Windows High Contrast Mode VM (if running the branch locally, you'll need to enable the Assistiv Labs tunnel to access Storybook).
3. Enable Windows High Contrast Mode.
4. Navigate to the Avatar component in Storybook.
5. Verify that the square yellow outline no longer renders around the avatar component.
Validate:
=> fix(avatar): remove outline and reduce redundancy

components/closebutton/metadata/closebutton.yml, components/closebutton/stories/closebutton.stories.js, components/closebutton/stories/template.js
Migrates the **close button** documentation and examples from the docs site to Storybook. Some docs specific stories were added, and descriptions adjusted for clarity.
This adds a missing control for the "icon size" option that was documented on the [docs site](https://opensource.adobe.com/spectrum-css/closebutton.html) and [guidelines](https://spectrum.adobe.com/page/close-button/#Icon-size), and updates the template to render the correct cross UI icon sizes. The "large" icon size story is also included in the VRTs, so this option at each component size is covered.
Validate: …
=> docs(closebutton): migrate docs to storybook and add missing control

components/stepper/stories/stepper.stories.js, components/stepper/stories/stepper.test.js, components/stepper/stories/template.js
Update VRT to show "invalid" as a top-level test instead of a state because it's beneficial for us to see an "invalid" snapshot in combination with all other states (disabled, hovered, focused, etc.).
Moved "hide-stepper" to a state because it's most helpful to see it as a single snapshot for default and quiet variants.
Validate:
=> chore(stepper): update vrt snapshots

.changeset/flat-tips-knock.md, components/slider/index.css, components/slider/metadata/metadata.json
- Corrects side label positioning by adding margin-inline-end to provide space between the label and the slider component
- Verified locally in Storybook.
1. Run Storybook locally (or reference the link for this PR).
2. Navigate to the slider component
3. Set `Label position` to side.
4. Verify that there is no space between the label and the slider component.
Validate:
5. If components have been modified, VRTs have been run on this branch:
=> fix(slider): adds space between side positioned label and slider

components/button/stories/button.test.js
Some of the button component's outline variants were not covered in the VRTs. This PR adds additional coverage of these combinations:
- outline + primary
- outline + secondary
- outline + negative
It also removes the "Fill" test as it was a duplicate of the existing "Accent" test where the default treatment is already "fill".
Validate:
=> docs(button): increase coverage of outline variants

components/dropindicator/stories/dropindicator.stories.js, components/dropindicator/stories/template.js
Update the dropindicator argTypes to use the key `length` instead of `size` so that the testing grid doesn't try to render the sizing table.
=> chore(dropindicator): update storybook prop to use length instead of size

.changeset/giant-scissors-protect.md, .changeset/twelve-melons-battle.md, package.json, plugins/stylelint-no-missing-var/package.json, plugins/stylelint-no-unknown-custom-properties/index.js, plugins/stylelint-no-unused-custom-properties/index.js, plugins/stylelint-no-unused-custom-properties/package.json, plugins/stylelint-theme-alignment/CHANGELOG.md, plugins/stylelint-theme-alignment/README.md, plugins/stylelint-theme-alignment/index.js, plugins/stylelint-theme-alignment/package.json, plugins/stylelint-theme-alignment/project.json, stylelint.config.js, yarn.lock
This pull request introduces a theme alignment tool to help us identify custom properties or selectors used in the express.css theme that have not been identified in the spectrum.css theme file. In order to ensure correct rendering in both themes, it's important that the spectrum.css file have a definition for any custom properties being leverages in other themes.
**Validating the new theme alignment plugin**
```
45:3  ⚠  Selector "&.is-disabled" is not used or defined in the base file (themes/spectrum.css).  spectrum-tools/theme-alignment
```
**Testing for regressions in existing plugins that were updated**
```
22:2   ⚠  Unused custom property …
```
=> chore: add stylelint theme alignment tool; harden settings for s2

components/contextualhelp/stories/contextualhelp.mdx, components/datepicker/stories/datepicker.mdx
The TaggedRelease and ComponentDetails doc blocks were missing or not imported for the Contextual Help page. This PR adds those in.
@marissahuysentruyt
=> chore(contextualhelp): docs page fix

components/icon/stories/template.js
Fixes the issue with UI icons [not displaying in Storybook for the Default story](https://spectrum-css.netlify.app/preview/?path=/story/components-icon--default&args=setName:ui;uiIconName:Asterisk75). The Template was not making use of `uiIconName`, which is a separate control/arg when the setName is UI. The console was displaying our error message "Icon: Could not render a result because no icon name was provided to the icon template.".
Validate:
=> docs(icon): fix ui icons not displaying in storybook

.changeset/late-wombats-begin.md, tokens/custom-spectrum/custom-light-vars.css, tokens/dist/css/spectrum/light-vars.css, tokens/dist/index.css
I noticed that the `--spectrum-well-border-color` was mapped to the `-rgb` postfixed value which resolves to a raw rgb number but not a valid color. The way this property is being used, the styles expect to receive a valid color.
=> fix(tokens,well): border color mapping

.changeset/shiny-balloons-remember.md, components/typography/stories/typography.mdx, generator/templates/stories/{{ folderName }}.mdx.hbs
Update typography docs to include the tagged releases.
Update the generator to add the ComponentDetails and TaggedReleases doc blocks.
=> docs(typography): add tagged releases

components/helptext/stories/helptext.stories.js, components/helptext/stories/template.js
Migrates the help text component's docs page information to Storybook. Creates additional docs-only stories and some supporting templates. Also brings over some helpful info from help text's guidelines for the descriptions.
_Note: it didn't seem necessary to show Sizing for both neutral and negative, as negative is already showing the increase in text size. If you think it's still worth showing both, let me know._
Validate:
=> docs(helptext): migrate docs to storybook

components/button/stories/template.js, components/buttongroup/stories/template.js, components/dialog/stories/dialog.stories.js, components/popover/stories/popover.stories.js
Verified locally in Storybook.
1. Check out the branch and run Storybook locally (or navigate to the Storybook URL for this PR).
2. Open the docs section of the Dialog component and verify that all examples render.
3. Open the docs section of the Popover component and verify that all examples render.
Validate:
=> fix(storybook): updates to pass the correct content types to the dialog and popover components

.github/actions/file-diff/index.js
File diff GitHub Action has a small logic error when determining if a package has been removed or added. This PR fixes that logic error.
- Updates logic to the existing `isRemoved` and `isNew` functions which are being used elsewhere for the same determination
=> chore: fix logic in file-diff github action

components/commons/project.json
When running `yarn reporter commons`, an error was being thrown. This resolves that error by switching commons report task to a no-op. This aligns with how we run build and test on the commons package.
=> build: commons reporting bug fix

components/tooltip/stories/template.js, components/tooltip/stories/tooltip.stories.js
Makes updates to the Tooltip Docs page in Storybook to incorporate [Docs Site examples](https://opensource.adobe.com/spectrum-css/tooltip.html).
Note that in S2 all semantic variants will be removed (all variants aside from neutral). These semantic variants have been added in as a story of their own for easier removal later.
This is a docs-only PR, no changeset is necessary.
CSS-945
Validate:
=> docs(tooltip): docs site to storybook

components/actionbutton/CHANGELOG.md, components/actionbutton/metadata/actionbutton.yml, components/actionbutton/stories/actionbutton.stories.js, components/actionbutton/stories/actionbutton.test.js, components/actionbutton/stories/template.js, components/search/stories/search.stories.js
Migrating `actionbutton` docs to storybook. 
Added missing variants:
- Static White & Black
- Selected 
- Emphasis
- Sizing
- Disabled
Validate:
=> docs(actionbutton): migrate docs to storybook

components/search/stories/search.stories.js, components/search/stories/template.js
Added disabled, quiet, helptext docs
Validate:
=> docs(search): storybook doc migrations

components/statuslight/CHANGELOG.md, components/statuslight/stories/statuslight.stories.js, components/statuslight/stories/statuslight.test.js, components/statuslight/stories/template.js
This PR continues migrating documentation from the static docs site to Storybook, with a focus on the status light component. When possible, documentation and/or stories were brought over from the [S2 status light migration](https://github.com/adobe/spectrum-css/pull/2818).
- Added the migration notes to the `CHANGELOG`
- Added component description and some control descriptions
- Added documentation around variant usage
- Added sizing, semantic and non-semantic stories to showcase all variants of status light
[CSS-939](https://jira.corp.adobe.com/browse/CSS-939)
_This PR has no CSS changes, so no changeset is needed._
Validate:
1. The documentation pages for at …
=> docs(statuslight): docs to storybook migration

plugins/postcss-splitinator/package.json
=> chore: make postcss-splitinator pkg private

plugins/postcss-rgb-mapping/package.json
=> chore: switch postcss-rgb-mapping pkg to private

.changeset/rude-rivers-crash.md, components/slider/index.css, components/slider/metadata/metadata.json
This applies a flex layout to the spectrum slider controls to consistently align the enclosed handle and ramp, while also removing the margins that might otherwise interfere with alignment. This aims to resolve the issues with the calc-based approach that exhibited variations in vertical alignment.
Checked locally in Storybook.
1. Pull down the branch and run Storybook locally or access the Storybook URL for the PR.
2. Open the Slider component and select `Default`.
3. Verify that the handle is vertically aligned over the track.
Validate:
=> fix(slider ramp): correct handle and ramp vertical alignment

components/fieldlabel/stories/fieldlabel.stories.js, components/fieldlabel/stories/fieldlabel.test.js, components/fieldlabel/stories/form.stories.js, components/fieldlabel/stories/form.template.js, components/fieldlabel/stories/form.test.js
This continues the effort to migrate documentation from the CSS static docs site into Storybook, with a focus on `fieldlabel` and `form`. 
- In each component's case, missing stories and corresponding documentation were added, along with any relevant S2 features from https://github.com/adobe/spectrum-css/pull/2569.
- Test coverage was expanded for `form`, and "cleaned up" for `fieldlabel`.
- `form` also now has a `fieldLabelAlignment` control, to better showcase left- or right-aligned field labels.
_This PR has no CSS changes, so no changeset is needed._
[CSS-932](https://jira.corp.adobe.com/browse/CSS-932)
Validate:
1. The documentation pages for at least two other …
=> docs(fieldlabel/form): migrates docs to storybook

.changeset/three-months-provide.md, components/fieldgroup/stories/fieldgroup.stories.js, components/radio/index.css
Includes two small fixes:
1. The field group "Docs" page was blank. It was missing the default arg value for `items` in its Template, causing nothing to render within the field group markup.
2. The read-only radios on the field group Docs page were displaying on the completely wrong side. This issue also existed on the Chromatic template for radio. This was because of `margin-inline-start` being set to `auto` instead of `0` for read-only. In a flex container, `auto` on the margin of a flex item will automatically extend its specified margin to occupy the extra space.
Validate: …
=> fix: blank field group docs and read-only radio alignment

components/underlay/stories/underlay.stories.js
No documentation currently exists on the site for the underlay styles so this PR adds a very light-weight set of notes on the proper usage of the underlay, similar to those found on the [SWC docs site](https://opensource.adobe.com/spectrum-web-components/components/underlay/).
On the Underlay Storybook docs page, expect to see:
=> docs(underlay): migrate docs to storybook

.github/workflows/vrt.yml
Specifies that certain branch names should be excluded from triggering Chromatic when they're merged into `main`
Attempts to be selective about when a merge to `main` triggers a Chromatic run. The first bit of code here should prevent Chromatic from being run on any Dependabot or Changesets-created branches.
The second bit of code checks to see if the branch being merged into `main` is a Dependabot or Changesets-related branch, and stops the Chromatic action if the merge has come from one of those two types of branches.
Validate:
2. If components have been modified, VRTs have …
=> ci: be selective about running VRT on main

components/datepicker/stories/datepicker.test.js
the read-only datepicker should no longer display the calendar
This PR corrects the spelling of an arg for the date picker component so that the appropriate styles show up, as well as clear up the Chromatic snapshot.
`readOnly` should be `isReadOnly`
Before, the date picker calendar was displayed when it shouldn't have been, and the component's read-only styles weren't rendering. It's also encroaching on the Quiet date picker's personal space.
After, a happy, read-only date picker:
- Pull down the branch locally or use [the deploy preview](https://pr-3210--spectrum-css.netlify.app/preview/?path=/docs/guides-contributing--docs)
- Visit [the date picker testing …
=> chore: corrects readOnly to isReadOnly arg

components/accordion/stories/accordion.stories.js, components/actionbar/stories/actionbar.stories.js, components/actionbutton/stories/actionbutton.stories.js, components/actiongroup/stories/actiongroup.stories.js, components/alertbanner/stories/alertbanner.stories.js, components/alertdialog/stories/alertdialog.stories.js, components/avatar/stories/avatar.stories.js, components/badge/stories/badge.stories.js, components/breadcrumb/stories/breadcrumb.stories.js, components/button/stories/button.stories.js, components/buttongroup/stories/buttongroup.stories.js
This PR is the first in a series that adds S2 design links to components. Now, when a user is on a story page (not a docs page), under the "Design" tab, a Figma asset should render. 
Using the [S2 / Desktop Figma file](https://www.figma.com/design/Mngz9H7WZLbrCvGQf3GnsY/S2-%2F-Desktop?node-id=5634-5140&node-type=frame&t=YT3sYHqnhqpnjdv9-0), specific frames were selected in an attempt to give a user (specifically a developer) context to the component they are viewing. (instructions on how to get the Figma frame links are here: [slack canvas](https://adobe.enterprise.slack.com/docs/T024FSURM/F07PTPUPMRV)
Most designs are geared towards the default for a component, like linking to the `M`/medium grouping of the component and its states, or the frame selection with the most options for a user …
=> docs: add links to figma assets part 1

components/switch/CHANGELOG.md, components/switch/stories/switch.stories.js, components/switch/stories/switch.test.js, components/switch/stories/template.js
Updates the Switch Docs page in Storybook to align more closely with [Docs site](https://opensource.adobe.com/spectrum-css/switch.html), incorporating [guidelines](https://spectrum.adobe.com/page/switch/) to add extra information.
Testing coverage was examined but no changes were made.
Docs-only, no changeset necessary.
[CSS-940](https://jira.corp.adobe.com/browse/CSS-940)
Validate:
=> docs(switch): docs site to storybook

components/checkbox/stories/checkbox.stories.js, components/closebutton/stories/closebutton.stories.js, components/coachindicator/stories/coachindicator.stories.js, components/coachmark/stories/coachmark.stories.js, components/colorarea/stories/colorarea.stories.js, components/colorhandle/stories/colorhandle.stories.js, components/colorslider/stories/colorslider.stories.js, components/colorwheel/stories/colorwheel.stories.js, components/combobox/stories/combobox.stories.js, components/contextualhelp/stories/contextualhelp.stories.js
This PR is the second in a series that adds S2 design links to components. Now, when a user is on a story page (not a docs page), under the "Design" tab, a Figma asset should render. 
Using the [S2 / Desktop Figma file](https://www.figma.com/design/Mngz9H7WZLbrCvGQf3GnsY/S2-%2F-Desktop?node-id=5634-5140&node-type=frame&t=YT3sYHqnhqpnjdv9-0), the top-level component pages are linked in an attempt to give a user (specifically a developer) context to the component they are viewing. (instructions on how to get the Figma frame links are here: [slack canvas](https://adobe.enterprise.slack.com/docs/T024FSURM/F07PTPUPMRV)
Components affected:
- checkbox (do we want the designs to link to the single checkbox, or checkbox group?)
- close button
- coach indicator
- coach mark
- colar area
- color …
=> docs: add links to figma assets part 2

components/dialog/stories/dialog.stories.js, components/divider/stories/divider.stories.js, components/dropzone/stories/dropzone.stories.js, components/fieldlabel/stories/fieldlabel.stories.js, components/helptext/stories/helptext.stories.js, components/illustratedmessage/stories/illustratedmessage.stories.js, components/inlinealert/stories/inlinealert.stories.js, components/link/stories/link.stories.js, components/menu/stories/menu.stories.js, components/picker/stories/picker.stories.js, components/progressbar/stories/meter.stories.js
This PR is the third in a series that adds S2 design links to components. Now, when a user is on a story page (not a docs page), under the "Design" tab, a Figma asset should render. 
Using the [S2 / Desktop Figma file](https://www.figma.com/design/Mngz9H7WZLbrCvGQf3GnsY/S2-%2F-Desktop?node-id=5634-5140&node-type=frame&t=YT3sYHqnhqpnjdv9-0), the top-level component pages are linked in an attempt to give a user (specifically a developer) context to the component they are viewing. (instructions on how to get the Figma frame links are here: [slack canvas](https://adobe.enterprise.slack.com/docs/T024FSURM/F07PTPUPMRV)
Components affected:
- standard/default dialog
- takeover dialog
- divider
- drop zone
- field label
- help text
- illustrated message
- inline alert
- link
- menu (menu group in …
=> docs: add links to figma assets part 3

components/popover/stories/popover.stories.js, components/progressbar/stories/progressbar.stories.js, components/progresscircle/stories/progresscircle.stories.js, components/radio/stories/radio.stories.js, components/rating/stories/rating.stories.js, components/search/stories/search.stories.js, components/sidenav/stories/sidenav.stories.js, components/slider/stories/slider.stories.js, components/statuslight/stories/statuslight.stories.js, components/stepper/stories/stepper.stories.js, components/swatch/stories/swatch.stories.js, components/swatchgroup/stories/swatchgroup.stories.js
This PR is the fourth installment in a series that adds S2 design links to components. Now, when a user is on a story page (not a docs page), under the "Design" tab, a Figma asset should render. 
Using the [S2 / Desktop Figma file](https://www.figma.com/design/Mngz9H7WZLbrCvGQf3GnsY/S2-%2F-Desktop?node-id=5634-5140&node-type=frame&t=YT3sYHqnhqpnjdv9-0), the top-level component pages are linked in an attempt to give a user (specifically a developer) context to the component they are viewing. (instructions on how to get the Figma frame links are here: [slack canvas](https://adobe.enterprise.slack.com/docs/T024FSURM/F07PTPUPMRV)
Components affected:
- popover
- progress bar
- progress circle
- radio
- rating
- search
- side nav (multi-level/withHeadings = side navigation in Figma; default = …
=> docs: add links to figma assets part 4

components/typography/stories/template.js
In the Typography storybook, allow typography elements to gracefully fallback to the next closest size when an invalid size is provided.
Visit the [typography storybook page here](https://pr-3198--spectrum-css.netlify.app/preview/?path=/story/components-typography--default):
Validate:
=> chore(typography): add fallback sizes for testing

components/toast/stories/template.js, components/toast/stories/toast.stories.js, components/toast/stories/toast.test.js
- Added stories: Action & Wrapping
- Added descriptions for neutral, negative, and informative variants
- Added control for variants
- Added test case for wrapping story 
Validate:
=> docs(toast): migrate docs to storybook

components/picker/CHANGELOG.md, components/picker/stories/picker.stories.js, components/picker/stories/picker.test.js, components/picker/stories/template.js, components/tabs/stories/template.js
Migrates docs site information to Storybook for the Picker component. Creates several docs only stories to represent the missing examples. This also updates the variants test.js data to add coverage for missing states and variants.
Some Storybook updates of note:
- Adds a control for value (`currentValue`), and separates the concept of value and placeholder, which are different things with different classes. Their text resides in the same element but the `is-placeholder` class only exists when this text is a placeholder.
- Adds a control for setting the adjacent help text that already exists in the template
- Adds a control for displaying the thumbnail variant (with a workflow icon) from the docs site. This icon has a class associated with it (`.spectrum-Picker-icon`) that was not …
=> docs(picker): migrate docs to storybook

.changeset/chatty-carrots-warn.md, components/search/index.css, components/search/metadata/metadata.json
Addresses issue where a portion of search clear button sat outside of its parent by moving the transform applied to the button to the child icon.
This repositions the icon and the enclosing button such that the icon renders in the same place in the layout, the button doesn't move outside the bounds of the container and the clickable area to clear the input remains the same size.
**Note:** the clear icon is no longer centered within the parent _but_ addressing the overflow without re-aligning the icon would result in the icon sitting further inside the field than is the case with other variants.
CSS-914
Locally in Storybook.
1. Fetch branch and run locally or access the Storybook URL for the PR.
2. Navigate to the search component.
3. Enable quiet mode
4. Verify that the clear icon remains …
=> fix(search): addresses quiet variant clear icon positioning

.storybook/assets/base.css, .storybook/decorators/context.js, .storybook/decorators/helpers.js, .storybook/decorators/utilities.js, components/actionbutton/stories/actionbutton.stories.js, components/actionbutton/stories/actionbutton.test.js, components/actionbutton/stories/template.js, components/actiongroup/stories/actiongroup.test.js, components/badge/stories/badge.test.js, components/button/stories/button.stories.js, components/button/stories/button.test.js, components/clearbutton/stories/clearbutton.stories.js, components/clearbutton/stories/clearbutton.test.js, components/clearbutton/stories/template.js, components/closebutton/stories/closebutton.test.js, components/divider/stories/divider.stories.js, components/divider/stories/divider.test.js, components/link/stories/link.stories.js, components/link/stories/link.test.js, components/progressbar/stories/meter.stories.js, components/progressbar/stories/meter.test.js, components/progressbar/stories/progressbar.stories.js, components/progressbar/stories/progressbar.test.js, components/progresscircle/stories/progresscircle.stories.js, components/progresscircle/stories/progresscircle.test.js
This update adds support for static colors in the testing grids saving us from having to run static white/static black snapshots separately. I accomplished this by updating which containers are returned by the fetchContainers function based on if the document is in a testing state or not.
Updated tests:
- ActionButton: Remove separate static black & static white tests; add both to the testing grid.
- ActionGroup: Add static black & static white to the test grid.
- Button: Remove separate static black & static white tests; add both to the testing grid.
- ClearButton: Remove OverBackground test; add static white to testing grid.
- CloseButton: Add static black & static white to testing grid.
- Divider: Remove static white and static black from separate snapshots; add to testing grid.
- …
=> chore(storybook): support static color settings in testing grid

.changeset/silent-news-applaud.md, components/contextualhelp/metadata/metadata.json, components/contextualhelp/themes/spectrum-two.css, tokens/dist/css/components/bridge/contextualhelp.css, tokens/dist/css/components/bridge/index.css, tokens/dist/css/components/express/contextualhelp.css, tokens/dist/css/components/express/index.css, tokens/dist/css/components/spectrum-two/contextualhelp.css, tokens/dist/css/components/spectrum/contextualhelp.css, tokens/dist/css/components/spectrum/index.css
This PR addes the `--spectrum-contextual-help-content-spacing` definition to the theme file.
Validate:
Previously:
=> fix(contextual-help): added help-content-spacing definition

.changeset/chatty-sheep-draw.md, components/picker/index.css
Addresses issue with vertical alignment of picker text/placeholder by applying inline-flex in template rather than inline-block. Applies flex-shrink to validation icons to prevent icon from resizing when label is long enough to be truncated.
CSS-977
Verified locally in Storybook.
1. Fetch branch and run locally or access the Storybook URL for the PR.
2. Navigate to the picker component.
3. Verify that the placeholder text is properly aligned within the picker.
4. Verify that the validation icon does not resize when a long label is supplied as an arg.
Validate:
5. If components have been modified, VRTs have been run on this branch:
=> fix(picker): update picker display and icon flex properties to resolve layout bugs

components/actionbutton/stories/actionbutton.stories.js, components/actionbutton/stories/template.js, components/actiongroup/stories/actiongroup.stories.js, components/actiongroup/stories/template.js
All action buttons were, by default, receiving the `aria-label` attribute. When clickable elements have visible text, typically they should not receive an `aria-label` because a screen reader will read the visible text aloud. The button component was applying `aria-label`s conditionally (when a button didn't have visible text/label), so the same approach was brought to action button. Now, any action button that has "regular" label text does not receive the `aria-label`, and if an action button is icon-only, with its `hideLabel: true` arg set, an `aria-label` will be applied.
Because action buttons are used in the action group component as well, some refactoring had to be done to make sure any arguments used to create icon-only action buttons were from the action group args, as opposed to …
=> chore[actionbutton, actiongroup]: fix application of aria-labels

.vscode/extensions.json, .vscode/settings.json
Alphabetize the suggested VS Code plugins and add DocThis, Figma, and CoPilot suggestions. Also organized and enhanced the settings for our supported plugins to make best use of these tools when installed.
=> chore: update vscode settings and suggestions

components/fieldgroup/stories/fieldgroup.stories.js, components/fieldgroup/stories/template.js
Addresses regressions in field groups.
Verified locally in storybook and by referencing [legacy docs page](https://pr-2827--spectrum-css.netlify.app/preview/?path=/docs/components-field-group--docs).
1. Fetch branch and run locally or access the Storybook URL for the PR.
2. Navigate to the field group component.
3. Verify that the rendered field groups align with the [legacy docs page](https://pr-2827--spectrum-css.netlify.app/preview/?path=/docs/components-field-group--docs).
Validate:
=> fix(field-group): addresses regressions in field groups.

components/progressbar/stories/meter.stories.js, components/progressbar/stories/meter.template.js
An update to the meter component storybook templates to help with simplifying the comparison between `rootClass` values in #3129. The Meter component was the only component using a `rootClass` arg value that is not unique and its own (previously it was using `spectrum-ProgressBar`).
Meter's Storybook template was using the `rootClass` for progress bar, rather than its own `rootClass`. It was set up this way because of the way the two components are housed together, and meter primarily just uses ProgressBar, with some added classes.
This value not being unique made it difficult to compare and match up the value of `rootClass` in the `package.json` `spectrum` data to the actual `rootClass` defined in the story files default args.
Please tag yourself on the tests you've marked complete to …
=> docs(meter): let meter use its rootclass in storybook

.changeset/green-ants-accept.md, components/thumbnail/index.css, components/thumbnail/metadata/metadata.json
Found a bug in the `thumbnail/index.css` file for the following variable stack:
```
--spectrum-thumbnail-border-color-rgba: rgba(var(--spectrum-gray-800-rgb), var(--spectrum-thumbnail-border-opacity));
```
**Typo**: `--spectrum-thumbnail-border-color-opacity` should have been `--spectrum-thumbnail-border-opacity`. Thumbnail border was rendering as 0% opacity but should have been 10%.
Validate:
=> fix(thumbnail): incorrect opacity variable used

components/typography/stories/template.js
I noticed in the visual regression tests that the detail heading is still showing at default medium sizing when at "XXS"; ideally it should default to "S".
=> chore(typography): fallback sizing for detail at xxs

.changeset/funny-jobs-relax.md, .storybook/decorators/utilities.js, components/closebutton/index.css, components/closebutton/metadata/metadata.json, components/closebutton/stories/closebutton.stories.js, components/closebutton/stories/closebutton.test.js
Remove hardcoded tokens for CloseButton sizing in favor of component sizing. Remove mapping to height & width separately in favor of using the existing `--spectrum-closebutton-size` property.
Validate:
=> fix(closebutton): t-shirt sizing variable fix

components/fieldgroup/stories/fieldgroup.test.js
- Removes hardcoded templates from test cases
- Sets input type(s) to differentiate tests
- Adds additional cases/variations to provide parity between the two input types (checkbox/radio)
Verified locally in Storybook.
1. Fetch the branch and run Storybook locally or access the URL for the PR.
2. Navigate to the field group component.
3. Enable the `Show testing preview` for the component.
Validate:
=> chore(field-group): update field group tests

.changeset/wild-crabs-allow.md, components/assetlist/index.css
Moves `forced-color` rule after custom properties to satisfy lint rules.
=> chore(stylelint-assetlist): adjust declaration order to resolve lint violation

components/clearbutton/index.css, stylelint.config.js
Verified locally in VS Code + config.
1. Fetch the branch.
2. Open a file with duplicate selectors like `components/clearbutton/index.css`. Verify that there's no longer a lint violation for the duplicate selectors.
Validate:
=> chore(stylelint): config updates

.changeset/silver-pianos-develop.md, components/badge/index.css, components/badge/metadata/metadata.json
Assigns `CanvasText` to custom property to satisfy linting requirements.
=> chore(stylelint-badge): create property for forced-colors value to satisfy lint requirements

.changeset/flat-toys-battle.md, .changeset/forty-radios-type.md, components/card/index.css, components/card/metadata/metadata.json, components/contextualhelp/index.css, components/contextualhelp/metadata/metadata.json, components/swatch/index.css, components/swatch/metadata/metadata.json, tokens/custom-spectrum/custom-dark-vars.css, tokens/custom-spectrum/custom-darkest-vars.css, tokens/custom-spectrum/custom-large-vars.css, tokens/custom-spectrum/custom-light-vars.css, tokens/custom-spectrum/custom-medium-vars.css, tokens/custom-spectrum/custom-vars.css, tokens/dist/css/spectrum/custom-large-vars.css, tokens/dist/css/spectrum/custom-medium-vars.css, tokens/dist/css/spectrum/custom-vars.css, tokens/dist/css/spectrum/dark-vars.css, tokens/dist/css/spectrum/darkest-vars.css, tokens/dist/css/spectrum/global-vars.css, tokens/dist/css/spectrum/index.css, tokens/dist/css/spectrum/large-vars.css, tokens/dist/css/spectrum/light-vars.css, tokens/dist/css/spectrum/medium-vars.css, tokens/dist/index.css
Add component-level token overrides from card, contextualhelp, swatch, and typography to ensure valid theme toggling.
Light/dark/darkest custom overrides added: 
- `--spectrum-card-selected-background-color-rgb`
- `--spectrum-swatch-border-color`
- `--spectrum-swatch-border-color-light`
Medium/large custom overrides added:
- `--spectrum-contextual-help-content-spacing`
Global custom overrides added: 
- `--spectrum-font-family-ar`
- `--spectrum-font-family-he`
- `--spectrum-font-family`
- `--spectrum-font-style`
- `--spectrum-font-size`
This update removes tokens defined locally that belonged in the global scope. To ensure no regressions, please upgrade your @spectrum-css/tokens package at the same time so you will pick up the component-level definitions now in the global tokens scope. …
=> feat(card,contextualhelp,swatch,tokens): add theme tokens for components to global scope

.changeset/serious-pumpkins-share.md, components/closebutton/index.css, components/search/index.css
Removes unnecessary stylelint-disable comments now that rule is disabled in config.
=> chore(stylelint): remove stylelint disable comments

.changeset/two-mayflies-divide.md, components/colorloupe/index.css
Disables lint violation and moves comment to stylelint-disable description.
=> chore(stylelint): disable stylelint violation; use comment as description

.changeset/quick-paws-lick.md, components/colorwheel/index.css
Moves custom properties to resolve declaration order lint violation. Disable unused property violation and add comment as disable statement description.
=> chore(stylelint): move property declarations + disable violation

.changeset/wet-bulldogs-shake.md, components/slider/index.css
Resolves lint violation by moving todo comment into stylelint disable comment as a description
=> chore(slider): add comment as description to stylelint disable

.changeset/flat-ads-compete.md, components/rating/index.css, components/rating/metadata/metadata.json
Assigns CanvasText to custom property to satisfy linting requirements.
=> chore(rating): create property for forced-colors value to satisfy lint requirements

.changeset/gold-pens-clean.md, components/search/index.css
Resolves lint violation in search by moving spectrum-search-color custom property above style declarations.
=> chore(search): move custom property to resolve lint violation

.changeset/few-icons-kneel.md, .changeset/khaki-pugs-rescue.md, .changeset/wise-apricots-repeat.md, components/colorslider/index.css, components/datepicker/index.css, components/dropzone/index.css, components/menu/index.css, components/search/index.css, components/slider/index.css, plugins/stylelint-no-unused-custom-properties/index.js, stylelint.config.js
The biggest update not included in a changeset is to the stylelint config. Updates include:
- Adding the legacy `u-` prefix support to the allowed class names
- Removing the legacy token structure from the ignore list for unknown custom properties
- Adding `--spectrum-picked-color` as an ignored unknown value
- Removing `--highcontrast` and `--system` as ignored prefixes for the unused custom properties (those should show up as used or there's likely an error in the styles)
See changesets for details on other updates.
Validate:
2. If components have been modified, VRTs have …
=> fix(CSS-1009): stylelint clean-up for unused custom properties

components/swatch/index.css
Remove unnecessary stylelint disable for max nesting depth. Move undefined variable comments into stylelint-disable descriptions.
=> chore(swatch): remove unnecessary max nesting depth ignore comments

.changeset/strong-geese-yawn.md, components/steplist/index.css
Resolves stylelint violation by removing vertical-align declaration that is ignored due to preceding display: block declaration.
=> chore(steplist): remove unnecessary vertical-align declaration

.changeset/calm-ears-think.md, .changeset/fair-badgers-repeat.md, components/actionbutton/index.css, components/actionbutton/stories/actionbutton.test.js, components/actiongroup/index.css
Recently, another bug was captured in relation to the diacritics and tone marks getting cut off in the action button when the text is Thai: https://jira.corp.adobe.com/browse/CCEX-131368. 
This PR attempts to fix that bug by adding padding to the action button's label, allowing for the diacritics to overflow into the padding space, and no longer get cut off. A similar solution was implemented recently for picker (https://github.com/adobe/spectrum-css/pull/2914) 
If we decide that adding padding is causing VRT diffs or other unexpected issues we want to avoid, we could explore using line height as well (a PR for the same picker issue mentioned above was closed in favor of the padding fix instead: https://github.com/adobe/spectrum-css/pull/2913)
The 2 commits related to adding and then …
=> fix(actionbutton): prevent diacritic clipping in thai

components/textfield/stories/template.js, components/textfield/stories/textarea.stories.js, components/textfield/stories/textarea.template.js, components/textfield/stories/textarea.test.js, components/textfield/stories/textfield.stories.js
Migrating docs for Textfield and Textarea. 
- Textarea Storybook coverage has been added 
- Helptext component is now a part of the Textfield Template
Textarea/Textfield docs:
Validate:
=> docs(textfield,textarea): migrating docs to storybook

.storybook/assets/base.css, components/alertbanner/stories/alertbanner.stories.js, components/alertbanner/stories/alertbanner.test.js, components/alertbanner/stories/template.js, components/coachmark/stories/coachmark.stories.js
The width of the Storybook root element was being limited with inline-size: max-content, which was causing a few issues:
- min-widths on some components were no longer being tested
- some responsive grid layouts were no longer working as intended
After running a force-rebuild on the VRTs to check for differences, it looks like removing these should not be a problem.  This is likely due to the switch to the Storybook "centered" layout for most stories, which uses a flex layout for centering, which creates a less wide storybook-root. The only stories which were affected in the VRT diff were:
- **coachmark**: this was manually setting the "padded" layout, which I removed in this PR after testing that the centered layout looks fine
- **alertbanner**: this is manually setting the "padded" …
=> feat(storybook): remove custom styles on storybook-root

.changeset/chilly-cheetahs-study.md, components/sidenav/index.css
Resolve stylelint violations by moving declaration and adding comment as stylelint disable description.
=> chore(sidenav): move declaration, add description and apply token

.changeset/modern-clocks-obey.md, components/tray/index.css
Resolves stylelint violation by adjusting declaration order
=> chore(tray): adjust declaration order to resovle lint violation

.changeset/lucky-schools-pay.md, components/thumbnail/index.css
Remove ignored vertical-align declaration and remove unnecessary stylelint ignore comments.
=> chore(thumbnail): remove unnecessary declarations + comments

.vscode/settings.json
- Removes deprecated `aslant.packageManager` setting
- Adds `postcss.validate: false` as `postcss.validate` conflicts with our `stylelint` and `posts`
Verified locally. Removing the following:
```
"at-rule-no-unknown": [
true,
{
ignoreAtRules: ["extend", "container", "each", "include", "mixin"],
},
],
```
Raises a lint violation against `at-rule-no-unknown`, establishing that `ignoreAtRules` is being applied (as no exceptions are now being defined in the rule definition).
Restoring the rule then returns our `unknownAtRules` violation which is attributed to `postcss`.
Adding `postcss.validate: false` to the workspace settings resolves the issue. Additionally — removing `"extend"` from `ignoreAtRules` and restarting the stylelint server in VS Code causes stylelint to surface a violation — …
=> chore(vscode-settings): remove deprecated property; disable postcss validate

.changeset/nervous-steaks-provide.md, components/treeview/index.css
Use custom property in place of direct value when defining mod.
=> chore(treeview): remove unused custom property to resolve lint violation

.changeset/lucky-experts-grow.md, components/coachmark/index.css, components/coachmark/metadata/metadata.json
During S2 development, I noticed a regression in pagination styles for the Coach Mark step and discovered this was due to font styles pointing to spectrum tokens that are not defined. There are however unused tokens defined with similar names. This PR points those typography elements to the appropriate styles.
See comment below for verification via the visual regression test results.
Validate:
=> fix(coachmark): correct invalid token pointers in pagination styles [CSS-1011]

stylelint.config.js
Removes `container` from `at-rule-no-unknown` at the exception is no longer necessary. `@container` 
1. Fetch the branch
2. Add an `@container` declaration to a CSS file
3. Restart stylelint
4. Verify the rule isn't marked as a stylelint violation
=> chore(stylelint): remove container from at-rule-no-unknown

.changeset/dirty-suits-mix.md, components/clearbutton/index.css, components/search/index.css, components/search/metadata/metadata.json, components/search/metadata/mods.md, components/search/stories/search.stories.js
A bug fix for the Search component's quiet variant. The `--spectrum-search-quiet-button-offset` was being calculated using a static workflow icon size of 100 but the search icon sizing is set using t-shirt sizing and varies. This PR updates the calculation to use the variable `--spectrum-search-icon-size` which updates based on the determined t-shirt size.
This also adds a deprecation notice for the `--mod-workflow-icon-size-100` and suggests the use of the `--mod-search-icon-size` instead.
I didn't add a changeset for the update to clearbutton because it just combines the duplicate selectors for `.spectrum-ClearButton`.
Validate:
1. The documentation pages for at …
=> fix(search): update icon sizing calculation in the quiet variant [CSS-1012]

.changeset/nasty-pillows-wonder.md, components/dialog/index.css, components/dialog/metadata/metadata.json
This PR aligns the sizing classes for the dialog component to t-shirt sizing, as most of our other components have done in recent years. The old size modifier classes will be deprecated and removed in S2, so deprecation comments were left in the CSS, along with the addition of the t-shirt classes. 
| old class name | new class name |
| --------- | ---------- |
| spectrum-Dialog--small | spectrum-Dialog--sizeS |
| spectrum-Dialog--medium | spectrum-Dialog (the default, so no size is necessary) |
| spectrum-Dialog--large | spectrum-Dialog--sizeL |
Validate:
2. If components have …
=> chore: dialog t-shirt sizing

.storybook/decorators/utilities.js, components/actionbutton/stories/template.js, components/actiongroup/stories/template.js, components/alertbanner/stories/template.js, components/button/stories/template.js, components/checkbox/stories/template.js, components/closebutton/stories/template.js, components/coachindicator/stories/template.js, components/combobox/stories/template.js, components/helptext/stories/template.js, components/menu/stories/template.js, components/picker/stories/template.js, components/progressbar/stories/meter.template.js, components/progressbar/stories/template.js, components/radio/stories/template.js, components/search/stories/template.js, components/statuslight/stories/template.js, components/steplist/stories/template.js, components/stepper/stories/template.js, components/swatch/stories/template.js, components/swatchgroup/stories/template.js, components/switch/stories/template.js, components/tabs/stories/template.js, components/tag/stories/template.js, components/textfield/stories/template.js, components/textfield/stories/textarea.template.js, components/toast/stories/template.js, components/tooltip/stories/template.js, components/typography/stories/template.js
Currently VRTs are leveraging the Typography element for the ignored headings. Although they use the "chromatic-ignore" class, this can cause layout issues when the line-height or font-size changes for those typographical elements, leading to unexpected VRT differences. This PR aims to reduce that risk by isolating type styles for VRT from the design system.
In order for the text color to respond to the background context without using a token value, we need to pass the context data through the Container down to the Heading. To this end I've added the context passthroughs in all the existing uses.
Validate:
1. The documentation pages for at least two other …
=> chore(storybook): align typography elements for VRTs

components/textfield/CHANGELOG.md
Since we're close to deprecating the CSS docs site in favor of our docs being housed in Storybook, I noticed we didn't have the text field migration guide notes in the CHANGELOG. This PR just moves any relevant contention for the Textfield Migration Guide to the textfield and/or textarea CHANGELOGs.
No changeset is necessary.
Validate:
=> chore(textfield,textarea): add migration guide to changelog

components/textfield/stories/textarea.stories.js, components/textfield/stories/textarea.template.js
Similar to progress bar and meter, text field and text area are now "nested" components. Recently, [meter was updated to include its own `rootClass`](https://github.com/adobe/spectrum-css/pull/3231) argument to ensure it was delivering the correct Spectrum guidelines URL. Text area will need the same treatment. Before these changes, the text area guidance resource link was navigating to the text _field_ page instead of the text _area_ page.
- Adds a `.spectrum-Textfield--multiline` rootClass to textarea component. It shouldn't overwrite/interfere with the textfield component in the text area template.
- adds an additional spectrum object to contain the text area guidance link & new rootClass
Please tag yourself on the tests you've marked complete to confirm the tests have been run by …
=> docs(textarea): add corrected guidelines link and rootClass

.changeset/itchy-bikes-join.md, components/search/index.css, components/search/metadata/metadata.json, components/search/metadata/mods.md
For `CSS-1052`.
This change removes the existing calc function used to calculate the padding-inline-end for S1 and the quiet variant in favor of a simpler value with a mod preceding a static value.
This change removes the `--mod-search-quiet-button-offset` mod.
With this change the blue area referenced in #3297 no longer extends under the bounding box of the clear button. The user can safely click on the blue area after this change to edit text and the touch area for the clear button is preserved. The `cursor` UI changes to the `pointer` state when hovering over the clear button as a visual indicator of the button's interactivity.
Verified locally in Storybook.
1. Open the Storybook URL for the PR (or fetch the branch and run it locally).
2. Navigate to the search component.
3. Enter a …
=> fix(search): removes calc and replaces w/fixed value

components/textfield/stories/template.js, components/textfield/stories/textarea.stories.js, components/textfield/stories/textarea.template.js, components/textfield/stories/textfield.stories.js
Our Storybook was adding the `is-keyboardFocused` class on click, which isn't the intended design. Click focus and focused by use of a keyboard have different styles. This update stops the class from being applied on click, applies it on tab focus, and documents how the class should be added by the implementation.
Validate:
New Docs story:
Design reference for styling differences between focus and focused by keyboard:
=> docs: fix and document use of keyboard focus classes on text fields

.changeset/afraid-dogs-worry.md, .changeset/gold-deers-smash.md, components/checkbox/index.css, components/checkbox/metadata/metadata.json, components/checkbox/stories/checkbox.stories.js, components/checkbox/stories/checkbox.test.js, components/checkbox/stories/template.js, components/fieldgroup/index.css, components/fieldgroup/metadata/metadata.json, components/fieldgroup/stories/fieldgroup.mdx, components/fieldgroup/stories/fieldgroup.stories.js, components/fieldgroup/stories/template.js
As noted in CSS-833, the CSS, SWC, and RSP implementations of read-only checkboxes/checkbox groups, and the docs surrounding them, conflicted with each other. After discussing with the design team, it was decided that the first step would be for CSS to bring our visual styles in line with React's implementation.
**Field group:**
- This PR updates field group to remove the additional checkbox read-only styles that were causing the box to not display and for commas to be appended.
- Template: added `aria-labeledby` connected to the group label, so this is announced as a group by the screen reader.
**Checkbox:**
- Removes some unnecessary read-only CSS. Read-only just needs to override disabled styles. It was confirmed with PJ on the design team that otherwise it uses default styles (for …
=> fix: correct the display of checkbox read-only state

.storybook/decorators/utilities.js, components/actionbutton/stories/actionbutton.test.js, components/button/stories/button.test.js, components/clearbutton/stories/clearbutton.test.js, components/link/stories/link.test.js
Expand test coverage for variants in static color modes.
- ActionButton: new static black & white tests covering default, emphasized, quiet
- Button: Updated format of testing to show fill & outline variants side-by-side with color variations together and then iterated over by state; new static white & static black tests iterate over more variants and states; truncation & line-wraps expanded
- ClearButton: Add quiet testing
- Link: Add static secondary testing
Other diffs relate to the update to the border color. 
=> chore(button,link): add more static color tests

.storybook/assets/404.html
This PR adds a custom `404.html` file to the static `assets` directory. Users may likely encounter several invalid links once we finalize our Storybook as our documentation site. This page aims to provide a link so users can get to the Storybook landing page and navigate to their components from there.
No changeset was added since no component CSS was altered.
[CSS-1054](https://jira.corp.adobe.com/browse/CSS-1054)
Before 🚫 
This is the default 404 page with a GitHub pages site.
After ✅ 
This is our custom 404 page.
- Note: this will navigate you back to the old docs site, as opposed to the Storybook landing page we have now. This URL should be the one Storybook …
=> chore(storybook): add 404 page

.changeset/spotty-onions-study.md, components/colorarea/index.css
`CSS-1032`
This change migrates the `colorarea` component to S2. It updates the `--spectrum-colorarea-border-radius` token to `--spectrum-colorarea-border-rounding`. Additionally, it leverages updated tokens and the `rgba(...)` color function, replacing the existing `TODO` and hardcoded values.
1. Run Storybook locally or open the link for the PR.
2. Navigate to the `colorarea` component.
3. Verify that no regressions are visible.
=> feat(colorarea): S2 migration

.changeset/afraid-ladybugs-smile.md, .changeset/twenty-tables-know.md, components/opacitycheckerboard/index.css, components/thumbnail/index.css, components/thumbnail/stories/template.js
`CSS-1056`
This is a follow up to CSS-1023, implementing the `thumbnail-opacity-checkerboard-square-size` that is specific to the `thumbnail` component but targeted at the `opacity-checkerboard`.
Adds thumbnail specific `--spectrum-opacity-checkerboard-size` token. This impacts the display of the `opacity-checkerboard` when used within the `thumbnail` component.
1. Run Storybook locally or open the link for the PR.
2. Navigate to the `thumbnail` component.
3. Verify that no regressions are visible.
Validate:
=> feat(thumbnail-opacity-checkboard): S2 migration

.changeset/silent-frogs-care.md, plugins/stylelint-theme-alignment/index.js, stylelint.config.js
=> feat(stylelint-theme-alignment): base filename input

components/coachindicator/stories/coachindicator.stories.js
This PR removes the "components/" from the title key of the coach indicator. This was causing the side nav to render a `components` folder, where `coachIndicator` was nested, instead of simply rendering the `Coach indicator` link.
Before 🚫 
After ✅ 
Validate:
=> chore(coachindicator): correct the title of coachindicator

.changeset/seven-dogs-help.md, .storybook/decorators/utilities.js, components/alertbanner/stories/alertbanner.test.js, components/buttongroup/stories/buttongroup.stories.js, components/picker/stories/picker.stories.js, components/picker/stories/picker.test.js, components/swatch/index.css, components/swatch/stories/swatch.stories.js, components/swatch/stories/swatch.test.js, components/swatch/stories/template.js, components/tabs/stories/tabs.test.js
Addresses #1460 
Open the [storybook](https://opensource.adobe.com/spectrum-css/?path=/story/components-swatch--default) for the swatch component:
Validate:
=> fix(swatch): support gradient input

components/icon/stories/template.js
Icons were not loading on the `spectrum-two` branch. The `require` statements in the `fetchIconSVG` function are not working, but that function no longer exists in `main`. This is a light touch update so icons appear for the current work, until `spectrum-two` is back up to date with main.
This updates the default `useRef` to true in the Icon component, so icons use the spritesheet version. `useRef` is not set to anything other than the default in the repo.
=> fix(icon): fix for icons not loading

.changeset/plenty-trees-act.md, .storybook/foundations/corner-rounding/action-button-corner-rounding.stories.js, .storybook/foundations/corner-rounding/checkbox-corner-rounding.stories.js, .storybook/foundations/corner-rounding/corner-rounding.stories.js, .storybook/foundations/down-state/button-down-state.stories.js, .storybook/foundations/down-state/checkbox-down-state.stories.js, .storybook/foundations/drop-shadow/drop-shadow.stories.js
Storybook foundations pages now display as a single page on the sidebar, as they did previously. This fixes the issue where they were appearing as folders with example stories nested within. These now use the newer `!dev` tag to hide them. The custom `foundation` tag was previously used to hide them, but this tag is no longer used.
This also fixes some linter errors that were encountered during commit; a couple unused variables and incorrect `typeof` comparisons.
=> fix: use new tag to hide storybook foundations stories

.changeset/slow-dogs-yawn.md, components/colorloupe/index.css, components/colorloupe/metadata/metadata.json
It was noted in #3409 that the color loupe shouldn't display when its color handle is disabled. If a user went to color handle, turned the `withColorLoupe` to true, then tried to disable the color handle, and the color loupe is still rendering. This PR aims to fix that by adding styles for disabled color loupes. There's also the corresponding changeset and udpates to the metadata.json.
Before 🚫 (color loupe testing grid/color handle testing grid)
After ✅ (color loupe testing grid/color handle testing grid)
[CSS-1089](https://jira.corp.adobe.com/browse/CSS-1089)
- Go to the [color loupe default story ](https://pr-3453--spectrum-css.netlify.app/?path=/story/components- …
=> fix(colorloupe): adds correct disabled styles

components/avatar/stories/avatar.stories.js
This PR updates the sizing documentation for avatar. There was an older table that listed the available sizes, but only for S1 avatars. The S2 avatar has more sizes available, so the Sizing story has now been updated to reflect that.
No changeset or VRTs needed since this was a documentation update only.
Validate:
=> docs(avatar): update sizing documentation

.storybook/preview.js
The `@whitespace/storybook-addon-html` seems to have started to double up on its line numbers, showing two complete sets of numbers when switching to the tab in the storybook console. Changing its config setting seems to fix the issue.
1. Pull this branch down locally and start Storybook (`yarn start`)
2. View any component's non-docs story or stories.
3. Validate that only one set of line numbers is shown for the source code.
Before!
After!
=> fix: resolve buggy line numbers display in addon

.changeset/tasty-pigs-tickle.md, .env.example, .storybook/blocks/ColorPalette.jsx, .storybook/blocks/ComponentDetails.jsx, .storybook/blocks/Layouts.jsx, .storybook/blocks/PropertiesTable.jsx, .storybook/blocks/Swatches.jsx, .storybook/blocks/ThemeContainer.jsx, .storybook/blocks/Typography.jsx, .storybook/blocks/index.js, .storybook/main.js, .storybook/package.json, .storybook/preview.js, .storybook/templates/DocumentationTemplate.mdx, package.json, tasks/chromatic-config-creation.sh, yarn.lock
Chromatic moved away from `@chromaui/addon-visual-tests` to the `@chromatic-com/storybook` package.
This requires an update to the `chromatic.config.json` settings, removal of the generic argTypesRegex from the preview config, and a stricter import in the doc blocks (i.e., `fileName.js` not just `fileName`).
To support a successful build, our test command must maintain the autodocs and mdx syntax which requires we add this information to our build instructions in the .storybook/main.js file.
Expect to be able to run Storybook locally, connect to the Chromatic add-on in the component panel, and kick off a manual re-run of VRTs.
=> feat(storybook)!: update chromatic add-on to latest version

components/combobox/stories/template.js, components/pickerbutton/stories/template.js
The Picker Button that is nested within Combobox was previously tab focusable, separately from the Combobox itself. This update gives it a negative `tabindex`, making it consistent with the intended behavior and SWC implementation. This adds a `tabindex` option to the Picker Button template to facilitate this change.
Validate:
=> docs(combobox): remove separate tab focus for nested pickerbutton

.changeset/shiny-files-chew.md, components/menu/dist/metadata.json, components/menu/index.css, components/menu/themes/spectrum-two.css, components/menu/themes/spectrum.css
This PR addresses the incorrect border radius for menu items in Spectrum 2, by updating the value to be `corner-radius-100` (`8px`) to align with the Spectrum 2 designs.
1. Open the [storybook](url) for the menu component:
2. - [ ] Verify the correct 8px rounding is applied to menu items in the hover, down, and keyboard states.
Validate:
=> fix(menu): update menu item border radius

.storybook/package.json
Fixes an issue where we were still linking to the old project URL (which included `/preview`).
Validate:
=> fix: use updated project url for logo link

.changeset/tame-wasps-shake.md, tokens/dist/css/global-vars.css, tokens/dist/css/index.css, tokens/dist/index.css, tokens/package.json, yarn.lock
Uses the latest tokens release.
Release details here: https://github.com/adobe/spectrum-tokens/releases/tag/%40adobe%2Fspectrum-tokens%4013.0.0-beta.56
=> chore(tokens): use spectrum-tokens@13.0.0-beta.56

.changeset/strong-actors-warn.md, components/page/themes/express.css, components/textfield/dist/metadata.json, components/textfield/index.css, components/textfield/themes/spectrum-two.css, components/textfield/themes/spectrum.css
This PR addresses SWC-574 and updates the textfield border radius and background-color and adds the respective `--mod` property.
1. Open the [storybook](url) for the textfield component:
2. - [ ] Verify the correct background color and border color for Default, Hover, Focus Hover and Disabled state.
Validate:
=> fix(textfield): update border and background color

components/picker/stories/picker.stories.js, components/picker/stories/template.js, components/tooltip/stories/template.js
This PR reimplements some fixes for the `spectrum-two` branch after a rebase. 
1. Adds a missing `variant = "neutral"` default arg to the tooltip template. This should alleviate the errors on the docs page.
Before 🚫 
After ✅ 
2. An additional fix on the steplist docs page occurred since the `WithTooltip` story calls for the tooltip component. 🥳 
Before 🚫 
After ✅ 
3. The calls to `window.isChromatic` have been removed.  It also corrects the arg names for picker, in order for them to be properly passed to the popover used in the template and render the content. This should alleviate all errors and most of the missing content on the docs page. (additional styling and content changes will need to be addressed in a separate PR).
Before 🚫 
After ✅ 
4. An additional fix on the form docs page …
=> chore: spectrum-two fixes

components/opacitycheckerboard/stories/template.js
- Resolves linting error in opacitycheckerboard: `'size' is assigned a value but never used  no-unused-vars`
Validate:
=> fix: resolve s2 branch build errors

.changeset/flat-snails-admire.md, components/button/stories/template.js, components/combobox/stories/template.js, components/infieldprogresscircle/README.md, components/infieldprogresscircle/dist/metadata.json, components/infieldprogresscircle/index.css, components/infieldprogresscircle/package.json, components/infieldprogresscircle/project.json, components/infieldprogresscircle/stories/infieldprogresscircle.stories.js, components/infieldprogresscircle/stories/infieldprogresscircle.test.js, components/infieldprogresscircle/stories/template.js, components/picker/stories/template.js, components/textfield/stories/template.js, tools/bundle/package.json, tools/bundle/src/index.css, yarn.lock
The infield progresscirlce is a subcomponent of the progress circle which is used in button, combobox, textfield and picker template files. It's smaller in block size and has its own t-shirt sizing.
1. Open the storybook for the infield progress circle:
Validate:
=> feat(infield-progress-cirlce): new component, sharing tokens from progress circle

components/popover/dist/metadata.json
Adds a missing change to a metadata file that is generated after `yarn build`.
=> chore(popover): add missing metadata update from build

.changeset/metal-bees-bake.md, components/button/themes/spectrum.css
Reverts S1 and Express Primary filled button content color to use the [same tokens](https://github.com/adobe/spectrum-css/blob/3182da4812ed183b163739a956ebbc290ae19328/components/button/themes/spectrum.css#L130) it used prior to Foundations. Because the primary button is a gray color in both dark and light themes, content color should be white regardless of theme.
Current `main` branch:
Previous `main` [(before foundations)](https://pr-3524--spectrum-css.netlify.app/?path=/story/components-button--default&globals=color:dark;testingPreview:!true):
Current PR:
Note that the design [spec](https://spectrum.adobe.com/page/button/) calls for the `neutral-content-color-default`, `neutral-content-color-hover`, etc. to be used--these appear not to have been used because they work nicely in the …
=> fix(button): revert primary button content color

components/dialog/stories/dialog.stories.js
This PR correctly implements the `isOpen` shared type on the dialog pages. This should correct the display of the `isOpen` control.
Validate:
Before 🚫 
After ✅
=> chore(dialog): use isOpen type for open control

components/splitview/package.json
After talking with the design team, Jess liked the idea of CSS's split view component linking to the "drag bars and thumbs" contribution page.
This continues the work from [CSS-772](https://jira.corp.adobe.com/browse/CSS-772) where we were linking CSS components to their design guidelines on the Spectrum or Spectrum contributions site.
No changeset is included with this PR since it affects the package.json only.
[CSS-963](https://jira.corp.adobe.com/browse/CSS-963)
[Slack thread](https://adobedesign.slack.com/archives/G01P2PHJMC6/p1738605814936429?thread_ts=1738603928.182389&cid=G01P2PHJMC6) (about asset list and split view)
Validate:
1. The documentation pages for …
=> docs(splitview): add guidelines link

.changeset/ten-owls-beam.md, .storybook/package.json, yarn.lock
To allow external projects to leverage our assets (such as our lovely doc blocks), internal references need to be explicit instead of using "workspace:^" or it throws an error when trying to install.
Expect no regressions in VRTs or the docs site.
Validate:
=> fix(storybook): remove workspace dependency references

components/combobox/stories/combobox.stories.js, components/combobox/stories/combobox.test.js
`CSS-1132`
Fixes spacing for open combobox tests and stories.
- Adds fixes size to `parameters.docs.story` in combobox story file.
- Adds `min-inline-block-size` to `wrapperStyles` for `open` stories.
1. Open the branch preview.
2. Navigate to the `combobox` docs.
3. Verify that `open` component variations do not overlap adjacent components.
4. Open the `combobox` component and enable the testing preview view.
5. Verify that `open` component variations do not overlap adjacent components.
=> test(combobox): corrects cases where open combobox stories and testing previews could overlap adjacent components

.changeset/slow-eyes-lay.md, components/divider/dist/metadata.json, components/divider/index.css, components/divider/stories/divider.stories.js, components/divider/stories/divider.test.js, components/divider/stories/template.js
`CSS-708`
This migrates the `divider` component to S2. Custom properties have been remapped and updated per the design spec.
```css
--spectrum-divider-horizontal-minimum-width
--spectrum-divider-vertical-minimum-height
```
```css
--mod-divider-inline-minimum-size
--mod-divider-block-minimum-size
```
```css
--mod-divider-background-color-large-static-black
--mod-divider-background-color-large-static-white
--mod-divider-background-color-medium-static-black
--mod-divider-background-color-medium-static-white
--mod-divider-background-color-small-static-black
--mod-divider-background-color-small-static-white
```
This adds new minimum width and height tokens for the divider and the `minDimensionValues` arg has been removed in favor of these tokens and the rules with which they're applied.
The …
=> feat(divider): S2 migration

.changeset/giant-windows-smoke.md, components/colorwheel/dist/metadata.json, components/colorwheel/index.css, components/colorwheel/stories/colorwheel.stories.js, components/colorwheel/stories/colorwheel.test.js, components/colorwheel/stories/template.js
`CSS-1020`
This change migrates the colorwheel component to S2. It adds the `--spectrum-colorwheel-border-color-rgb` and `--spectrum-colorwheel-border-opacity` custom properties. It updates `--spectrum-colorwheel-border-color` to leverage these tokens in an `rgba(...)` function.
1. Run Storybook locally or open the link for the PR.
2. Navigate to the `colorwheel` component.
3. Verify that no regressions are visible.
Validate:
=> feat(colorwheel): S2 migration

.changeset/odd-seahorses-hunt.md, components/checkbox/dist/metadata.json, components/checkbox/themes/spectrum-two.css, components/checkbox/themes/spectrum.css
Update deselected border color of checkbox to neutral.
[SWC-498](https://jira.corp.adobe.com/browse/SWC-498)
Include steps for the PR reviewer that explain how they should test your PR. Example test outline:
1. Open the [storybook](https://pr-3573--spectrum-css.netlify.app/?path=/story/components-checkbox--default) for the component:
- [  ] Verify that the `--system-checkbox-control-color-default` is now pointing to `var(--spectrum-neutral-content-color-default)` for s2
Validate:
=> fix(checkbox): update box color to neutral in s2

.changeset/green-ghosts-collect.md, components/menu/dist/metadata.json, components/menu/index.css
Resolves an issue with the focus indicator for S1 and Express, in which the focus indicator appears on the left side for both LTR and RTL modes. The focus indicator in these themes should always be on the start-side, therefore, it should appear on the left side for LTR, and on the right side for RTL. This was something we overlooked in #3530.
This changes the scope of `--spectrum-menu-item-focus-indicator-direction-scalar` so that it can be used in the definition for `--spectrum-menu-item-focus-indicator-border-width`.
This does in some cases make `--spectrum-menu-item-focus-indicator-border-width` negative, which causes issues for `outline` and `margin` properties using it, so those have been reverted to use `--spectrum-menu-item-focus-indicator-width` instead. …
=> fix(menu): move s1/express focus indicator to right side for rtl

README.md
Corrects the path in the project readme to point to the relocated image file.
=> fix(readme): corrects path to css illutration png in readme

.changeset/shaggy-dragons-visit.md, components/stepper/themes/spectrum-two.css
updated stepper Default variant, Key focus state border color to gray-800
[swc-576](https://jira.corp.adobe.com/browse/SWC-576)
1. Open the [storybook](https://pr-3594--spectrum-css.netlify.app/?path=/story/components-stepper--default&args=isKeyboardFocused:!true) for the stepper component:
Validate:
=> chore(stepper): update default variant, key focus state in s2

yarn.lock
After our most recent merge, the `yarn.lock` hadn't been updated and CI was failing.
Validate:
=> chore: regenerate yarn.lock after merge

lint-staged.config.js
This PR adds the `yarn` command after `yarn constraints --fix` is invoked in `lint-staged.config.js` to ensure that the lock file is updated and to help prevent build failures.
We'll need to monitor release PRs to verify that this addresses failures when generating release PRs.
=> fix(lint-staged): add yarn command to lint staged to ensure the lock file is updated

.changeset/angry-boats-walk.md, components/picker/dist/metadata.json, components/picker/themes/spectrum-two.css
Updated border-color for Open not hover state of picker from --spectrum-gray-900 to --spectrum-gray-800 as specified in the spec
https://jira.corp.adobe.com/browse/SDS-14609
https://jira.corp.adobe.com/browse/SWC-641
Include steps for the PR reviewer that explain how they should test your PR. Example test outline:
1. Open the [storybook](https://pr-3607--spectrum-css.netlify.app/) for the button component:
Validate:
=> chore(picker): updated border-color for open not hover state of picker

.github/workflows/release.yml, lint-staged.config.js, package.json
This PR modifies the `version:packages` command to run `yarn constraints --fix && yarn install` after `changeset version`. This command now runs in `release.yml` prior to the execution of `yarn release`.
We'll need to monitor release PRs to verify that this addresses failures when generating release PRs.
=> fix(constraints): run constraints and update lockfile

components/slider/stories/template.js
Corrects the contrast issue observed between the fill element and slider track that caused the fill element to be difficult to see.
- Adjusts colors per design feedback.
- Removes default control/template value that caused contrast issue in dark modew.
1. Open Storybook URL
2. Navigate to slider
3. Change theme from light to dark
4. Enable testing preview
5. Scroll to filled offset and verify offset and track have sufficient contrast
=> fix(slider): corrects contrast bug caused by template default arg

.changeset/sharp-spiders-complain.md, components/stepper/themes/spectrum-two.css
SWC got some design feedback on stepper for S2 foundations to "update the stepper focus hover border color to gray-900 (currently its 800)." This PR should address that by updating the values for `focus-hover` from `gray-800` to `gray-900`, as well as update the stepper buttons' border color for `keyboard-focus` to `gray-800`, matching the nested textfield's keyboard-focus color.
This work relates to [SWC-576](https://jira.corp.adobe.com/browse/SWC-576) and [SWC-501](https://jira.corp.adobe.com/browse/SWC-501) I believe. 🤔 
[PR description and validation instructions](https://adobe-my.sharepoint.com/:v:/p/for00418/EW81Rx6hYlRAmWrGrzJTeqsBFEK5zabyIBllmXUC8Izl5Q?e=e0kjfF)
Please tag yourself on the tests you've marked complete to confirm the tests have been run by someone other than the …
=> fix(stepper): focus/focus+hover/keyboardFocus border colors

.changeset/rude-jokes-judge.md, components/slider/dist/metadata.json, components/slider/index.css
The border radius styles were not being applied to the second instance of the `spectrum-Slider-track` when the offset variant is activated. The reason for this bug is because when the `offset` is selected, the template structure changes as `spectrum-Slider-fill` gets added to the slider. 
Adding a sibling combinator `&~.spectrum-Slider-track` to `spectrum-Slider-track` when offset is activated resolved the issue.
Validate:
=> fix(slider): offset variant border radius bug fix

.changeset/breezy-crews-guess.md, components/combobox/dist/metadata.json, components/combobox/index.css, components/combobox/themes/express.css, components/combobox/themes/spectrum-two.css, components/combobox/themes/spectrum.css
Some design feedback on the s2 foundations combobox included border color fixes. This PR aims to address those!
- In the default variant, focus+hover state (not shown in the testing grid):
- border should resolve all the way to `gray-900` (via `--spectrum-combobox-border-color-focus-hover`)
---
- In the default variant, focus state: 
- border color should resolve to `gray-800` (via `--spectrum-combobox-border-color-focus`)
---
- In the default variant, keyboard focus state: 
- border should resolve to `gray-800` (via `--spectrum-combobox-border-color-key-focus`)
---
- In the default variant, disabled state: 
- the background color should resolve to `gray-25` (by way of some textfield mods and `--spectrum-combobox-background-color-disabled`)
- the border color should resolve to `gray-300` …
=> fix(combobox): border color fast follows swc-582 

.github/workflows/development.yml
Due to a high vulnerability security issue with the tj-actions package for changed-files, that GitHub Action has been blocked in our allowlist. To retain this functionality, we have leveraged the patched clone by step-security, as documented [here](https://www.stepsecurity.io/blog/harden-runner-detection-tj-actions-changed-files-action-is-compromised).
=> chore: patch tj-actions vulnerability

.changeset/metal-eels-protect.md, components/alertbanner/themes/spectrum.css
Noted in #3609, we found that the alert banner contained `--system: spectrum` (which should indicate S2 design/theming) in the `spectrum.css` or S1 stylesheet. This PR corrects that 👍 
No style changes should have occurred in this work.
- If the combobox spectrum.css file gets return for having `--system: spectrum` in the S1 file, this is addressed in #3609.
Validate:
=> fix(alertbanner): change system variable from spectrum to legacy

components/checkbox/stories/checkbox.stories.js, components/checkbox/stories/checkbox.test.js, components/checkbox/stories/template.js, components/form/stories/form.stories.js
This PR adds several tests and more Storybook support for hovers through the shared type control. Additionally, this PR should address the regressions found on the form docs page, where some inputs (based on work from https://github.com/adobe/spectrum-css/pull/3227 and https://github.com/adobe/spectrum-css/pull/3165) no longer had labels.
Related: [CSS-1139](https://jira.corp.adobe.com/browse/CSS-1139)
- `checked+hovered`
- `invalid+checked+hovered`
- `disabled+checked+hovered`
- `readonly+checked+hovered`
Validate:
2. If components have been modified, VRTs have been run on …
=> test(checkbox): add more coverage for checkbox

.changeset/blue-wasps-talk.md, components/checkbox/dist/metadata.json, components/checkbox/index.css
This PR addresses the regression we noticed in the invalid checkboxes, where the default hover color was "winning" out over the invalid hover color. To avoid this bug in the future, #3625 adds several tests and more Storybook support for hovers through the shared type control.
This PR includes adding a `::before` selector in the `is-invalid` hover state.
It should be noted that there is more opportunity to refactor here. I noticed that the emphasized+invalid+checked+hovered state was behaving as expected. If that selector block (marked with a `TODO` in commit https://github.com/adobe/spectrum-css/pull/3617/commits/ea8741a7f04a8bfa3b2a6deb6d18452ba7cb1d29) gets consolidated or moved into the default `.spectrum-Checkbox`, it seemed like it could safely be removed and all the styles would …
=> fix(checkbox): corrects invalid+checked+hover background color

.changeset/kind-walls-fix.md, components/pickerbutton/dist/metadata.json, components/pickerbutton/themes/spectrum-two.css
Further design feedback was given regarding the nested picker button within combobox:
Default state: gray-100 background color expected.
Button: Hover state: gray-200 background color expected.
Button: Down state: gray-200 background color expected.
Button: Keyboard focus state: gray-200 background color expected.
This PR addresses these requests and fixes the custom property references within picker button's `spectrum-two.css` theme file.
[SWC-582](https://jira.corp.adobe.com/browse/SWC-582)
[Figma SWC feedback](https://www.figma.com/design/JAyGhxAD6s9mD6vbTJNVHD/Design-QA-for-SWC-foundations?node-id=399-10335&m=dev)
[Slack thread (in temp-s2-foundations-delivery)](https://adobedesign.slack.com/archives/C06Q3G5HJUX/p1742248946161009?thread_ts=1741699553.838139&cid=C06Q3G5HJUX)
Please tag …
=> fix(pickerbutton): correct states' background colors

.changeset/stale-pans-carry.md, components/tooltip/dist/metadata.json, components/tooltip/index.css, components/tooltip/stories/template.js, components/tooltip/stories/tooltip.stories.js, components/tooltip/stories/tooltip.test.js
This restores the negative and informative tooltip semantic variant styles, story controls and test cases. Icons have been removed for all variants as they are not present in the specifications provided by design.
`--mod-tooltip-background-color-informative`
`--mod-tooltip-background-color-negative"`
1. Open the Storybook link for this PR.
2. Navigate to the `Default` story for the tooltip component.
3. Select the informative and negative tooltip styles in controls and verify that they match the Figma design(s).
=> fix(tooltip): restore negative and informative semantic variants

.changeset/popular-trains-sniff.md, components/infieldbutton/dist/metadata.json, components/infieldbutton/index.css, components/infieldbutton/themes/spectrum-two.css, components/infieldbutton/themes/spectrum.css
The design feedback for number field revealed some requests regarding the border colors of the stepper/number field, and most recently related to the nested infield button. This PR aims to address that feedback.
Updates the value of disabled border of infield-button
```
Disabled state (in-field button)
Expected: gray-300 border
```
Additional feedback included: 
- Focus hover state (textfield)
_Expected: gray-900 border_ ✅ 
- Default state (in-field button)
_Expected: gray-100 button background_ ✅ 
- Disabled state (in-field button)
_Expected: gray-300 border_ ✅ 
- Hover state (in-field button)
_Expected: gray-200 button background_ ✅ 
- Key focus state (in-field button)
~~_Expected: gray-200 button background_
_Expected: gray-900 chevron color_~~
The green checkmarks above are styles …
=> fix(infield-button): updated border color for disabled state

.changeset/happy-frogs-flash.md, components/button/themes/spectrum.css
Adjusts S1/Express themes' static outline button content colors back to their original--they should deviate from S2 designs and be solid colors rather than having transparency.
1. Open the PR [preview](https://pr-3665--spectrum-css.netlify.app/?path=/story/components-button--default&globals=testingPreview:!true) and verify: [@castastrophe]
Validate:
=> fix(button): s1/express static outline variant content color

stylelint.config.js
Fixes large number of stylelint warnings appearing after yarn start. These were the result of stylelint running on the
`tools/bundle/dist/index.module.css` file.
- Adds stylelint override to better lint module files that have a different class format.
- Add ignoreFiles for the tools/bundle/dist, as stylelint should not be running on the dist folders during this step; it seems to be disregarding the .stylelintignore file.
CSS-1155
Pull down the branch locally and:
Original problem:
=> fix: reduce excess stylelint warnings from bundle module

.changeset/honest-animals-stop.md, components/fieldlabel/index.css, components/fieldlabel/stories/fieldlabel.stories.js, components/fieldlabel/stories/template.js
Addresses case where fieldlabel required icon could appear on its own line when wrapping by applying text-wrap: pretty; to the parent label class.
1. Open the storybook link for the PR.
2. Navigate to the `fieldlabel` component.
3. Enable the `Required` control.
4. Adjust the contents of the `Label` control and verify that the `Required` icon does not render on a line separate from the text when it wraps.
=> fix(fieldlabel): prevent required icon from appearing on its own line when wrapping

.github/workflows/development.yml, .storybook/assets/base.css, tasks/clean-up-after-migration.sh, tokens/utilities/data-json-formatter.js
Hind-sight is 20:20! I found a couple super minor updates to the scripts I recently worked on for the style-dictionary and Windows compatibility effort. I added notes inline to the code to help clarify these updates. It should just ensure we get more predictable results.
Validate:
=> chore: harden recently updated scripts

components/popover/stories/popover.stories.js, components/popover/stories/popover.test.js
This PR corrects the spelling of the `dismissible` arg in the dialog-style popover. In #https://github.com/adobe/spectrum-css/pull/2860, the arg spelling was updated, and we must have missed correcting the spelling in this popover story. 
Validate:
=> chore(popover): fix dismissible spelling

.github/workflows/development.yml
Bringing over the markdown lint variable fix in the GitHub Actions workflow. We expect this to help limit the scope of what the markdown lint GitHub tool will flag for changes in a pull request.
=> chore: update with latest from main

components/actionbutton/stories/actionbutton.stories.js, components/breadcrumb/stories/breadcrumb.stories.js, components/checkbox/stories/checkbox.stories.js, components/coachmark/stories/coachmark.stories.js, components/colorhandle/stories/colorhandle.stories.js, components/colorslider/stories/colorslider.stories.js, components/colorwheel/stories/colorwheel.stories.js, components/divider/stories/divider.stories.js, components/dropzone/stories/dropzone.stories.js, components/fieldgroup/stories/fieldgroup.stories.js, components/helptext/stories/helptext.stories.js, components/icon/stories/icon.stories.js, components/illustratedmessage/stories/illustratedmessage.stories.js, components/infieldbutton/stories/infieldbutton.stories.js, components/infieldprogresscircle/stories/infieldprogresscircle.stories.js, components/inlinealert/stories/inlinealert.stories.js, components/link/stories/link.stories.js, components/meter/stories/meter.stories.js, components/popover/stories/popover.stories.js, components/progresscircle/stories/progresscircle.stories.js, components/radio/stories/radio.stories.js, components/rating/stories/rating.stories.js, components/search/stories/search.stories.js, components/textfield/stories/textarea.stories.js, components/textfield/stories/textfield.stories.js, components/toast/stories/toast.stories.js
Some of our migrated components from 2024 (like textfield, search, switch, button, etc), had the migrated tag added to the components' metadata. You could find `tags: ["migrated"]` in the story files. However, at some point we stopped adding that tag, and because we've gotten back to migrated S2 components, it would probably be good to add this tag to all of our currently migrated components.
This work adds that migrated tag to the components that are missing it as of 5 May 2025. 
CSS-1191 (ticket for this work)
CSS-604 (epic for S2 Migration)
Validate:
2. If components have …
=> docs: adds tag for migrated components

components/menu/stories/menu.stories.js
Adds the migrated status to the metadata for the menu component.
Validate:
=> docs(menu): add migrated status badge

.github/renovate.json
I noticed that the renovate tool is bumping the lock files but not reflecting the update in the packages. This configuration setting should remedy that: https://docs.renovatebot.com/configuration-options/#bumpversion
=> chore: renovate config to bump packages with updates

.github/renovate.json
This update did not function as we expected. The setting in question is now attempting to bump the version of our repo's packages when dependencies are updated.
=> chore: revert renovate config to bump packages with updates

.changeset/dirty-melons-look.md, components/swatch/stories/template.js
When the `swatch` component was originally migrated we only had the `workflow` add icon. This updates the component to use the `ui` icon now that the latter is available.
=> chore(swatch): updates the add swatch icon to use the ui rather than workflow icon

.changeset/public-facts-boil.md, components/taggroup/dist/metadata.json, components/taggroup/index.css, components/taggroup/stories/taggroup.stories.js, components/taggroup/stories/taggroup.test.js, components/taggroup/stories/template.js
The Spectrum 2 version of Tag Group is a major change from its Spectrum 1 counterpart.
- Use of new tokens and custom properties for spacing tags. The method of spacing between tags has changed. Where previously tags were spaced using tokens to represent inline and block margins on each tag, tags are now spaced by tokens representing the gaps between tags.
- Rather than being a single size, Tag group now comes in t-shirt sizes: Small, medium, and large. These sizes should determine the sizes of the embedded components, but also the spacing between tags.
- Tag group can now accommodate a side label. To do so, it makes use of a grid layout.
- In order to match the layout in the spec, more embedded components besides Tag have been added. Field label, Help text, and Action button (quiet) …
=> feat(taggroup): spectrum 2 migration

.github/workflows/publish-site.yml
`CSS-1249`
<mark>Verified: closed this PR, checked Azure admin and clean up succeeded. Pertinent run: https://github.com/adobe/spectrum-css/actions/runs/15861350315</mark>
=> fix(azure-preview-workflow): update resource url to remove + use same token pattern

lint-staged.config.js
This fixes the `prettier` portion of our lint stage hooked by removing the `--no-config` flag that conflicts with the final `--config .prettierrc` flag.
Verified by removing the flag in question and running a test commit.
1. Pull down the branch.
2. Install project dependencies using `yarn`.
3. Make a small change to a `*.css` file.
4. Commit the file to verify the lint-staged hook runs successfully.
5. Reset your branch. Do not push the change.
=> fix(lint-staged): remove conflicting flag for prettier command

.changeset/chubby-mirrors-wish.md, components/sidenav/index.css, components/tooltip/index.css
_[Aligns with PR](https://github.com/adobe/spectrum-web-components/pull/5504) by @castastrophe on SWC_
Replace deprecated `word-break: break-word` with `overflow-wrap: break-word` to align with modern CSS standards and improve cross-browser compatibility. This property was deprecated in Chrome 44 (July 2015) in favor of the standardized [overflow-wrap](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap) property.
Validate:
=> fix(tooltip,textfield,sidenav): update deprecated css

package.json, yarn.lock
When validating a renovate update of our dependencies, I noted that we are no longer using the @nx/devkit utilities in this repository. Removing this should cause no deprecations or issues with our build.
=> chore(deps): remove unused @nx/devkit dependency

.changeset/config.json, .github/workflows/development.yml, plugins/changesets-changelog-github/index.js, plugins/changesets-changelog-github/package.json, plugins/changesets-changelog-github/project.json, plugins/changesets-changelog-github/test.js, tokens/project.json, yarn.lock
This PR implements a custom changesets changelog plugin for GitHub that improves the changelog generation process. The changes include:
- **Custom changelog plugin**: Created `@spectrum-tools/changesets-changelog-github` plugin to replace the standard `@changesets/changelog-github`
- **Enhanced formatting**: Added emoji prefix (📝) and improved spacing in changelog entries
- **Better commit handling**: Simplified commit link generation and improved test coverage
- **CI integration**: Added distinct GitHub token environment variable for plugin's access to user's GitHub username and reading pull request titles.
The plugin provides better control over changelog formatting and ensures consistent output across releases.
Please tag yourself on the tests you've marked complete to confirm the …
=> chore: custom changesets plugin

.yarnrc.yml, package.json, yarn.lock
Reference: https://github.com/abbr/deasync/issues/181
Remove this unused dependency.
I validated the following commands to ensure this removal did not introduce regressions:
=> chore(deps): remove unused node-gyp

.github/GUIDE.md, .github/workflows/development.yml, .github/workflows/production.yml, .gitignore
`CSS-1263`
Minor documentation and comment changes to remove lingering Netlify references on the `spectrum-two` branch. Netlify is changed to Azure where appropriate and a comment in the `.gitignore` was updated as, while the rule is still valid, we haven't used 11ty for documentation in some time.
=> docs(.git*): removes remaining reference(s) to Netlify in the codebase

.storybook/guides/s2_migration.mdx
This PR adds a small section of documentation regarding S2-migrated components. There is a built in filter in the Storybook toolbar for tags, so the docs point consumers to that filter.
CSS-1259
Validate:
=> docs(storybook): add documentation to filter s2 components

.github/workflows/development.yml, .github/workflows/lint.yml
A few minor CI updates for linting:
- Remove *.mdx files from markdownlint as they don't adhere to the same guidelines
- Add the eslint config
- Only run markdownlint if markdown files are present
=> chore(spectrum-two): config ci updates

.github/GUIDE.md, .github/renovate.json, .github/workflows/build.yml, .github/workflows/compare-results.yml, .github/workflows/development.yml, .github/workflows/lint.yml, .github/workflows/production.yml, .github/workflows/publish-site.yml, .github/workflows/release-snapshot.yml, .github/workflows/release.yml, .github/workflows/vrt.yml, .gitignore
A few minor CI updates to align with latest changes here and in S2:
- update documentation references to Azure instead of Netlify
- bump actions to latest versions (already tested for S2)
- update lockfile added to renovate to ensure dependencies like caniusedb get updated on a regular cadence
=> chore(main): github actions minor ci updates

.changeset/sweet-badgers-melt.md, components/accordion/dist/metadata.json, components/accordion/index.css, components/accordion/stories/accordion.stories.js, components/accordion/stories/accordion.test.js
Resolves the previous issue with accordion where, when the action button was added to an item's direct actions area, the action button was taller than the accordion item's height. (This was only an issue with compact XL.)
The updates made to accordion adjust the spacing tokens so that the action button always fits within the accordion item, although its focus outline may be outside of the accordion item (just as the accordion item's focus outline is outside of the item).
After confirming with design, the tokens used for minimum height have been updated to be more spacious, which better matches the designs. Note that these tokens aren't always used; there is a calculation that sets the min height to the maximum between the token or the sum of the space needed (top & bottom padding + …
=> fix(accordion): clean up spacing issues
