adobe/spectrum-css

src/circleloader/index.css
Fixing rtl issue with Circle Loader
#46 
Circle Loader was broken when using rtl attr
Tested locally
=> Fix circle loader rtl layout issue, fixes #46

README.md, package-lock.json, package.json, scripts/prepare-artifactory-release.js, scripts/prepare-release.js
Automated some of the release process. Check out the readme changes for the new release process. 
Created two scripts. 
The first script handles updating the version, tagging, committing, pushing commits and tags to git. We may want to split out the pushing to git part into its own command. 
The second script handles updating the package scope in `package.json` for the artifactory release. It also installs the internal only dependency of spectrum-icons. 
I don't have anything about docs release in this yet.
https://github.com/adobe/spectrum-css/issues/44
=> Added new release scripts

src/accordion/index.css
Fixed #79 by adding display: block to spectrum-Accordion-itemHeader
#79 
I test this change with customer element tag in Angular.
=> Fixed #79 by adding display: block to spectrum-Accordion-itemHeader

README.md
I'm not exactly sure if the wording and accuracy here is quite right, so would appreciate a review from a core contributor!
=> 📝 updating link to spectrum icons in readme to point to non-internal url

README.md
Changed 'pacakage' to 'package' in the README
=> changed spelling

README.md, package-lock.json
Added directions about how to install spectrum-css into a project.
#127 
I used Spectrum CSS for the first time today, and spent a good chunk of time just trying to find/figure out the command to add Spectrum CSS as a dependency in my project. I ended up needing to ask a coworker who I knew used it. I think it would be helpful to have that command in the README for this project. Let me know if you'd like to change the wording of my addition. No offense will be taken!
Because it was a simple README addition and doesn't affect the code, the only testing I did was viewing the preview and double checking that it was the only thing I changed.
=> :memo: Added terminal command for installation to README, closes #127

src/table/index.css, src/table/skin.css
`td` is getting focused when `number-input` is clicked on, see https://git.corp.adobe.com/pages/Coral/coral-spectrum/dist/playground/#?livereload=true&screen=vertical&code=MTk3LDg0LDE5MywxMTAsMjE5LDQ4LDEyLDYxLDE2Nyw5NSwxNjEsMjMzLDE0OCwwLDE3OSwxMTcsMjIzLDI4LDMsNzUsOTAsMTE2LDI0LDE4Niw0NSw3LDk1LDExOCwxNDgsMzcsMzgsODYsMzgsNzUsMTM0LDY4LDUzLDQ4LDEzNCwyNTMsMjUxLDEwMCwxNzEsMTA1LDg2LDM2LDMsMjgsMTgwLDE5MiwxMiwxOTUsMTYyLDE1OCwyMDAsMjQ3LDcyLDEzOCwxMTIsMjQxLDIzOCwyNDYsMjUxLDE4NiwyNTAsMTc3LDE4NSwzNSwxMywxODIsMTg2LDE4OCw0MSwxNDIsMTEsMTEyLDg5LDIyMiwxNiw4MiwxMDQsMTAxLDEyNiwxOCw3LDEyMiw3Myw2MSwyNDYsMjYsMTI0LDMsMTI4LDE0OCw1MiwxNCwxODIsNzUsMjE4LDMyLDExOCwyNTQsMyw5OSw1OSwxMzMsMTg1LDE3NiwxNzQsMjAzLDE4NSwxODAsNTMsNjgsMTc5LDEwMSwyOSwyMjMsMTI5LDEwMywxMDcsMjM1LDE4NCwxMDIsOTgsMjQ4LDEwMiwxOTAsMywxMjksNDYsMTgwLDc2LDQy …
=> 🐛 disable focus ring for td when content inside of td is being focused

gulpfile.js, scripts/prepare-artifactory-release.js, scripts/prepare-release.js, tasks/build-backstop.js, tasks/build-css.js, tasks/build-docs.js, tasks/build.js, tasks/clean.js, tasks/copy-loadIcons.js, tasks/copy-vars.js, tasks/dev.js, tasks/gh-pages.js, tasks/icons.js, tasks/lib/dumpfile.js, tasks/lib/plumb.js, tasks/lib/postcss-custom-properties-mapping.js, tasks/lib/postcss-custom-properties-passthrough.js, tasks/lib/postcss-notnested.js, tasks/lib/postcss-varsonly.js, tasks/lib/postcssdiff.js, tasks/lib/vars.js, tasks/lint.js, tasks/sass-compile.js, tasks/test-backstop.js, tasks/test.js, topdoc/lib/index.js, topdoc/lib/npm_pug_plugin.js, topdoc/resources/js/docs.js
this closes #145 - adding apache source code headers to JS files
#145
=> 💼 add apache 2 source code headers to js files

tasks/build-css.js
Basically, the glob being passed to concat wasn't ordered, so we would get inconsistent output between builds. This change fixes that by explicitly ordered the glob, and ignores non-directories in figuring out what components to process.
#149 
The build was breaking randomly.
I ran the following command over and over:
```
rm -rf dist1 dist; gulp build-css:individual-components-vars; cp -r dist dist1; gulp build-css:individual-components-vars; diff -rq dist dist1
```
No output = success
=> Make sure glob passed to concat for vars is ordered

package-lock.json, package.json
=> updated topdoc

docs/rule/rule.yml, src/rule/index.css
This PR adds support for vertical Rules. The examples are a bit silly, but they're there.
#198 
This was needed for the App Frame prototype #157 
iScrolled
- New feature (non-breaking change which adds functionality)
=> Vertical Rule

components/tags/index.css, package-lock.json
Tags use a float and a clear, but are already inline-flex so it's unnecessary and has caused some issues.
=> Removed float from tags

tools/bundle-builder/subrunner/index.js
As reported by @majornista, refactoring resulted in a reject() that should have just been a throw
- How this was tested: code executed on brain
=> build: fix error handling in subrunner

site/resources/js/site.js
This implements feedback from design re: automatic scale switching when resizing the window.
- **How this was tested:** resize window, look at scale switcher, smile
=> docs: fix scale switcher dropdown state when resizing window

site/README.md, tools/conventional-changelog-spectrum/CHANGELOG.md
Fixed a few typos in Markdown files.
=> Fixed typos in markdowns

README.md
issue #310 
changed continuous to continous (https://www.quora.com/Which-one-is-spelled-correctly-continous-or-continuous)
changed varaibles to variables
- using Github preview option as this is simple typo fix.
=> Update README.md - typo fixes

components/site/index.css, site/includes/sidebar.pug
This PR updates the Adobe logo color and SVG. 
**WIP:** Waiting on branding to give us one that renders nice at 36x36.
- **How this was tested:** Eyes on it
- **Browser(s) and OS(s) this was tested with:** Chrome 77 on macOS
=> docs: update Adobe logo

backstop_data/backstop_scenarios.json
=> test: increase misMatchThreshold to 0.11 for typography and typography-international testing scenarios

components/css/page.scss
Fixes Typekit loading timeout issues in Brave, as reported by Mick.
=> docs: don't have typekit fix in there twice

backstop_data/packageDependentMap.json, tools/test-builder/index.js, tools/test-builder/plugins/scenarioList.js
1. Regenerated the package dependent map
2. Fixed the out put path for gulp taks `test:init`
=> fix(test): test-builder sub module

components/css/responsiveImage.scss, components/css/section.scss
Fixing 2 bugs here: 
[SDS-3250](https://jira.corp.adobe.com/browse/SDS-3250) and another unlogged bug that makes the responsive image take too much with and being cut-off with the page-overflow. 
2 minor changes.
This appears to be happening because the sections.scss file got copied from https://git.corp.adobe.com/Spectrum/spectrum-documentation-website/blob/551be27863dbd31fd39a4958df3f85fa7bb95195/components/css/section.scss#L1
I have removed the margin and went through a couple of other pages to ensure it doesn't break anything.
Go to a couple of pages like:
1. http://localhost:5000/get-started
2. http://localhost:5000/components/avatar/
Before:
After:
=> fix: removing section margin and fixing responsive image (SDS-3250)

pages/index.js
Remove unnecessary link to guidelines.
- **How this was tested:** n/a
=> docs: remove guidelines link for platform support

pages/components/id.js
As a following PR of https://github.com/adobe/spectrum-css/pull/369
@lazd
=> Fix: Github to GitHub in nextjs branch

components/PageHeader.js
Give the heading more room.
- **How this was tested:** Check *Getting Started* page, the heading shouldn't wrap at 1440px wide
=> docs: max the headroom for the headings

README-legacy.md
Discussed in #372, reference has moved.
=> docs(readme-legacy): fix example reference

.github/ISSUE_TEMPLATE/--bug-report.md
Simple github issue template fix.
=> fix: typo in issue template

package.json, yarn.lock
Fix another security vulnerabilities introduced by handlebars.
=> fix(security): upgrade handlebars to fix security vulnerabilities

components/inputgroup/index.css
This PR makes the dash a reasonable length.
- **How this was tested:** Load up, look at, be less long
=> fix: use endash for Date range picker, fixes #440

components/calendar/index.css
This fixes the Datepicker disco.
- **How this was tested:** it wasn't, but I bet it works
=> fix: remove transition from dates in calendar, fixes #438

components/well/index.css
This PR adds local tokens for Well so it scales correctly. Once https://git.corp.adobe.com/Spectrum/spectrum-dna/pull/353 is merged, we can remove these local tokens.
- **How this was tested:** With me eyes
=> fix: implement local tokens for Well, fixes #422

README.md
=> docs: added nextjs deployment instructions to README, closes #404

css/main.scss
Remove CSS that never should have been.
- **How this was tested:** look with me eye and see what I see
=> fix: remove override of table styles, fixes #448

components/checkbox/index.css, components/radio/index.css, components/statuslight/index.css, components/toggle/index.css
Correcting the top margin for checkboxes & radio buttons.
https://jira.corp.adobe.com/browse/SDS-4420 closes #406,
https://jira.corp.adobe.com/browse/SDS-4418 closes #402,
https://jira.corp.adobe.com/browse/SDS-4403 closes #403
https://jira.corp.adobe.com/browse/SDS-4472 closes #426 
Corrects #412
same as https://github.com/adobe/react-spectrum-v3/pull/138
Inspected pages: 
http://localhost:3000/docs/radio.html
http://localhost:3000/docs/checkbox.html
http://localhost:3000/docs/toggle.html
http://localhost:3000/docs/switch.html
=> fix: aligning labels #406, #402, #403, #426

components/popover/metadata/popover.yml
Remove success popover example.
Fixes #465 
VR: https://spectrum-visual-regression.ci.corp.adobe.com/job/spectrum-css-vr-test-asset/161/artifact/spectrum-css/backstop_data/html_report/index.html
=> docs: remove success popover example

components/textfield/index.css, components/textfield/metadata/textarea.yml, components/textfield/metadata/textfield.yml
This PR corrects the vertical alignment of Textarea (fixes #489) and the horizontal alignment of Textarea (fixes #454)
- **How this was tested:** Screenshot, paste over designs
Spectrum CSS screenshot overlayed on Spectrum design:
React Spectrum V2:
React Spectrum V3:
=> fix: Textarea/Textfield alignment

backstop_data/backstop_scenarios.json, backstop_data/packageDependentMap.json
=> test: update vr scenarios

.travis.yml, backstop_data/deploy_comment.sh, backstop_data/push.yml, components/accordion/index.css, package.json, yarn.lock
Provide the public accessible VR test result
1. Switch the VR reference package to a much smaller one - `@spectrum-css/spectrum-css-vr-test-assets-essential`. It would increase the inner scalability as the VR result branch could store more results with an acceptable branch merging speed.
2. VR result will be published to [adobe/spectrum-css-vr-results](https://github.com/adobe/spectrum-css-vr-results/tree/gh-pages)
3. The VR result will only be deployed when the change is triggered by PR and test failed.
Tested with my fork of spectrum-css: https://github.com/jianliao/spectrum-css/pull/80
https://github.com/jianliao/spectrum-css-vr-test-result/tree/gh-pages
=> test: public accessible vr result

.travis.yml, backstop_data/deploy_comment.sh, backstop_data/push.yml, package.json, yarn.lock
To get public accessible VR result
=> feat: enable public vr result for rtl branch

backstop_data/deploy_comment.sh, components/accordion/index.css
=> test: vr report enhancement to include the dev site

components/treeview/index.css, components/treeview/metadata/treeview.yml, components/vars/css/components/spectrum-treeview.css
Comments from designer: https://adobedesign.slack.com/archives/GEFETJ9BR/p1583183591233400?thread_ts=1583183591.233400
https://reactspectrum.blob.core.windows.net/reactspectrum/c9500ee4a9c5d87b188ddf12c93920da1f72305a/storybook/index.html?path=/story/tree--sections
```html
<ul class="spectrum-TreeView" style="width: 250px">
<div class="spectrum-TreeView-heading">Section 1</div>
<li class="spectrum-TreeView-item">
<a class="spectrum-TreeView-itemLink" href="#">
<svg class="spectrum-Icon spectrum-UIIcon-ChevronRightMedium spectrum-TreeView-indicator" focusable="false" aria-hidden="true">
<use xlink:href="#spectrum-css-icon-ChevronRightMedium" />
</svg>
Group 1
</a>
<ul class="spectrum-TreeView">
<li class="spectrum-TreeView-item">
<a class="spectrum-TreeView-itemLink" href="#">Layer 2</a> …
```
=> feat: add Treeview heading (via RSP V3)

components/searchwithin/index.css, components/searchwithin/metadata/searchwithin.yml
=> fix: make SearchWithin use new Textfield markup

components/pagination/index.css, components/pagination/metadata/pagination-explicit.yml, site/truncation.pug, site/wrapping.pug
`Pagination - Explicit` and Textfield Examples in `Truncation` study are broken by #615 .
**Pagination - Explicit**
**Truncation**
**Wrapping**
**Pagination - Explicit**
**Truncation**
**Wrapping**
=> fix: fix the broken examples introduced by textfield refactor

components/breadcrumb/index.css, components/breadcrumb/metadata/breadcrumb.yml, components/breadcrumb/skin.css
Removed `spectrum-Breadcrumbs--title`
Fixed #139 
=> feat: breadcrum component change for rsp@v3

components/link/index.css, components/link/metadata/link.yml, components/link/skin.css
=> feat: link component change for rsp@v3

components/actiongroup/index.css
=> fix: quiet compact Action Group margin

package.json, yarn.lock
Current master build failed on vulnerabilities check, this PR is to fix it.
=> fix: fix security vulnerabilities - http_proxy

components/splitbutton/index.css, components/splitbutton/metadata/splitbutton.yml
#731
- **How this was tested:** Scrolly scroll
With `--spectrum-alias-border-radius-small`
Not gonna lie, that looks kinda weird...
=> fix: correct focus ring for SplitButton, fixes #731

components/accordion/index.css, yarn.lock
`accordion` is a contribution with a UI kit, so I removed most of the hardcoded values in favor of DNA accordion tokens and calculated tokens based on DNA accordion tokens.
Closes #806 
- MacOS Version 85.0.4183.83 (Official Build) (64-bit)
Old: 
New:
=> Spectrum tokens 17 accordion

components/dialog/metadata/dialog.yml, components/divider/metadata/divider.yml, components/popover/metadata/popover.yml, components/tray/metadata/tray.yml, site/get-started.pug, site/includes/footer.pug, site/includes/section.pug, site/templates/siteComponent.pug
Fixes #832 
Migration guide added.
All references to `.spectrum-Rule` replaced with `.spectrum-Divider` in all documentation and in site template.
Deprecated Typography in Divider docs swapped out with the new new.
=> Spectrum Tokens 17 Divider

components/well/metadata/well.yml
Fixed deprecated Typography usage
Fixes #830
=> Spectrum Tokens 17 well

components/avatar/index.css, components/tags/metadata/tags.yml
Fixed #819 #870 
CSS:
DL:
CSS:
DL:
=> Spectrum tokens 17 avatar

components/actiongroup/metadata/actiongroup.yml, components/actionmenu/metadata/actionmenu.yml, components/button/metadata/button-primary.yml
Fixed #813 
1. Workflow icon size was changed to medium.
=> Spectrum tokens 17 button

components/rating/metadata/rating.yml, components/rating/skin.css
Fixes #867
Fix selected Rating star color, emphasized hover color
Correct Emphasized examples, add note about quiet/emphasized
=> Spectrum Tokens 17 Rating

components/toast/index.css
Fixes #871 
Fixes line-height of Toast content
=> Spectrum Tokens 17 Toast

components/steplist/metadata/steplist.yml
=> Spectrum Tokens 17 Steplist

components/colorloupe/index.css
Fixes #815
This PR handles all color controls.
1. Color handle - Loupe positioning was affected by circular variable reference
2. Color slider - No problems.
3. Color wheel - No problems
4. Color area - No problems
5. Color loupe - Loupe positioning was affected by circular variable reference
=> Spectrum Tokens 17 color controls

components/card/index.css, components/card/metadata/card-asset.yml, components/card/metadata/card-gallery.yml, components/card/metadata/card.yml, components/card/package.json, components/card/skin.css
Fixed #811 
1. Text line-height change caused by typography - expected
2. `More` icon size change - fixed
3. Card title font-color and font-weight change to match the DL
Line-height change caused by the text in footer and card title font color/weight change.
DL:
=> Spectrum tokens 17 card

components/button/metadata/actionbutton.yml, components/cyclebutton/metadata/cyclebutton.yml
Fixes #908 
Fixes #814
Fixes icon sizing in CycleButton and ActionButton, and sounds like the quiet selected border change causing ActionGroup and ActionButton was intended, so we're good there.
=> Spectrum Tokens 17 actionbutton

components/tabs/metadata/tabs.yml
Change workflow icon size to medium.
After apply the change, only two scenarios failed. They're caused by line-height change.
=> Spectrum tokens 17 tabs

site/truncation.pug, site/wrapping.pug
1. Fix markup caused by component rename.
2. Fix component dependencies of these two pages
Fixed #928 
=> Spectrum Tokens 17 - Wrapping and Truncation page

components/switch/metadata/switch.yml
Added migration guides
closes #137 
closes #460 
closes #855
=> Spectrum tokens 17 switch

components/divider/metadata/divider.yml, components/inputgroup/metadata/datepicker.yml, components/menu/metadata/menu.yml, components/quickaction/metadata/quickaction.yml, components/treeview/metadata/treeview.yml
Workflow icon size small --> medium
=> Spectrum tokens 17 icon

components/progressbar/metadata/progressbar.yml, components/progresscircle/metadata/progresscircle.yml, components/slider/metadata/slider.yml, components/switch/metadata/switch.yml, components/tray/metadata/tray.yml
Add migration guides for:
* Progress circle
* Progress bar
* Dial (inside of slider)
Correct casing
* Progress circle/Progress bar
Add Spectrum site links
* Tray
=> docs: add migration guides and Spectrum site links, correct casing

backstop_data/backstop_scenarios.json, backstop_data/packageDependentMap.json
As we just merged token update branch in, quite a few component name got renamed and new component added. This is the PR for updating the VRT scenarios definition.
=> Update VRT scenarios for new components

components/slider/index.css, site/resources/js/enhancement.js
Closes #965, Closes #966 
- **How this was tested:** See screenshots in the issues
- **Browser(s) and OS(s) this was tested with:**  85.0.4183.102, macOS 10.15
=> Slider: remove cursor: pointer and reenable active style

components/actionbutton/index.css, tools/component-builder/css/processors.js, tools/component-builder/package.json, tools/postcss-dropdupedvars/README.md, tools/postcss-dropdupedvars/expected/dupes.css, tools/postcss-dropdupedvars/fixtures/dupes.css, tools/postcss-dropdupedvars/index.js, tools/postcss-dropdupedvars/package.json, tools/postcss-dropdupedvars/test.js, tools/postcss-dropunusedvars/README.md, tools/postcss-dropunusedvars/expected/unused.css, tools/postcss-dropunusedvars/fixtures/unused.css, tools/postcss-dropunusedvars/index.js, tools/postcss-dropunusedvars/package.json, tools/postcss-dropunusedvars/test.js, tools/postcss-remapvars/README.md, tools/postcss-remapvars/expected/find-replace.css, tools/postcss-remapvars/expected/regexp.css, tools/postcss-remapvars/fixtures/find-replace.css, tools/postcss-remapvars/fixtures/regexp.css, tools/postcss-remapvars/index.js, tools/postcss-remapvars/package.json, tools/postcss-remapvars/test.js, yarn.lock
This PR adds tools for t-shirt sizing that makes it simple to bolt it on to any existing component.
Action Button has been retrofitted with the new tooling to highlight the differences
1. Write out each t-shirt size, call `@remapvars {}` with `find` and `replace`, then simply use the size-agnostic variables. Most components already use size-agnostic variable names, so its possible no additional code will have to be modified:
```css
.spectrum-ActionButton--sizeS {
@remapvars {
find: --spectrum-actionbutton-s-;
replace: --spectrum-actionbutton-;
}
}
.spectrum-ActionButton--sizeM {
@remapvars {
find: --spectrum-actionbutton-m-;
replace: --spectrum-actionbutton-;
}
}
/* ... */
.spectrum-ActionButton {
block-size: var(--spectrum-actionbutton-height);
/* ... */
}
```
2. During processing, the …
=> T-shirt sizing tooling

tools/bundle-builder/package.json, tools/component-builder/package.json, yarn.lock
Fixes security issue
- Checked in Chrome
- Build Locally
=> Update Browser Sync

package.json, yarn.lock
=> test: upgrade backstopjs to latest version

components/fieldlabel/metadata/form.yml, components/inputgroup/metadata/combobox.yml, components/inputgroup/metadata/datepicker.yml, components/picker/index.css, components/picker/metadata/picker.yml, components/searchwithin/metadata/searchwithin.yml, site/wrapping.pug
BREAKING CHANGES: picker requires t-shirt size. closes #940.
=> Added t-shirt sizes to picker

components/actionbar/metadata/actionbar.yml, components/assetlist/metadata/assetlist.yml, components/card/metadata/card-asset.yml, components/card/metadata/card-gallery.yml, components/card/metadata/card.yml, components/checkbox/index.css, components/checkbox/metadata/checkbox.yml, components/fieldgroup/metadata/fieldgroup.yml, components/fieldlabel/metadata/form.yml, components/miller/metadata/miller.yml, components/table/metadata/table.yml, site/templates/halo-focus.pug, site/wrapping.pug
BREAKING CHANGE: a t-shirt size class is now required for checkbox.
closes #951
=> Added t-shirt sizes to checkbox

components/inlinealert/.npmignore, components/inlinealert/CHANGELOG.md, components/inlinealert/README.md, components/inlinealert/gulpfile.js, components/inlinealert/index.css, components/inlinealert/metadata/inlinealert.yml, components/inlinealert/package.json, components/inlinealert/skin.css
Adding updated alert back as inlinealert to be more in line with DNA
=> Inlinealert

components/link/skin.css, package.json, yarn.lock
Replacing https://github.com/adobe/spectrum-css/pull/1126 with this or so I can collaborate on it.
=> High contrast links

components/radio/skin.css
Replacing https://github.com/adobe/spectrum-css/pull/1122 so I can collaborate on it
=> High contrast radio

components/vars/css/components/spectrum-checkbox.css, components/vars/json/spectrum-metadata.json, package.json, site/truncation.pug, yarn.lock
The disabled checkbox box background was filled in wrong
=> Dna 7.0 beta checkbox

components/badge/index.css, components/badge/metadata/badge.yml, components/badge/skin.css
=> fix: correct Badge YML examples, usage of variables

components/treeview/index.css
Partly to test travis integration.
=> fix(tree-view): reduce rule specificity for easier customization

components/helptext/.npmignore, components/helptext/gulpfile.js, components/helptext/index.css, components/helptext/metadata/helptext.yml, components/helptext/package.json, components/helptext/skin.css
Added the new HelpText component
=> feat: added helptext component

components/statuslight/index.css
Fixes #1218 by replacing the word dog with dot
Not sure if relevant but not needed.
=> Fixes spelling mistake

site/resources/js/site.js, site/templates/siteComponent.pug
Fixes #1309, they're pretty now
Fixes #1308, selection persists when navigating (fastload only, of course)
=> fix: vars switcher issues

components/sidenav/index.css
=> fix: focus-ring on SideNav, closes #1317

site/templates/siteComponent.pug
Express menu wasn't appearing for local development for me, this fixes it and should also make it appear in prod.
=> docs: make Express menu always appear

components/actionbutton/index.css, components/actiongroup/index.css, components/button/skin.css
SWC requested that we update this property by changing a vars definition.
=> Actiongroup focus ring

components/expressvars/custom.css, components/slider/index.css, components/slider/metadata/slider.yml, components/slider/skin.css, components/vars/custom.css
This PR removes the gap between the slider handle and the track for Express, as well as fixes rounding of the handle (it was already bigger).
=>  fix: support Express Slider

components/expressvars/custom.css, components/fieldlabel/metadata/fieldlabel.yml
This is not ready to merge; waiting on t-shirt sizes from Design.
=> Express field label

components/picker/index.css
=> Express Picker

components/cyclebutton/metadata/cyclebutton.yml
=> Replace CirclePlay and CirclePause with Play and Pause icons

components/tag/index.css
=> fix: stick to a single selector for consistency in tag clearbutton

components/thumbnail/index.css
Just trying out @Westbrook 's potential solution mentioned in [this issue](https://github.com/adobe/spectrum-css/issues/1334).
=> Add z-index to thumbnail

components/infieldbutton/package.json, tools/component-builder/package.json, yarn.lock
=> chore: update deps

netlify-build-ignore.sh, netlify.toml, package.json
=> chore: exclude main when running builds

components/actionbar/metadata/actionbar.yml, components/actiongroup/metadata/actiongroup.yml, components/actionmenu/metadata/actionmenu.yml, components/breadcrumb/metadata/breadcrumb.yml, components/calendar/package.json, components/card/metadata/card.yml, components/cyclebutton/metadata/cyclebutton.yml, components/divider/metadata/divider.yml, components/picker/package.json
Action Button now requires the `spectrum-ActionButton-icon`
class to be included with the icon. 
Visually
=> Updating components that use Action Button to the latest markup

components/tokens/gulpfile.js, components/tokens/package.json, tools/bundle-builder/dev/index.js, yarn.lock
=> build: support live-reload for token custom value changes (CSS-225)

components/tokens/custom-spectrum/custom-large-vars.css, components/tokens/custom-spectrum/custom-medium-vars.css, components/tokens/custom-spectrum/custom-vars.css
This adds several custom properties to help support font styling. Additionally, this adds custom properties for medium/large scales for radio.
These are the same changes that are made in other branches, but we need to release this tokens package separately from those branches because they will be released as betas initially.
=> chore(tokens): add global vars for radio scales & font sizing

components/tokens/package.json, yarn.lock
* Updates `@adobe/spectrum-tokens` to the latest release to fix an issue where scale output was incorrect
* Updates `style-dictionary-sets` to the latest release
=> chore(tokens): update dependencies to latest versions

components/tokens/package.json, yarn.lock
Updates to the latest core tokens package, which includes tokens for Swatch.
=> chore(tokens): update to latest core tokens release

package.json
=> test: update VRT baseline images

components/commons/overlay-coretokens.css, components/overlay/package.json, components/popover/index.css
=> fix: adjust import for overlay

README.md, gulpfile.js, package.json, tools/bundle-builder/dev/index.js, tools/bundle-builder/docs/index.js, tools/bundle-builder/index.js, yarn.lock
=> chore: build tool tweaking

package.json
This adds a new npm script to perform a clean and build before releasing betas from packages.
=> feat: add beta-from-package release script

README.md
=> docs: clarify prerelease process & document from-package cmd

components/actiongroup/gulpfile.js, components/actiongroup/index.css, components/actiongroup/metadata/actiongroup.yml, components/actiongroup/package.json, components/actiongroup/themes/express.css, components/actiongroup/themes/spectrum.css, yarn.lock
Migrates ActionGroup to core tokens. Also consumes latest version of ActionButton
=> feat(actiongroup)!: migrate to core tokens

components/swatchgroup/gulpfile.js, components/swatchgroup/index.css, components/swatchgroup/package.json, components/swatchgroup/themes/express.css, components/swatchgroup/themes/spectrum.css, yarn.lock
This was a really simple one.
- Update spacing tokens
Tested locally referencing the SwatchGroup XD file.
=> feat(swatchgroup)!: migrate swatchgroup to core tokens

components/actionbutton/index.css, components/actionbutton/themes/spectrum.css, components/checkbox/index.css, components/closebutton/index.css, components/helptext/index.css, components/radio/index.css, components/swatch/index.css, components/switch/index.css, components/tokens/package.json, tools/component-builder-simple/package.json, yarn.lock
=> refactor!: update to latest tokens release

components/tokens/package.json, yarn.lock
=> feat(tokens)!: use latest spectrum-tokens package

components/actionbar/index.css, components/badge/index.css, components/checkbox/index.css, components/fieldlabel/index.css, components/helptext/index.css, components/progressbar/index.css, components/radio/index.css, components/statuslight/index.css, components/toast/index.css
=> fix: resolve missing tokens errors due to name changes

.gitignore, .vscode/settings.json, README.md, components/button/stories/button.stories.js, components/button/stories/template.js, components/helptext/stories/helptext.stories.js, components/helptext/stories/template.js, package.json, site/includes/nav.pug, tools/preview/README.md, tools/preview/assets/index.css, tools/preview/assets/logo.svg, tools/preview/decorators/contextsWrapper.js, tools/preview/decorators/index.js, tools/preview/decorators/reduceMotion.css, tools/preview/icons.js, tools/preview/main-head.html, tools/preview/main.js, tools/preview/manager.js, tools/preview/package.json, tools/preview/preview-head.html, tools/preview/preview.js, yarn.lock
- Add storybook with button & helptext example
- Add global css to storybook
Commands added:
`yarn start`: Builds components & spins up storybook; opens localhost in browser
`SKIP_BUILD=true yarn start`: Sneaky way to suppress the pre-build components step.
https://pr-1539--spectrum-css.netlify.app/preview/?path=/story/button--default
=> chore: Storybook implementation

components/tokens/package.json, yarn.lock
* updates `@adobe/spectrum-tokens` from `12.0.0-beta.60` to `12.0.0-beta.63`
* [beta.63 release notes](https://github.com/adobe/spectrum-tokens/releases/tag/v12.0.0-beta.63)
* [beta.62 release notes](https://github.com/adobe/spectrum-tokens/releases/tag/v12.0.0-beta.62)
* [beta.61 release notes](https://github.com/adobe/spectrum-tokens/releases/tag/v12.0.0-beta.61)
=> feat(tokens): use spectrum-tokens v12.0.0-beta.63

.github/CONTRIBUTING.md, README.md, components/README.md, package.json, tools/generator/package.json, tools/generator/plopfile.js, tools/generator/templates/.npmignore.hbs, tools/generator/templates/README.md.hbs, tools/generator/templates/gulpfile.js.hbs, tools/generator/templates/index.css.hbs, tools/generator/templates/metadata/{{ folderName }}.yml.hbs, tools/generator/templates/package.json.hbs, tools/generator/templates/stories/template.js.hbs, tools/generator/templates/stories/{{ folderName }}.stories.js.hbs, tools/generator/templates/themes/express.css.hbs, tools/generator/templates/themes/spectrum.css.hbs, yarn.lock
This PR introduces 2 new generators for the project (and corresponding documentation):
1. `yarn new component`
2. `yarn new story`
The component generator prompts the user for a component name (in human-readable format) and will reject the input if the name already exists in the library.  When run, it will generate a component using the new token system format and will include the storybook templated assets.  After generating the files, it will run `yarn install` to register the component in the monorepo.
The story generator asks the user to type the name of an existing component (using an autocomplete feature) and it will generate a new stories directory with \*.stories.js and template.js assets. In the template.js asset, you will note that it includes an example of markup which was …
=> chore: component generator [CSS-317]

.github/CONTRIBUTING.md, README.md, tools/bundle-builder/README.md
Updating documentation to reflect current browser support and a few minor markdown linting updates.
=> docs: update readme documentation for IE11

components/breadcrumb/themes/express.css, components/breadcrumb/themes/spectrum.css
=> chore(breadcrumb): remove whitespace

components/picker/index.css, components/textfield/index.css
=> fix(textfield,picker): restore missing vars

components/picker/gulpfile.js, components/picker/index.css, components/picker/metadata/picker.yml, components/picker/package.json, components/picker/themes/express.css, components/picker/themes/spectrum.css, components/tokens/custom-express/custom-vars.css, yarn.lock
Refactor Picker to use core tokens and update WHCM.
- Add Field Label example
- Add Progress Circle example
- Chrome
- WHCM
- Medium, Large scale
=> refactor(picker)!: use spectrum tokens

components/actionbar/stories/template.js, components/actiongroup/stories/template.js, components/clearbutton/stories/template.js, components/coachmark/stories/template.js, components/fieldlabel/stories/template.js, components/illustratedmessage/stories/template.js, components/modal/stories/template.js, tools/generator/templates/stories/template.js.hbs, tools/generator/templates/stories/{{ folderName }}.stories.js.hbs
This PR tackles 2 small updates:
- Update generator to match the latest storybook syntax
- Update imports in files from `if-definedjs` to `if-defined.js`
=> chore: update storybook generator; fix syntax of import

components/picker/metadata/mods.md
Regenerate the mod docs after updates to Picker.
=> docs(picker): update mod custom properties

components/infieldbutton/stories/infieldbutton.stories.js, components/infieldbutton/stories/template.js
This adds the fields and details needed for the infield button story.
[JIRA CSS-406](https://jira.corp.adobe.com/browse/CSS-406)
=> feat: add infield button story

.husky/commit-msg, .husky/pre-commit, package.json
Husky hooks in package.json were not picking up so this migrates the tasks to the script method.  Confirmed these were working on this commit!
=> chore: husky fix

components/colorarea/stories/colorarea.stories.js, components/colorarea/stories/template.js, components/colorhandle/stories/colorhandle.stories.js, components/colorhandle/stories/template.js
Adds storybook for ColorArea and ColorHandle
Jira Ticket[ CSS-397](https://jira.corp.adobe.com/browse/CSS-397)
Jira Ticket [CSS-398](https://jira.corp.adobe.com/browse/CSS-398)
=> feat:adds storybook for colorarea and colorhandle

components/tokens/custom-express/custom-dark-vars.css, components/tokens/custom-express/custom-darkest-vars.css, components/tokens/custom-express/custom-light-vars.css, components/tokens/custom-spectrum/custom-dark-vars.css, components/tokens/custom-spectrum/custom-darkest-vars.css, components/tokens/custom-spectrum/custom-large-vars.css, components/tokens/custom-spectrum/custom-light-vars.css, components/tokens/custom-spectrum/custom-medium-vars.css
Adds custom Menu tokens to support the Menu migration
=> feat(tokens): adds menu scale and theme tokens

tasks/packageLint.js
=> chore: remove packageJSON reference in package lint script

components/colorarea/stories/template.js, components/colorwheel/stories/colorwheel.stories.js, components/colorwheel/stories/template.js
=> feat: colorwheel storybook

components/inlinealert/stories/inlinealert.stories.js, components/inlinealert/stories/template.js, components/pickerbutton/stories/pickerbutton.stories.js, components/pickerbutton/stories/template.js, components/progresscircle/stories/progresscircle.stories.js, components/progresscircle/stories/template.js, components/statuslight/stories/statuslight.stories.js, components/statuslight/stories/template.js
=> feat: add additional storybook stories

components/pagination/stories/pagination.stories.js, components/pagination/stories/template.js
This PR adds storybook functionality for the Pagination component. I split it up by the two variations: Listing and Explicit
=> feat: pagination storybook

components/assetcard/stories/assetcard.stories.js, components/checkbox/stories/template.js, components/swatchgroup/stories/swatchgroup.stories.js, components/swatchgroup/stories/template.js
Adds the story file and template for [SwatchGroup](https://opensource.adobe.com/spectrum-css/swatchgroup.html)
=> chore(swatchgroup): add story and story template

components/assetlist/stories/assetlist.stories.js, components/assetlist/stories/template.js, components/miller/stories/miller.stories.js, components/miller/stories/template.js
Adds Storybook story data and writes the template for Miller columns.
=> chore(miller): write storybook story & template

components/sidenav/stories/sidenav.stories.js, components/sidenav/stories/template.js
This PR adds four stories for SideNav (Default, Multilevel, WithIcon, and WithHeading) and a template to display them
=> chore(sidenav): add Storybook story and template

components/logicbutton/metadata/logicbutton.yml, components/logicbutton/stories/logicbutton.stories.js, components/logicbutton/stories/template.js
Improves storybook for logicbutton
=> chore(logicbutton): add storybook file and template

components/well/metadata/well.yml, components/well/stories/template.js, components/well/stories/well.stories.js
Adding storybook stuff for Well
=> chore(well): clean up story and template

components/colorarea/stories/template.js, components/colorhandle/stories/template.js, components/colorslider/stories/colorslider.stories.js, components/colorslider/stories/template.js
Adds storys for ColorSlider, Default and Vertical.
=> chore: add storybook for colorslider

components/progressbar/stories/progressbar.stories.js, components/progressbar/stories/template.js
Adds storybook stories and template for progress bar.
Uses FieldLabel component template.
=> chore(progressbar): add story and template

components/splitbutton/stories/splitbutton.stories.js, components/splitbutton/stories/template.js
=> chore(splitbutton): add storybook stories & template

components/tokens/package.json, yarn.lock
Bump token package to the latest release [12.1.0](https://github.com/adobe/spectrum-tokens/releases/tag/v12.1.0)
=> feat(tokens): updates accordion, colorhandle, coachmark, menuitem tokens

components/tokens/package.json, yarn.lock
Minor update to tokens package; unblocks #1556.
=> fix(tokens): add 'px' to zero length value for combobox

.github/workflows/testing.yml, tools/preview/package.json
=> chore: adjust chromatic github action

yarn.lock
=> chore: remove and generate a fresh lock file

.github/dependabot.yml
=> chore: initialize dependabot requirements

.github/dependabot.yml
=> fix: remove typo from dependabot config

.github/dependabot.yml
Ignore Storybook 7.x upgrades in dependabot (CSS-450)
=> chore(dependabot): ignore storybook

components/button/stories/button.stories.js, components/button/stories/template.js
* Fixes an issue where the `iconOnly` variants were not rendering as perfect circles at the `l` and `xl` t-shirt sizes
* Fixes an issue where icons were being set for each Button example in Storybook.
* Adds static background colors for static examples for better rendering.
Here's a list of stories that were affected and always showed an icon when they previously were not:
* Button Group (both default and vertical stories)
* Pagination
* Split Button (all stories)
* Toast
Examples of misshapen iconOnly buttons:
Before:
After:
=> docs(button): only show icons when appropriate in Storybook

.github/PULL_REQUEST_TEMPLATE.md
Adding a reminder to the PR Template to update any relevant stories and temapltes
n/a
n/a
=> chore: add-storybook-to-todo-list

components/tokens/package.json, yarn.lock
Bring in latest Spectrum tokens package - adds tokens for field and picker. [v12.2.0](https://github.com/adobe/spectrum-tokens/releases/tag/v12.2.0)
=> feat(tokens): bring in latest tokens (field, picker)

components/tokens/package.json, yarn.lock
BREAKING CHANGE: updates to `@adobe/spectrum-tokens@12.6.0`.
* Includes additions and deprecations from `12.5.0`
* https://github.com/adobe/spectrum-tokens/releases/tag/%40adobe%2Fspectrum-tokens%4012.5.0
* Includes additions, updates, and deprecations from `12.6.0`
* https://github.com/adobe/spectrum-tokens/releases/tag/%40adobe%2Fspectrum-tokens%4012.6.0
=> chore(tokens)!: use v12.6.0 release of @adobe/spectrum-tokens

components/assetcard/stories/template.js, components/assetlist/stories/assetlist.stories.js, components/colorhandle/stories/template.js, components/colorloupe/stories/template.js, components/quickaction/stories/template.js, components/typography/stories/typography.stories.js
- Fix a few image paths for storybook that weren't rendering
- Optimize typography sections for VRT (snapping 1 image for every size available)
- Remove alignment on color components to reduce snapshot size
=> chore: optimize storybooks for vrt; patch images

components/picker/index.css
=> fix(picker): resolve missing var keyword

components/rating/metadata/mods.md
=> docs(rating): update mods

.github/PULL_REQUEST_TEMPLATE.md
Adds a new to-do to our list of things to take care of upon opening a PR.
=> chore: add design validation to-do to PR template

components/actionbutton/stories/actionbutton.stories.js, components/calendar/stories/calendar.stories.js, components/calendar/stories/template.js
In prep for DIY migration of Calendar, this PR updates storybook to more resemble the docs site. 
- Added a disabled story 
- removes Large scale default from Range story 
- Ensures icon sizing is accurate 
- hide dates outside of the current month 
- Removed t-shirt sixing
=> chore(calendar): improve stories

components/dial/stories/dial.stories.js
Adds several new Storybook stories for the Dial component. This will provide more coverage for us as we migrate it to the new tokens system.
=> docs: add Dial stories to provide more state coverage

.github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE/--bug-report.md, .github/ISSUE_TEMPLATE/--documentation-issue.md, .github/ISSUE_TEMPLATE/--feature-request.md, .github/ISSUE_TEMPLATE/--support-request.md, .github/PULL_REQUEST_TEMPLATE.md, .github/dependabot.yml
Updates PR & issue templates to reflect small changes to our build and test workflow. Improve the examples for how to write a good test case and instructions on validating the tests completion.
=> chore: update pr and issue templates

components/tokens/custom-spectrum/custom-large-vars.css, components/tokens/custom-spectrum/custom-medium-vars.css, components/tokens/package.json, yarn.lock
=> feat(tokens): update to spectrum-tokens 12.4.0

components/tokens/custom-spectrum/custom-dark-vars.css, components/tokens/custom-spectrum/custom-darkest-vars.css, components/tokens/custom-spectrum/custom-light-vars.css
Adds custom tokens need for the DIY migration of Calendar. #1988 
Validate:
=> chore(tokens): adds custom tokens for calendar

components/tokens/custom-spectrum/custom-dark-vars.css
Addresses an error in the custom tokens for calendar as pointed out: https://github.com/adobe/spectrum-css/pull/1988#pullrequestreview-1535533357  where an incorrect value was used for the focus state of a calendar day when viewed in dark. 
Validate:
=> chore(tokens): update custom token for calendar

components/tokens/package.json, yarn.lock
* Adds `menu-item-section-divider-height`
Validate:
=> feat(tokens): update to spectrum tokens v12.16.0

components/toast/index.css, components/toast/metadata/mods.md, components/toast/metadata/toast.yml, components/toast/stories/template.js, components/toast/stories/toast.stories.js
Update Toast component to use token for Toast max width
Expand storybook to include all variants 
Open to [storybook](url) for the Toast component:
Open to [the docs site](url) for the Toast component:
Validate:
=> chore(toast): add max width token

components/colorhandle/index.css
Addresses [CSS-559](https://jira.corp.adobe.com/browse/CSS-559) and SWC issue [3443](https://github.com/adobe/spectrum-web-components/issues/3433) which reported issues with the animation to the focused state for the ColorHandle. 
Switching from targeting individual properties to `all` addressed the animation issue in safari
Validate:
=> fix(colorhandle): updates animation

components/radio/index.css, components/radio/stories/radio.stories.js, components/radio/stories/template.js, components/radio/themes/express.css, components/radio/themes/spectrum.css
Updated Radio (button) to use new color tokens for selected, not emphasized variants. 
- removed no longer needed theme specific tokens
- added Disabled, Emphasized and Read only variants to storybook
1. Open the [storybook](https://pr-2045--spectrum-css.netlify.app/preview/?path=/docs/components-radio--docs) for the Radio component:
2. Open the [Docs Site](https://pr-2045--spectrum-css.netlify.app/radio) for the Radio component:
@jawinn :
Validate:
2. A migrated documentation page (such as [action …
=> fix(radio): update selected color tokens

components/icon/package.json, components/tokens/package.json
=> revert(icon,tokens): use correct package version numbers

components/splitbutton/metadata/splitbutton.yml
Updates SplitButton to recommend usage of button group and links to relevant documentation. 
[Jira Ticket](https://jira.corp.adobe.com/secure/RapidBoard.jspa?rapidView=33123&projectKey=CSS&view=detail&selectedIssue=CSS-382) 
1. Open the [Docs Site](https://pr-2134--spectrum-css.netlify.app/splitbutton) for the Split Button component:
Validate:
=> docs(splitbutton): update usage notes

components/actionmenu/gulpfile.js, components/actionmenu/package.json, components/actionmenu/themes/express.css, components/actionmenu/themes/spectrum.css, yarn.lock
=> chore(action-menu): diy migration

components/menu/index.css, components/menu/metadata/menu.yml, components/menu/metadata/mods.md, components/menu/package.json, components/menu/stories/menu.stories.js, components/menu/stories/template.js
This PR adds examples and styling for a multi-select menu option using the Checkbox component, and a multi-select menu option using the Switch component. 
[CSS-245](https://jira.corp.adobe.com/browse/CSS-245)
@jawinn 
1. Visit the [docs site](https://pr-2152--spectrum-css.netlify.app/menu) for Menu
2. Visit the [storybook](https://pr-2152--spectrum-css.netlify.app/preview/?path=/docs/components-menu--docs) for Menu
@jawinn 
Validate:
1. A legacy documentation page (such as [accordion](https://pr-2152--spectrum-css.netlify.app/accordion.html)), including:
4. A migrated documentation page (such as [action group](https://pr-2152--spectrum-css.netlify.app/actiongroup.htm …
=> feat(menu): multi select and switch

components/tokens/package.json, yarn.lock
=> feat(tokens): adds ui icons tokens via Spectrum Tokens

components/sidenav/index.css, components/sidenav/metadata/mods.md, components/tokens/custom-spectrum/custom-large-vars.css, components/tokens/custom-spectrum/custom-medium-vars.css
Removes custom tokens and use newly updated side nav tokens. 
Remove no longer needed TODO comments 
Updates SideNav with additional --mod properties 
1. Open the docs site for side nav 
Validate:
3. A migrated documentation page (such as [action group](https://pr-###--spectrum-css.netlify.app/actiongroup.html)), including:
=> fix(sidenav): Remove side nav temporary custom tokens

components/contextualhelp/index.css, components/tokens/package.json, yarn.lock
* Takes in the latest release from `@adobe/spectrum-tokens` which contains a fix for an incorrect token for ContextualHelp
* Refactors away a redefinition of an already existing custom property provided by `@adobe/spectrum-tokens`—we can just use the custom property directly as delivered
* By virtue of the fix coming from Spectrum Tokens, the font-size issues within ContextualHelp are now resolved.
Validate:
=> fix(tokens): use latest spectrum-tokens release (v12.22.1)

.github/workflows/build.yml, .github/workflows/compare-results.yml, .github/workflows/lint.yml, .github/workflows/publish-site.yml, .github/workflows/vrt.yml
=> chore(ci): remove dynamically named ci so we can require it for pull requests

.github/actions/file-diff/package.json, generator/package.json, tokens/package.json, tools/component-builder/package.json
=> chore: manual version bumps

components/steplist/index.css
Open [StepList on the docs site](https://pr-2308--spectrum-css.netlify.app/steplist) and emulate WHCM: 
Validate:
=> fix(steplist): add WHCM for marker

components/popover/stories/popover.stories.js, components/popover/stories/template.js
The Nested story for Popover has never quite worked. I added some logic to the existing Storybook template to turn off implementation for the Nested example in favor of a static and open example.
[Nested story](https://pr-2314--spectrum-css.netlify.app/preview/?path=/story/components-popover--nested):
[Default story](https://pr-2314--spectrum-css.netlify.app/preview/?path=/story/components-popover--default):
[With Tip story](https://pr-2314--spectrum-css.netlify.app/preview/?path=/story/components-popover--with-tip&args=isOpen:!true):
Validate:
2. If components have been …
=> fix(popover): nested storybook example is open and static

.github/actions/file-diff/index.js
Currently the file diff script is reporting on the size of packages by adding together the size of all files in the dist directory.  This is not an accurate view of a package's size because users are not expected to pull down and use every file we provide.
This update reports back on the file size change of the main CSS asset (index.css) and adds additional context to the footer of the comment to clarify this point.
=> chore(ci): clean file diff output

.github/actions/file-diff/index.js, .github/workflows/build.yml, .github/workflows/publish-site.yml, package.json, tasks/compare-compiled-output.js, tokens/package.json, tokens/project.json, yarn.lock
Migrate tokens workflow from package.json into the project.json for nx to manage.
Validate that the rendered tokens output is identical.
=> chore(tokens): move tasks to nx workflow

tools/bundle-builder/lib/depUtils.js, tools/component-builder/package.json
A few minor package updates to the legacy builders to prepare for the migration to NX.
Expect no regressions in build process.
=> chore(bundle-builder,component-builder): minor preparations for nx migration

ui-icons/package.json
=> chore(ui-icons): publish public access

.storybook/package.json, tools/bundle-builder/package.json, ui-icons/package.json
Manual 1.0 release graduation.
=> feat(ui-icons): graduate to 1.0 release

components/sidenav/stories/sidenav.stories.js, components/slider/stories/slider.stories.js, components/statuslight/stories/statuslight.stories.js, components/statuslight/stories/template.js, components/switch/stories/switch.stories.js, components/switch/stories/template.js, components/tag/stories/tag.stories.js, components/tag/stories/template.js, components/tray/stories/template.js, components/tray/stories/tray.stories.js
=> docs: storybook wrap, truncate examples part 3

components/checkbox/index.css
=> fix(checkbox): address typo

.github/workflows/vrt.yml, .storybook/project.json
* Specifies the Storybook base directory in the workflow file so that Chromatic can figure out where our stats file is.
* Updates the project.json to generate and keep a Storybook stats file upon build
Validate:
=> ci: update storybook & chromatic settings for turbosnap

components/coachindicator/index.css, components/coachindicator/metadata/coachindicator.yml, components/coachindicator/metadata/mods.md, components/coachindicator/stories/coachindicator.stories.js
Previously the CoachIndicator rings were not centered with in the CoachIndicator component. 
Changes: 
- updates `calc()` for `--spectrum-coach-indicator-top` and `--spectrum-coach-indicator-left` (includes border width) 
- add inline-size and inline-block (so component size not only set with min) 
- updates storybook to display group in Chromatic
Testing Note:  if you add `background-color: red;` to the CoachIndicator you can better see the position for the rings
On docs site: 
In Storybook:
Validate:
=> fix(coachindicator): address issues with coach indicator rings position

components/accordion/stories/accordion.stories.js, components/accordion/stories/template.js
Currently in [Storybook for Accordion](https://opensource.adobe.com/spectrum-css/preview/?path=/story/components-accordion--default&args=disableAll:!true), when you toggle "disabled" to true in the control panel, accordion items still open and close. They should not be toggle-able when disabled. 
Changes: 
- Update name for the `disableAll` control to be more clear 
- Remove ability to click accordion items when `disableAll === true` 
- Expand chromatic coverage to include a `disableAll` example 
Open [accordion in storybook ](https://pr-2458--spectrum-css.netlify.app/preview/?path=/story/components-accordion--default)
Validate:
1. The documentation pages for at …
=> docs(accordion): addresses issue with disabled state in storybook

components/combobox/stories/combobox.stories.js, components/combobox/stories/template.js
Increase Chromatic coverage for Combobox variants.
Validate:
=> docs(combobox): increase chromatic coverage of variants

.storybook/guides/deprecation.mdx
After walking through splitbutton, @mdt2 noted several good updates for the documentation.
=> docs: deprecation steps update

README.md
Add build status badges to our package README and revamp and clarify our introductory documentation.
[Preview](https://github.com/adobe/spectrum-css/blob/6ed27a620112873b9630ec9298d1041a5d68d2d3/README.md)
=> docs: add badges and formatting to readme

tokens/dist/css/global-vars.css, tokens/dist/css/large-vars.css, tokens/dist/css/medium-vars.css, tokens/dist/css/spectrum/global-vars.css, tokens/dist/css/spectrum/large-vars.css, tokens/dist/css/spectrum/medium-vars.css, tokens/dist/index.css, tokens/package.json, yarn.lock
Takes in the `12.24.0` release of `@adobe/spectrum-tokens`. Release notes with diff are [here](https://github.com/adobe/spectrum-tokens/releases/tag/%40adobe%2Fspectrum-tokens%4012.24.0).
Validate:
=> feat(tokens): use spectrum-tokens@12.24.0

components/asset/gulpfile.js, components/asset/index.css, components/asset/metadata/mods.md, components/asset/package.json, components/asset/stories/asset.stories.js
Migrate the asset component to the updated tokens package.
Validate:
=> refactor(asset): migrate to tokens package

components/accordion/index.css, components/actionbar/index.css, components/actionbutton/stories/template.js, components/actiongroup/stories/template.js
Applying minor stylelint and eslinting fixes to 4 components:
- accordion
- actionbar
- actionbutton
- actiongroup
Expect to see no regressions.
=> chore(accordion, actionbar, actionbutton, actiongroup): apply minor linting fixes

components/alertbanner/index.css, components/alertbanner/stories/template.js, components/alertdialog/stories/template.js, components/asset/stories/template.js, components/assetcard/index.css, components/assetcard/stories/template.js, components/assetcard/themes/express.css, components/assetcard/themes/spectrum.css
Applying minor stylelint and eslinting fixes to 4 components:
- alertbanner
- alertdialog
- asset
- assetcard
* Note: Ran formatter on actionmenu but no changes were needed.
Expect to see no regressions.
=> chore(alertbanner, alertdialog, asset, assetcard): lint fixes

.github/workflows/build.yml, .github/workflows/compare-results.yml, .github/workflows/production.yml, .github/workflows/publish-site.yml, .github/workflows/vrt.yml
For branches with slashes in them, the derived keys were invalid for uploading and downloading artifacts. This corrects that issue and removes legacy SHA code.
=> ci: support slashes in branch names

.github/actions/file-diff/package.json, plugins/stylelint-no-missing-var/package.json, plugins/stylelint-no-unknown-custom-properties/package.json, plugins/stylelint-no-unused-custom-properties/package.json, site/package.json
For publishing, flag our @spectrum-tools packages as private for now.
=> chore: flag private packages

.storybook/decorators/contextsWrapper.js, .storybook/preview.js
=> chore: remove darkest as SB option

package.json, site/includes/nav.pug
=> fix: build storybook as part of site deploy script

components/commons/basebutton.css, components/commons/overlay.css
Run `yarn formatter commons` to ensure the commons assets are properly formatted on main.
=> chore(commons): run format tasks on commons assets

components/infieldbutton/stories/infieldbutton.stories.js, components/sidenav/stories/sidenav.stories.js, components/tabs/stories/tabs.stories.js, components/underlay/stories/underlay.stories.js
Removes remaining migration statuses that we missed in the initial PR:
- in-field button
- side nav
- tabs
- underlay
Validate:
=> docs: remove additional instances of migration status

.storybook/DocumentationTemplate.mdx, .storybook/assets/index.css, .storybook/assets/typekit.js, .storybook/decorators/context.js, .storybook/decorators/sizing.js, .storybook/decorators/testingPreview.js, .storybook/decorators/textDirection.js, .storybook/guides/code_of_conduct.mdx, .storybook/guides/deprecation.mdx, .storybook/guides/develop.mdx, .storybook/guides/releasing.mdx, .storybook/main.js, .storybook/manager.js, .storybook/preview.js, .storybook/project.json, .storybook/types/global.js, .storybook/types/states.js, nx.json
Storybook was not being included in the lint and format tasks. This fixes that and applies the linting fixes to the storybook assets.
Expect no regressions.
=> chore(storybook): add formatting tool

.github/workflows/release.yml
=> chore: add additional prerelease branch

.changeset/dull-pandas-grin.md, components/coachmark/index.css, components/coachmark/themes/spectrum-two.css
=> chore(coachmark): migrate mods

.changeset/soft-pianos-suffer.md, components/colorhandle/index.css, components/colorhandle/themes/spectrum-two.css
=> chore(colorhandle): migrate mods

.github/dependabot.yml
Our team has grown! Expanding reviewers assigned to dependabots to share coverage of these tasks.
Also added postcss-preset-env v10 ignore which has an associated Jira ticket.
=> chore: expand reviewers for dependabot

postcss.config.js
Minor spacing alignment introduced to the CSS output.
Root-level COPYRIGHT content used in prepended licensing as well as standardized formatting.
Validate:
=> build: postcss formatting updates

components/typography/stories/template.js, components/typography/stories/typography.stories.js
Fixes an issue where Storybook seemed to be not correctly processing JS template literals that were being passed through the html function
The `detail` story seemed to be throwing errors while trying to render.
Validate:
=> fix: resolve error in typography story template

.storybook/blocks/ComponentDetails.jsx, .storybook/decorators/language.js, .storybook/loaders/font-loader.js
=> chore(storybook): typekit and react error resolution

components/tag/index.css, components/tag/stories/tag.stories.js, components/tag/stories/template.js
[Migrating Tags docs to Storybook](https://jira.corp.adobe.com/browse/CSS-941)
Validate:
=> docs(tags): migrate docs to storybook

.github/workflows/vrt.yml, nx.json
=> ci: refine branch pointers for selective VRT

.storybook/package.json, yarn.lock
[Chromatic release](https://github.com/chromaui/chromatic-cli/releases/tag/v11.12.0)
=> chore: upgrade chromatic dependency

.changeset/ten-tables-cross.md, components/colorslider/index.css, components/colorslider/metadata/metadata.json
Resolves lint violations by removing unused custom properties.
=> chore(colorslider): remove unused properties

.changeset/ninety-clocks-grin.md, components/infieldbutton/index.css, components/infieldbutton/metadata/metadata.json
Resolves lint violation by removing unused custom property.
=> chore(infieldbutton): remove unused property

.changeset/long-geckos-remember.md, components/menu/index.css, components/menu/metadata/metadata.json
Resolves lint violation by removing unused custom property.
=> chore(menu): remove unused property

.changeset/loud-flies-camp.md, components/statuslight/index.css
just custom property ordering to resolve lint violations.
=> chore(statuslight): adjust declaration order to resolve lint violations

.changeset/hungry-cougars-end.md, components/tag/index.css
Reorder rules and custom properties to resolve lint violations.
=> chore(tag): adjust custom property order to resolve lint violations

.changeset/silly-kids-invite.md, components/tabs/index.css, components/tabs/metadata/metadata.json
Resolves stylelint violation by removing undefined and unused token
=> chore(tabs): remove undefined/unused token

components/actionbutton/stories/actionbutton.test.js
Adds test configurations for active button `isSelected` + `isHovered`, `isFocused`, `isActive`
Validate:
=> chore(actionbutton): add tests for hovered, focused, actuve + selected

.storybook/assets/404.html, .storybook/assets/logo.svg
Resolves an issue where the logo for the 404 page and in the Storybook sidebar was being "clipped" (not fully displaying) in Firefox.
The ultimate fix was to remove extra whitespace in the SVG markup's `<text>`, and also to provide more width when the element was being displayed on the 404 page.
Validate:
=> docs: resolve firefox svg clipping for logo on 404 page

.changeset/weak-kings-pretend.md, tokens/dist/css/dark-vars.css, tokens/package.json, yarn.lock
Takes in the [0.0.0-s2-foundations-20241121221506 release](https://github.com/adobe/spectrum-tokens/releases/tag/%40adobe%2Fspectrum-tokens%400.0.0-s2-foundations-20241121221506) from Spectrum Tokens. This release contains the S2 Foundations non-gray-800 colors update.
Validate:
=> feat: s2 foundations non-gray-800 colors update

components/progresscircle/README.md
Typo in the readme description of the Progress Circle component.
Validate:
=> chore(progresscircle): correct typo in readme

yarn.lock
Resolve the caniuse-lite database update message during the build.
Expect to see no changes to the compiled output.
Validate:
=> chore(caniuse-lite): dependency update

.changeset/light-impalas-march.md, components/swatch/dist/metadata.json, components/swatch/index.css, components/swatch/themes/spectrum-two.css, components/swatch/themes/spectrum.css
Adjusts partially rounded swatch border radius to match S2 spec.
[CSS-1100](https://jira.corp.adobe.com/browse/CSS-1100)
@marissahuysentruyt 
Check out the branch locally (or open the deploy preview).
Validate:
=> fix(swatch): adjust s2 corner rounding

.storybook/CHANGELOG.md, .storybook/decorators/context.js, .storybook/decorators/helpers.js, .storybook/decorators/icon-sprites.js, .storybook/decorators/language.js, .storybook/decorators/testing-preview.js, .storybook/decorators/utilities.js, .storybook/main.js, .storybook/modes/index.js, .storybook/project.json, plugins/postcss-add-theming-layer/package.json, plugins/postcss-property-rollup/package.json, plugins/stylelint-no-missing-var/package.json
This pull request runs the `yarn formatter` command against all workspaces to bring everything up to our current coding standards "automagically".
=> chore: run formatting on all packages as a refresh

components/actionbar/stories/actionbar.stories.js
Adds the migrated tag to the metadata for the action bar component. 
Validate:
=> docs(action bar): add migrated tag

.github/QUICK-START.md, .github/actions/file-diff/README.md, .github/scripts/build-preview-urls-comment.js, .github/scripts/comment-or-update.js, .github/workflows/development.yml, .github/workflows/lint.yml, .github/workflows/production.yml, .github/workflows/publish-site.yml, .github/workflows/vrt.yml
This PR brings over some updates from the spectrum-two branch into main. The changes include:
- **Migration from Netlify to Azure Blob Storage**: Replaced Netlify deployment with Azure Blob Storage for better control and scalability
- **PR-based preview deployments**: Added automatic deployment of documentation previews for each pull request
- **Enhanced cleanup process**: Implemented automatic cleanup of PR deployments when pull requests are closed
- **Improved workflow structure**: Restructured GitHub Actions workflows for better maintainability and performance
- **Updated documentation**: Enhanced quick-start guide and workflow documentation
The migration from Netlify to Azure Blob Storage provides several benefits:
- Better control over deployment infrastructure
- Improved scalability …
=> chore: align build with s2 branch
